<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>MASTEMR - 06 T-tests</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><link rel="stylesheet" href="../css/mastemr.css">
</head>
<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="index.qmd" class="navbar-brand navbar-brand-logo">
    <img src="../images/KCL_logo.png" alt="" class="navbar-logo"></a>
    <a class="navbar-brand" href="index.qmd">
    <span class="navbar-title">MASTEMR</span>
    </a>
  </div>
        <div class="quarto-navbar-tools ms-auto">
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/01-Intro_to_quant_methods.html">Sessions</a></li><li class="breadcrumb-item"><a href="../chapters/07-T-testsPISA.html">06 T-tests</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto"><div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Sessions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-Intro_to_quant_methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">01 Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">02 Introduction to R</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-1-Intro_to_analysis_software.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-2-Intro_to_analysis_software.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Loading packages and exploring data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-3-Intro_to_analysis_software.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Piping and dplyr</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-4-Intro_to_graphs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Making graphs</span></a>
  </div>
</li>
      </ul>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-Descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">03 Descriptive Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-Presentations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">04 Presentations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-Introduction_to_PISA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">05 Introduction to PISA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-ChisqPISA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">07 Chi-square tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-T-testsPISA.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">06 T-tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-Writing_report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">08 Writing a quantitative report</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-Assignment_3_tutorials.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">09 Assignment 3 tutorials</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-Correlation_and_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">10 Correlation and regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-selecting_statistical_tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11 Selecting statistical tools</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-value_of_quant.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">12 The value of quantitative methods</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/QandA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Questions and Answers</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Data sets</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A1-PISA_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PISA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A2-DfE_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DfE England</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A3-TIMSS_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">TIMSS, PIRLS and ICILS</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A4-Other_datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Other datasets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A5-Self_Study_Tasks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix Self Study Tasks</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#pre-reading-and-pre-session-tasks" id="toc-pre-reading-and-pre-session-tasks" class="nav-link active" data-scroll-target="#pre-reading-and-pre-session-tasks"><span class="header-section-number">1</span> Pre-reading and pre-session tasks</a>
  <ul class="collapse">
<li><a href="#pre-reading" id="toc-pre-reading" class="nav-link" data-scroll-target="#pre-reading"><span class="header-section-number">1.1</span> Pre-reading</a></li>
  <li><a href="#pre-session-task" id="toc-pre-session-task" class="nav-link" data-scroll-target="#pre-session-task"><span class="header-section-number">1.2</span> Pre-session task</a></li>
  </ul>
</li>
  <li>
<a href="#t-tests" id="toc-t-tests" class="nav-link" data-scroll-target="#t-tests"><span class="header-section-number">2</span> T-tests</a>
  <ul class="collapse">
<li><a href="#types-of-t-test" id="toc-types-of-t-test" class="nav-link" data-scroll-target="#types-of-t-test"><span class="header-section-number">2.1</span> Types of t-test</a></li>
  <li><a href="#assumptions-of-t-tests" id="toc-assumptions-of-t-tests" class="nav-link" data-scroll-target="#assumptions-of-t-tests"><span class="header-section-number">2.2</span> Assumptions of t-tests</a></li>
  <li><a href="#normality-checking" id="toc-normality-checking" class="nav-link" data-scroll-target="#normality-checking"><span class="header-section-number">2.3</span> Normality checking</a></li>
  <li><a href="#checking-for-equal-variances" id="toc-checking-for-equal-variances" class="nav-link" data-scroll-target="#checking-for-equal-variances"><span class="header-section-number">2.4</span> Checking for Equal Variances</a></li>
  </ul>
</li>
  <li><a href="#performing-t-tests" id="toc-performing-t-tests" class="nav-link" data-scroll-target="#performing-t-tests"><span class="header-section-number">3</span> Performing t-tests</a></li>
  <li><a href="#interpreting-the-output-of-t-tests" id="toc-interpreting-the-output-of-t-tests" class="nav-link" data-scroll-target="#interpreting-the-output-of-t-tests"><span class="header-section-number">4</span> Interpreting the output of t-tests</a></li>
  <li>
<a href="#anova-multiple-t-tests" id="toc-anova-multiple-t-tests" class="nav-link" data-scroll-target="#anova-multiple-t-tests"><span class="header-section-number">5</span> Anova (multiple t-tests)</a>
  <ul class="collapse">
<li><a href="#eta-squared" id="toc-eta-squared" class="nav-link" data-scroll-target="#eta-squared"><span class="header-section-number">5.1</span> Eta-squared</a></li>
  <li><a href="#tukeys-hsd" id="toc-tukeys-hsd" class="nav-link" data-scroll-target="#tukeys-hsd"><span class="header-section-number">5.2</span> Tukey’s HSD</a></li>
  </ul>
</li>
  <li>
<a href="#seminar-tasks" id="toc-seminar-tasks" class="nav-link" data-scroll-target="#seminar-tasks"><span class="header-section-number">6</span> Seminar Tasks</a>
  <ul class="collapse">
<li><a href="#task-1-choice-of-tests" id="toc-task-1-choice-of-tests" class="nav-link" data-scroll-target="#task-1-choice-of-tests"><span class="header-section-number">6.1</span> Task 1 Choice of tests</a></li>
  <li><a href="#task-2-normality-checking" id="toc-task-2-normality-checking" class="nav-link" data-scroll-target="#task-2-normality-checking"><span class="header-section-number">6.2</span> Task 2 Normality Checking</a></li>
  <li><a href="#task-3-variance-checking" id="toc-task-3-variance-checking" class="nav-link" data-scroll-target="#task-3-variance-checking"><span class="header-section-number">6.3</span> Task 3 Variance checking</a></li>
  <li><a href="#task-4-performing-t-tests" id="toc-task-4-performing-t-tests" class="nav-link" data-scroll-target="#task-4-performing-t-tests"><span class="header-section-number">6.4</span> Task 4 Performing t-tests</a></li>
  <li><a href="#task-5-multiple-t-tests-with-anova" id="toc-task-5-multiple-t-tests-with-anova" class="nav-link" data-scroll-target="#task-5-multiple-t-tests-with-anova"><span class="header-section-number">6.5</span> Task 5 Multiple t-tests with anova</a></li>
  </ul>
</li>
  <li>
<a href="#extension-and-additional-reading" id="toc-extension-and-additional-reading" class="nav-link" data-scroll-target="#extension-and-additional-reading"><span class="header-section-number">7</span> Extension and additional reading</a>
  <ul class="collapse">
<li><a href="#recreating-a-paper-in-r" id="toc-recreating-a-paper-in-r" class="nav-link" data-scroll-target="#recreating-a-paper-in-r"><span class="header-section-number">7.1</span> Recreating a paper in R</a></li>
  </ul>
</li>
  <li><a href="#doing-t-tests-in-r" id="toc-doing-t-tests-in-r" class="nav-link" data-scroll-target="#doing-t-tests-in-r"><span class="header-section-number">8</span> Doing t-tests in R</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">06 T-tests</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><section id="pre-reading-and-pre-session-tasks" class="level1" data-number="1"><h1 data-number="1">
<span class="header-section-number">1</span> Pre-reading and pre-session tasks</h1>
<section id="pre-reading" class="level2" data-number="1.1"><h2 data-number="1.1" class="anchored" data-anchor-id="pre-reading">
<span class="header-section-number">1.1</span> Pre-reading</h2>
</section><section id="pre-session-task" class="level2" data-number="1.2"><h2 data-number="1.2" class="anchored" data-anchor-id="pre-session-task">
<span class="header-section-number">1.2</span> Pre-session task</h2>
</section></section><section id="t-tests" class="level1" data-number="2"><h1 data-number="2">
<span class="header-section-number">2</span> T-tests</h1>
<p>T-tests are statistical tests that determine if there are statistically significant differences between the means of two groups. Consider the data giving the results of girls and boys on a test:</p>
<p><strong>Boys’ scores</strong></p>
<table class="table">
<thead><tr class="header">
<th>Boy</th>
<th>Score (/10)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>7</td>
</tr>
<tr class="even">
<td>B</td>
<td>8</td>
</tr>
<tr class="odd">
<td>C</td>
<td>6</td>
</tr>
<tr class="even">
<td>D</td>
<td>5</td>
</tr>
<tr class="odd">
<td>E</td>
<td>8</td>
</tr>
<tr class="even">
<td>Mean</td>
<td>6.8</td>
</tr>
</tbody>
</table>
<p><strong>Girls’ scores</strong></p>
<table class="table">
<thead><tr class="header">
<th>Girls</th>
<th>Score (/10)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>9</td>
</tr>
<tr class="even">
<td>B</td>
<td>4</td>
</tr>
<tr class="odd">
<td>C</td>
<td>7</td>
</tr>
<tr class="even">
<td>D</td>
<td>8</td>
</tr>
<tr class="odd">
<td>E</td>
<td>8</td>
</tr>
<tr class="even">
<td>Mean</td>
<td>7.2</td>
</tr>
</tbody>
</table>
<p>The means of the two groups are different (6.8 for boys and 7.2 for girls) but the difference may simply be due to random variation. A t-test can report the probability that a difference is means is due to chance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2"></a>Boys <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Score=</span><span class="fu">c</span>(<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">6</span>,<span class="dv">5</span>,<span class="dv">8</span>))</span>
<span id="cb1-3"><a href="#cb1-3"></a>Girls <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Score=</span><span class="fu">c</span>(<span class="dv">9</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">8</span>))</span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="fu">print</span>(<span class="fu">mean</span>(Boys<span class="sc">$</span>Score))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="fu">print</span>(<span class="fu">mean</span>(Girls<span class="sc">$</span>Score))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="fu">t.test</span>(Boys<span class="sc">$</span>Score, Girls<span class="sc">$</span>Score)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Boys$Score and Girls$Score
t = -0.3849, df = 7.035, p-value = 0.7117
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -2.854915  2.054915
sample estimates:
mean of x mean of y 
      6.8       7.2 </code></pre>
</div>
</div>
<p>The <code>t.test</code> function returns a p-value greater than <code>0.05</code> so the mean test-results can be assumed to the result of chance, and we conclude there are no detectable differences by gender for this data set.</p>
<p>To take another example consider the random distribution of 10,000 boys and 10,000 girls scores on a mathematics tests below - the means are represented by dotted lines:</p>
<div class="cell">
<details><summary>show the code</summary><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="co"># Create random data sets of 10,000 boys' and girls' scores</span></span>
<span id="cb7-2"><a href="#cb7-2"></a>girlscores <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">rnorm</span>(<span class="at">n=</span><span class="dv">10000</span>, <span class="at">mean=</span><span class="dv">100</span>, <span class="at">sd=</span><span class="dv">10</span>))</span>
<span id="cb7-3"><a href="#cb7-3"></a>girlscores <span class="ot">&lt;-</span> girlscores <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="#cb7-4"></a>  <span class="fu">mutate</span>(<span class="at">gender=</span><span class="st">"female"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-5"><a href="#cb7-5"></a>  <span class="fu">rename</span>(<span class="at">Scores=</span><span class="st">"rnorm(n = 10000, mean = 100, sd = 10)"</span>)</span>
<span id="cb7-6"><a href="#cb7-6"></a>boysscores <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">rnorm</span>(<span class="at">n=</span><span class="dv">10000</span>, <span class="at">mean=</span><span class="dv">105</span>, <span class="at">sd=</span><span class="dv">10</span>))</span>
<span id="cb7-7"><a href="#cb7-7"></a>boysscores <span class="ot">&lt;-</span> boysscores <span class="sc">%&gt;%</span></span>
<span id="cb7-8"><a href="#cb7-8"></a>  <span class="fu">mutate</span>(<span class="at">gender=</span><span class="st">"male"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-9"><a href="#cb7-9"></a>  <span class="fu">rename</span>(<span class="at">Scores=</span><span class="st">"rnorm(n = 10000, mean = 105, sd = 10)"</span>)</span>
<span id="cb7-10"><a href="#cb7-10"></a></span>
<span id="cb7-11"><a href="#cb7-11"></a><span class="co"># Plot the data</span></span>
<span id="cb7-12"><a href="#cb7-12"></a>totalscores<span class="ot">&lt;-</span><span class="fu">rbind</span>(boysscores, girlscores)</span>
<span id="cb7-13"><a href="#cb7-13"></a><span class="fu">ggplot</span>(totalscores) <span class="sc">+</span></span>
<span id="cb7-14"><a href="#cb7-14"></a>  <span class="fu">geom_histogram</span>(<span class="at">data=</span>boysscores,</span>
<span id="cb7-15"><a href="#cb7-15"></a>                 <span class="fu">aes</span>(<span class="at">x=</span>Scores, <span class="at">fill=</span>gender, <span class="at">alpha=</span><span class="fl">0.5</span>), <span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb7-16"><a href="#cb7-16"></a>  <span class="fu">geom_histogram</span>(<span class="at">data=</span>girlscores,</span>
<span id="cb7-17"><a href="#cb7-17"></a>                 <span class="fu">aes</span>(<span class="at">x=</span>Scores, <span class="at">fill=</span>gender, <span class="at">alpha=</span><span class="fl">0.5</span>), <span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb7-18"><a href="#cb7-18"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="fu">mean</span>(boysscores<span class="sc">$</span>Scores), <span class="at">colour=</span><span class="st">"turquoise4"</span>, </span>
<span id="cb7-19"><a href="#cb7-19"></a>             <span class="at">linetype=</span><span class="dv">3</span>)<span class="sc">+</span> <span class="co"># Add a vertical line for the mean scores</span></span>
<span id="cb7-20"><a href="#cb7-20"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="fu">mean</span>(girlscores<span class="sc">$</span>Scores), <span class="at">colour=</span><span class="st">"red2"</span>, <span class="at">linetype=</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb7-21"><a href="#cb7-21"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">mean</span>(boysscores<span class="sc">$</span>Scores), <span class="at">y=</span><span class="dv">440</span>, <span class="co"># Add an arrow between means</span></span>
<span id="cb7-22"><a href="#cb7-22"></a>                   <span class="at">xend=</span><span class="fu">mean</span>(girlscores<span class="sc">$</span>Scores),</span>
<span id="cb7-23"><a href="#cb7-23"></a>                   <span class="at">yend=</span><span class="dv">440</span>), <span class="at">arrow =</span> <span class="fu">arrow</span>(<span class="at">length =</span> <span class="fu">unit</span>(<span class="fl">0.01</span>, <span class="st">"npc"</span>), </span>
<span id="cb7-24"><a href="#cb7-24"></a>                                              <span class="at">ends =</span> <span class="st">"both"</span>)) <span class="sc">+</span></span>
<span id="cb7-25"><a href="#cb7-25"></a>  <span class="fu">geom_text</span>(<span class="at">x=</span><span class="dv">125</span>, <span class="at">y=</span><span class="dv">440</span>, <span class="at">label=</span><span class="st">"Difference in means"</span>) <span class="sc">+</span> <span class="co"># Add text label</span></span>
<span id="cb7-26"><a href="#cb7-26"></a>  <span class="fu">xlab</span>(<span class="st">"score"</span>) <span class="sc">+</span></span>
<span id="cb7-27"><a href="#cb7-27"></a>  <span class="fu">ylab</span>(<span class="st">"Numer of students"</span>) <span class="sc">+</span></span>
<span id="cb7-28"><a href="#cb7-28"></a>  <span class="fu">guides</span>(<span class="at">alpha=</span><span class="st">"none"</span>) <span class="co"># Remove alpha from the legend</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="07-T-testsPISA_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Visually, it looks like there might be a difference in means (but we can’t be sure at this point). We can calculate the means.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="fu">mean</span>(girlscores<span class="sc">$</span>Scores)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 99.89479</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="fu">mean</span>(boysscores<span class="sc">$</span>Scores)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 105.075</code></pre>
</div>
</div>
<p>The means are different but, by inspection, it is not possible to tell if the difference in means is statistically significant. To find that out we need to perform a t-test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">t.test</span>(girlscores<span class="sc">$</span>Scores,boysscores<span class="sc">$</span>Scores)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  girlscores$Scores and boysscores$Scores
t = -36.65, df = 19992, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -5.457268 -4.903177
sample estimates:
mean of x mean of y 
 99.89479 105.07501 </code></pre>
</div>
</div>
<p>The test returns a p-value which we can use to make a conclusion. A p-value reports, assuming that there is no difference in the means of the two groups, what is the probability of getting a difference in means at least as big as the one we observe. Conventionally, we use 0.05 (1 in 20) as the cut off for statistical significance (a convention that has been much critiqued e.g. <span class="citation" data-cites="cohen1994earth baker2016statisticians">(<a href="#ref-cohen1994earth" role="doc-biblioref">Cohen 1994</a>; <a href="#ref-baker2016statisticians" role="doc-biblioref">Baker 2016</a>)</span>).</p>
<p>In the case above, the p-value of the t-test is less than 0.05 (p-value &lt; 2.2e-16) so we can assume that the means of the boys and girls scores are different to a statistically significant degree.</p>
<section id="types-of-t-test" class="level2" data-number="2.1"><h2 data-number="2.1" class="anchored" data-anchor-id="types-of-t-test">
<span class="header-section-number">2.1</span> Types of t-test</h2>
<p>There are a number of types of t-tests:</p>
<ul>
<li>One-tailed test - checks if the mean of one group is different in one direction (e.g.&nbsp;are one set of scores only higher than the other).</li>
<li>Two-tailed tests - checks if the means are different in two directions - (i.e.&nbsp;are tests scores of one group higher or lower than the other).</li>
<li>Paired tests - compares the means of measurements from the same individual or object (e.g.&nbsp;in a pre- and post-test - the comparison of means and before and after scores compares the same student’s scores in the first test with the second).</li>
<li>Unpaired t-tests - compares the means of two unrelated groups (for example, are the mean science scores of boys and girls in a school different).</li>
</ul>
<p>For more information on t-tests, see <a href="https://learningstatisticswithr.com/book/ttest.html">chapter 13</a>, in Navaro’s Learning Statistics with R.</p>
</section><section id="assumptions-of-t-tests" class="level2" data-number="2.2"><h2 data-number="2.2" class="anchored" data-anchor-id="assumptions-of-t-tests">
<span class="header-section-number">2.2</span> Assumptions of t-tests</h2>
<p>There are four assumptions that need to be met by data set for a t-test to be applicable: a) the data are continuous; b) the sample was randomly sampled; c) The variance of the data in each group is similar (homogeneity of variance); d) The data are approximately normally distributed.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>A rule of thumb researchers use is that if the ratio of variances of the larger sample to the smaller is less than 4, then a t-test can be used.</p>
</div>
</div>
</section><section id="normality-checking" class="level2" data-number="2.3"><h2 data-number="2.3" class="anchored" data-anchor-id="normality-checking">
<span class="header-section-number">2.3</span> Normality checking</h2>
<p>To check for normality we can use a number of different tests and approaches. For data sets that include more than 5000 observations (as is often the case with those sampled from the PISA data) then qqplots the Kolmogorov-Smirnov test are good approaches. Histograms can also be used to help visualise the data and compare with the normal distribution. We can use these different approaches to answer the question:</p>
<p>Are the PISA reading scores in the UK normally distributed?</p>
<p>Quantiles are sections of data, for example a type of quantile is a quartile, a section of data containing a quarter of the data points, a quintile contains 20% of the data and so on. A quintile-quantile plot, plots the quantiles of two distributions against each other. If the distributions are the same, a straight line is formed. Below, we produce a quintile-quantile plot (or qq-plot) for reading scores in the UK.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="co"># Create a UK reading subset</span></span>
<span id="cb14-2"><a href="#cb14-2"></a>PISAUKRead <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3"></a>  <span class="fu">select</span>(CNT, PV1READ) <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span>)</span>
<span id="cb14-5"><a href="#cb14-5"></a><span class="co"># Perform a qqplot</span></span>
<span id="cb14-6"><a href="#cb14-6"></a><span class="fu">qqnorm</span>(PISAUKRead<span class="sc">$</span>PV1READ)</span>
<span id="cb14-7"><a href="#cb14-7"></a><span class="co"># If data are normally distributed, a qq plot should be a straight line.</span></span>
<span id="cb14-8"><a href="#cb14-8"></a><span class="co"># To assist judgement, you can add a straight line with:</span></span>
<span id="cb14-9"><a href="#cb14-9"></a><span class="fu">qqline</span>(PISAUKRead<span class="sc">$</span>PV1READ, <span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-T-testsPISA_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="co"># The data in this case look normal.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The qqplot gives a good straight line so we can conclude that the data are normally distributed.</p>
<p>A non-graphical approach to normality testing is the Kolmogorov-Smirnov Test test. The package <code>dgof</code> contains <code>ks.test</code> which tests for normality. The test is carried out by passing the data to <code>ks.test(PISA_2018$PV1READ, "pnorm", mean=mean(PISA_2018$PV1READ), sd=sd(PISA_2018$PV1READ))</code>. <code>"pnorm"</code> sets the test to testing for normality (<code>ks.test</code> can test for different distributions). We also pass the function the mean (<code>mean</code>) and standard deviation (<code>sd</code>) of our data set. If the p-value is above 0.05, the data are normally distributed (or parametric).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="co"># the Kolmogorov-Smirnov Test</span></span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="fu">library</span>(dgof)</span>
<span id="cb16-3"><a href="#cb16-3"></a><span class="co"># Create a UK reading subset</span></span>
<span id="cb16-4"><a href="#cb16-4"></a>PISAUKRead<span class="ot">&lt;-</span>PISA_2018<span class="sc">%&gt;%</span></span>
<span id="cb16-5"><a href="#cb16-5"></a>  <span class="fu">select</span>(CNT, PV1READ)<span class="sc">%&gt;%</span></span>
<span id="cb16-6"><a href="#cb16-6"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span>)</span>
<span id="cb16-7"><a href="#cb16-7"></a><span class="fu">ks.test</span>(PISAUKRead<span class="sc">$</span>PV1READ, <span class="st">"pnorm"</span>, <span class="at">mean=</span><span class="fu">mean</span>(PISAUKRead<span class="sc">$</span>PV1READ), <span class="at">sd=</span><span class="fu">sd</span>(PISAUKRead<span class="sc">$</span>PV1READ))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One-sample Kolmogorov-Smirnov test

data:  PISAUKRead$PV1READ
D = 0.01386, p-value = 0.009895
alternative hypothesis: two-sided</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="co"># The p-value is less than 0.05, assume the data are not normally distributed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>The usefulness of normality tests is contested - for large samples, tests like the Kolmogorov-Smirnov test can return values below 0.05 (i.e.&nbsp;report that the data are not normal), for very small deviations from the normal <span class="citation" data-cites="hanna2013psychology">(<a href="#ref-hanna2013psychology" role="doc-biblioref">Hanna and Dempster 2013</a>)</span>. Normality tests may be a useful backup, for small samples, if the qqplot is hard to interpret but, with the large samples typical in the PISA data, may give contradictory outcomes to the two visual tests.</p>
</div>
</div>
<p>Finally, a third approach, which is harder to judge, is to plot a histogram and to examine it for the normal shape.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="co"># Create a UK reading subset</span></span>
<span id="cb19-2"><a href="#cb19-2"></a>PISAUKRead <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3"></a>  <span class="fu">select</span>(CNT, PV1READ) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span>)</span>
<span id="cb19-5"><a href="#cb19-5"></a><span class="co"># Plot a histogram</span></span>
<span id="cb19-6"><a href="#cb19-6"></a><span class="fu">ggplot</span>(<span class="at">data=</span>PISAUKRead,</span>
<span id="cb19-7"><a href="#cb19-7"></a>       <span class="fu">aes</span>(<span class="at">x=</span>PV1READ)) <span class="sc">+</span></span>
<span id="cb19-8"><a href="#cb19-8"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill=</span><span class="st">"darkseagreen4"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="07-T-testsPISA_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="co"># from the histrogram, the data look normally distributed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="checking-for-equal-variances" class="level2" data-number="2.4"><h2 data-number="2.4" class="anchored" data-anchor-id="checking-for-equal-variances">
<span class="header-section-number">2.4</span> Checking for Equal Variances</h2>
<p>The second assumption of a test is that the samples have equal variance. Variance describes the spread of the data (standard deviation is the square root of variance).</p>
<p>To check for equal variances, we can divide the variance of one sample by the other sample. A rule of thumb researchers use is that if the ratio of variances of the larger sample to the smaller is less than four, then a t-test can be used <span class="citation" data-cites="boneau1960effects">(<a href="#ref-boneau1960effects" role="doc-biblioref">Boneau 1960</a>)</span>. R will check this for you, and if they are unequal, will use the test for unequal variances (Welch’s test).</p>
<p>To check for the ratio of variance, we can use the <code>var</code> function, and calculate the ratio of the sample. We add <code>na.rm=TRUE</code> to the <code>var</code> function to omit NA values. For example, determine the ratio of girls’ and boys’ reading scores in the UK.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="co"># Create a UK reading subset for boys</span></span>
<span id="cb21-2"><a href="#cb21-2"></a>PISAUKReadM <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3"></a>  <span class="fu">select</span>(CNT, PV1READ,ST004D01T) <span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a href="#cb21-4"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span><span class="sc">|</span>ST004D01T<span class="sc">==</span><span class="st">"Male"</span>)</span>
<span id="cb21-5"><a href="#cb21-5"></a></span>
<span id="cb21-6"><a href="#cb21-6"></a><span class="co"># Create a UK reading subset for girls</span></span>
<span id="cb21-7"><a href="#cb21-7"></a>PISAUKReadF <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb21-8"><a href="#cb21-8"></a>  <span class="fu">select</span>(CNT, PV1READ,ST004D01T) <span class="sc">%&gt;%</span></span>
<span id="cb21-9"><a href="#cb21-9"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span><span class="sc">|</span>ST004D01T<span class="sc">==</span><span class="st">"Female"</span>)</span>
<span id="cb21-10"><a href="#cb21-10"></a><span class="co"># Find the variance</span></span>
<span id="cb21-11"><a href="#cb21-11"></a>MVar <span class="ot">&lt;-</span> <span class="fu">var</span>(PISAUKReadM<span class="sc">$</span>PV1READ, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb21-12"><a href="#cb21-12"></a>FVar <span class="ot">&lt;-</span> <span class="fu">var</span>(PISAUKReadF<span class="sc">$</span>PV1READ, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb21-13"><a href="#cb21-13"></a>MVar<span class="sc">/</span>FVar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.150343</code></pre>
</div>
</div>
<p>The ratio of variances is 1.15 so the samples meet the variance criterion for t-tests.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Checking and Filtering for Outliers</strong></p>
<p>Often, we need to check and filter for outliers in the data. There are many ways to do this, depending on the distribution of the data and how extreme the outliers are that we want to remove. A good rule of thumb is the median +/- 1.5 times the interquartile range (IQR), where the IQR is the upper quartile - lower quartile. If the data is normally distributed, then the mean +/- 1.5 time the standard deviation (sd) can be used. If we only want to remove more extreme outliers, then 2 or even 3 times the IQR (or sd) from the median (or mean) can be used instead.</p>
<p>Once we have determined the upper and lower bound of our outliers, we can remove any data points that lie outside of this and then perform our statistical test on the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="co"># Create a subset of UK math scores</span></span>
<span id="cb23-2"><a href="#cb23-2"></a>UKPISAmath <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3"></a>  <span class="fu">select</span>(CNT, PV1MATH) <span class="sc">%&gt;%</span></span>
<span id="cb23-4"><a href="#cb23-4"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span>)</span>
<span id="cb23-5"><a href="#cb23-5"></a></span>
<span id="cb23-6"><a href="#cb23-6"></a><span class="co"># Test for normality in current form</span></span>
<span id="cb23-7"><a href="#cb23-7"></a><span class="fu">ks.test</span>(UKPISAmath<span class="sc">$</span>PV1MATH, <span class="st">"pnorm"</span>, <span class="at">mean=</span><span class="fu">mean</span>(UKPISAmath<span class="sc">$</span>PV1MATH), <span class="at">sd=</span><span class="fu">sd</span>(UKPISAmath<span class="sc">$</span>PV1MATH))</span>
<span id="cb23-8"><a href="#cb23-8"></a></span>
<span id="cb23-9"><a href="#cb23-9"></a><span class="co"># p-value = 0.04783 - only just normal</span></span>
<span id="cb23-10"><a href="#cb23-10"></a><span class="co"># Calculate value of scores at 1.5 x sd above and below the mean</span></span>
<span id="cb23-11"><a href="#cb23-11"></a>outl_h_b<span class="ot">&lt;-</span><span class="fu">mean</span>(PISA_2018<span class="sc">$</span>PV1MATH, <span class="at">na.rm=</span><span class="cn">TRUE</span>) <span class="sc">+</span><span class="fl">1.5</span> <span class="sc">*</span> <span class="fu">sd</span>(PISA_2018<span class="sc">$</span>PV1MATH, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb23-12"><a href="#cb23-12"></a>outl_l_b<span class="ot">&lt;-</span><span class="fu">mean</span>(PISA_2018<span class="sc">$</span>PV1MATH, <span class="at">na.rm=</span><span class="cn">TRUE</span>) <span class="sc">-</span><span class="fl">1.5</span> <span class="sc">*</span> <span class="fu">sd</span>(PISA_2018<span class="sc">$</span>PV1MATH, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb23-13"><a href="#cb23-13"></a></span>
<span id="cb23-14"><a href="#cb23-14"></a><span class="co"># Filter values that are 1.5 x sd above and below the mean</span></span>
<span id="cb23-15"><a href="#cb23-15"></a>UKPISAmath <span class="ot">&lt;-</span> UKPISAmath <span class="sc">%&gt;%</span></span>
<span id="cb23-16"><a href="#cb23-16"></a> <span class="fu">filter</span>(PV1MATH <span class="sc">&gt;</span> outl_l_b <span class="sc">&amp;</span> PV1MATH <span class="sc">&lt;</span> outl_h_b)</span>
<span id="cb23-17"><a href="#cb23-17"></a></span>
<span id="cb23-18"><a href="#cb23-18"></a><span class="co"># Test for normality again</span></span>
<span id="cb23-19"><a href="#cb23-19"></a><span class="fu">ks.test</span>(UKPISAmath<span class="sc">$</span>PV1MATH, <span class="st">"pnorm"</span>, <span class="at">mean=</span><span class="fu">mean</span>(UKPISAmath<span class="sc">$</span>PV1MATH), <span class="at">sd=</span><span class="fu">sd</span>(UKPISAmath<span class="sc">$</span>PV1MATH))</span>
<span id="cb23-20"><a href="#cb23-20"></a><span class="co"># p-value now &lt; 2.2e-16 - a much more normal distribution</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section></section><section id="performing-t-tests" class="level1" data-number="3"><h1 data-number="3">
<span class="header-section-number">3</span> Performing t-tests</h1>
<p>To perform a t.test in R you use the <code>t.test</code> function. You need to pass the function the data set you want to test (<code>data=USMath</code>), and specify the groups to be compared (<code>PV1MATH ~ ST004D01T</code>) - here comparing the means of the mathematics scores (<code>PV1AMTH</code>) by the gender variable (<code>ST004D01T</code>). You can then specify if the test is two sided (<code>alternative = "two.sided"</code>), and the type of test (<code>paired = FALSE</code> - i.e.&nbsp;this is an unpaired test). For example, to determine if there are statistically significant differences in boys and girls maths scores in the United States:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="co"># Create a UK reading subset</span></span>
<span id="cb24-2"><a href="#cb24-2"></a>USMATH<span class="ot">&lt;-</span>PISA_2018<span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3"></a>  <span class="fu">select</span>(CNT, PV1MATH,ST004D01T)<span class="sc">%&gt;%</span></span>
<span id="cb24-4"><a href="#cb24-4"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United States"</span>)</span>
<span id="cb24-5"><a href="#cb24-5"></a><span class="co"># Plot a two-sided, unpaired t-test</span></span>
<span id="cb24-6"><a href="#cb24-6"></a><span class="fu">t.test</span>(PV1MATH <span class="sc">~</span> ST004D01T, <span class="at">data =</span> USMATH, </span>
<span id="cb24-7"><a href="#cb24-7"></a>       <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  PV1MATH by ST004D01T
t = -2.6529, df = 4832.8, p-value = 0.008006
alternative hypothesis: true difference in means between group Female and group Male is not equal to 0
95 percent confidence interval:
 -12.145264  -1.823039
sample estimates:
mean in group Female   mean in group Male 
            469.5886             476.5727 </code></pre>
</div>
</div>
<p>::: call-out note <strong><em>Types of t-test</em></strong> To set whether the t.test in R is one-tailed or two-tailed you can set the function <code>alternative</code> in <code>t.test</code> to “greater”, “less” or “two.sided”. To set the test as paired or unpaired, you can set the <code>paired</code> variable to TRUE or FALSE.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="co"># Create a UK reading subset</span></span>
<span id="cb26-2"><a href="#cb26-2"></a>UKSci<span class="ot">&lt;-</span>PISA_2018<span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3"></a>  <span class="fu">select</span>(CNT, PV1SCIE,ST004D01T)<span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span>)</span>
<span id="cb26-5"><a href="#cb26-5"></a><span class="co"># Plot a two-sided, unpaired t-test</span></span>
<span id="cb26-6"><a href="#cb26-6"></a><span class="fu">t.test</span>(PV1SCIE <span class="sc">~</span> ST004D01T, <span class="at">data =</span> UKSci, </span>
<span id="cb26-7"><a href="#cb26-7"></a>       <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  PV1SCIE by ST004D01T
t = 1.5274, df = 13662, p-value = 0.1267
alternative hypothesis: true difference in means between group Female and group Male is not equal to 0
95 percent confidence interval:
 -0.6983756  5.6282103
sample estimates:
mean in group Female   mean in group Male 
            496.4626             493.9977 </code></pre>
</div>
</div>
<p>:::</p>
</section><section id="interpreting-the-output-of-t-tests" class="level1" data-number="4"><h1 data-number="4">
<span class="header-section-number">4</span> Interpreting the output of t-tests</h1>
<p>To interpret the outcome of the test, the key value is the p-value (in this case, p-value = 0.008006). As the p-value is &lt;0.05 we can conclude that there are significant differences between boys’ and girls’ mean mathematics scores in the US.</p>
</section><section id="anova-multiple-t-tests" class="level1" data-number="5"><h1 data-number="5">
<span class="header-section-number">5</span> Anova (multiple t-tests)</h1>
<p>We have performed t-tests of the difference in mathematics scores between boys and girls in the UK. We may now want to perform the same t-test for all the countries in the sample. This can create a problem. Remember that a p-value report the probability that an outcome is due to chance. The more times we repeat a t-test, the more likely we are to see an effect, even when none-exists.</p>
<p>To avoid potential artefacts from doing multiple t-tests, when we want to compate the means of more than two groups, we use an anova (anlaysis of variance) test.</p>
<p>To determine if there is a statistically significant difference between groups we run an anova calculation, using the <code>aov</code> function in R. The dependent variable is the one we are interested in explaining, the independent variables are the factors we think might explain the variance.</p>
<p><code>aov(data, dependent_var ~ independent_var + independent_var + ...)</code></p>
<p>For example, we used t-tests to look at differences in scores between a pair of countries (e.g the UK and the US). We can now compare across all the countires.</p>
<p>We pass the function the data we wish to focus on (<code>PV1MATH</code>) and then indicate we wish to look for variation in the <code>PV1MATH</code>, by <code>CNT</code>. We then summarise the result to get a table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a>ALLPISAMATH<span class="ot">&lt;-</span>PISA_2018<span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2"></a>  <span class="fu">select</span>(CNT, PV1MATH)</span>
<span id="cb28-3"><a href="#cb28-3"></a></span>
<span id="cb28-4"><a href="#cb28-4"></a>resaov <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">data=</span>ALLPISAMATH, PV1MATH <span class="sc">~</span> CNT)</span>
<span id="cb28-5"><a href="#cb28-5"></a>sumresaov <span class="ot">&lt;-</span> <span class="fu">summary</span>(resaov)</span>
<span id="cb28-6"><a href="#cb28-6"></a>sumresaov</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Df    Sum Sq  Mean Sq F value Pr(&gt;F)    
CNT             78 1.737e+09 22271292    2774 &lt;2e-16 ***
Residuals   606548 4.870e+09     8028                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
5377 observations deleted due to missingness</code></pre>
</div>
</div>
<p>The resulting table has two rows: <code>CNT</code> residuals. The <code>aov</code> function looks to determine if there is a difference in the variance across countires. After determining any variation from those two variables, any remaining variation is associated with residuals - you can think of this as the unexplained variation that isn’t associated with the vectors we specified (i.e.&nbsp;the country).</p>
<p>First, look at the <code>Pr(&gt;F)</code> column. This is a test of significance and reports if the groups in that row show statistically significant variation. In our case, country returns <code>Pr(&gt;F) &lt;2e-16 ***</code> - which is over <code>0.05</code>. This suggests there are significant differences across countries.</p>
<p>This is not terribly interesting so far(!) - but we can do two post-hoc tests (i.e.&nbsp;tests after the first test, to find out the effect size and between which countries differences exist)</p>
<section id="eta-squared" class="level2" data-number="5.1"><h2 data-number="5.1" class="anchored" data-anchor-id="eta-squared">
<span class="header-section-number">5.1</span> Eta-squared</h2>
<p>Now knowing that there are significant differences between the two class groups, we can next determine how much variation in the test score is explained by class. To do this we calculate a variable called eta-squared.</p>
<p>Eta-squared gives the proportion of variance explained by each variable. The eta squared function is in the package <code>lsr</code> so we will install <code>lsr</code>, and then use the result of our anova (<code>resaov</code>) to calculate the eta squared variable using the function <code>etaSquared</code>. To report the value of eta as a percentage we need to multiply the output of eta by 100.</p>
<p>Eta squared tells us the proportion of the total variance that is explained by a variable (you can also think of it as an effect size). An eta squared value of 1 indicates all the variance of a sample is explain by some variable and 0 means the variable is not responsible for any of the observed variance. We can multiply the eta-squared score by 100 to get a value for the percentage of variance explained.</p>
<p>The percentage of variance explained is a useful figure. For example, it has been reported that schools only account for 14% of the variance in progress 8 scores, whilst family explains 43% (<span class="citation" data-cites="wilkinson2018assessing">Wilkinson, Bryson, and Stokes (<a href="#ref-wilkinson2018assessing" role="doc-biblioref">2018</a>)</span>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="fu">library</span>(lsr)</span>
<span id="cb30-2"><a href="#cb30-2"></a>eta <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">etaSquared</span>(resaov))</span>
<span id="cb30-3"><a href="#cb30-3"></a>eta <span class="ot">&lt;-</span> eta<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb30-4"><a href="#cb30-4"></a>eta</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      eta.sq eta.sq.part
CNT 26.29404    26.29404</code></pre>
</div>
</div>
<p>The important column here is the <code>eta.sq</code> column - it tells us that the country explains 26% of the variance in test scores. (The second column contains information about partial eta-squared, which we won’t go into, but are used when the results of each measure are <em>not independent</em> i.e. one result influences another).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>As a rule of thumb, a percentage variance explained of 1% is considered small, 6% medium and 14% and more large</p>
</div>
</div>
</section><section id="tukeys-hsd" class="level2" data-number="5.2"><h2 data-number="5.2" class="anchored" data-anchor-id="tukeys-hsd">
<span class="header-section-number">5.2</span> Tukey’s HSD</h2>
<p>When an anova test reports that are some statistically significant differences between groups, it does not imply there are statistically significant differences between all subgroups. For example, if the anova reports statistically significant differences by age, statistically significant differences might exist between 11, 12 and 13-year old students, but not between 13 and 14-year olds.</p>
<p>We can use an additional anova test, <strong>Tukey’s Honest Significant Difference</strong> test (or Tukey’s HSD for short), to find out which pairs of subgroups have statistically significant differences in means.</p>
<p>Consider the question: Are there statistically significant differences in the variance of science scores of the UK, US, France and Germany? To determine if such differences exist, we create a new subset for those countries’ science scores, and then run an anova test by country, reporting the eta squared value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a>PISAMULTI <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2"></a>  <span class="fu">select</span>(CNT, PV1SCIE)<span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span> <span class="sc">|</span> CNT<span class="sc">==</span><span class="st">"United States"</span> <span class="sc">|</span> CNT<span class="sc">==</span><span class="st">"Germany"</span> <span class="sc">|</span> CNT<span class="sc">==</span><span class="st">"France"</span>)</span>
<span id="cb32-4"><a href="#cb32-4"></a>  <span class="co"># filter(CNT %in% c("United Kingdom", "United States", "Germany", "France"))</span></span>
<span id="cb32-5"><a href="#cb32-5"></a></span>
<span id="cb32-6"><a href="#cb32-6"></a>resaov<span class="ot">&lt;-</span><span class="fu">aov</span>(PV1SCIE <span class="sc">~</span> CNT, <span class="at">data=</span>PISAMULTI)</span>
<span id="cb32-7"><a href="#cb32-7"></a>sumresaov<span class="ot">&lt;-</span><span class="fu">summary</span>(resaov)</span>
<span id="cb32-8"><a href="#cb32-8"></a>sumresaov</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Df    Sum Sq Mean Sq F value Pr(&gt;F)    
CNT             3   1071227  357076   37.36 &lt;2e-16 ***
Residuals   30411 290638789    9557                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a>eta<span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(<span class="fu">etaSquared</span>(resaov))</span>
<span id="cb34-2"><a href="#cb34-2"></a>eta<span class="ot">&lt;-</span>eta<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb34-3"><a href="#cb34-3"></a>eta</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       eta.sq eta.sq.part
CNT 0.3672231   0.3672231</code></pre>
</div>
</div>
<p>The anova results tell us there are significant differences between the countries, which account for 0.4% of variance in scores. We can then run a Tukey HSD test to determine which countries have significant differences between mean scores.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a><span class="fu">TukeyHSD</span>(resaov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = PV1SCIE ~ CNT, data = PISAMULTI)

$CNT
                                   diff        lwr        upr     p adj
France-Germany               -18.844787 -23.489214 -14.200359 0.0000000
United Kingdom-Germany        -9.056104 -13.073086  -5.039123 0.0000000
United States-Germany         -7.024614 -11.985354  -2.063874 0.0015665
 [ reached getOption("max.print") -- omitted 3 rows ]</code></pre>
</div>
</div>
<p>From that we get a table with p values (p adj) for different pairs of countries. Note that these are below 0.005 for all pairs of countries, except the US and the UK. So we can conclude there are significant differences in science scores between all countries except the UK and the US.</p>
</section></section><section id="seminar-tasks" class="level1" data-number="6"><h1 data-number="6">
<span class="header-section-number">6</span> Seminar Tasks</h1>
<section id="task-1-choice-of-tests" class="level2" data-number="6.1"><h2 data-number="6.1" class="anchored" data-anchor-id="task-1-choice-of-tests">
<span class="header-section-number">6.1</span> Task 1 Choice of tests</h2>
<p>Consider the following scenarios. Which (if any) of the t-tests would be most of appropriate, including whether it would be a one or two tailed test.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>One and two-tailed tests</p>
<p>Remember that a one-tailed test only looks for differences in one direction from the mean (for example, that one sample has a higher mean than the other). A two-tailed tests tests for the possibility of the means of the two groups being higher or lower than each other.</p>
</div>
</div>
<div class="question">
<ol type="a">
<li><p>An educational researcher wants to test a teaching approach with a group of 12 students to see if an intervention increases performance in their year 6 SATs results. Pupils are given a SATS paper before the intervention and again after. The results of these are normalised and then compared.</p></li>
<li><p>A teacher wants to see if their pupils’ GCSE computer science test scores are in line with the national average or not. The tests are out of 180 marks.</p></li>
<li><p>The DfE want to compare uptake of STEM subjects pre and post pandemic to see if there has been any change in the percentage of students studying at least one STEM subject for A level.</p></li>
<li><p>A school wants to compare salaries of staff between this academic year and last academic year to see whether there has been a significant increase.</p></li>
<li><p>The same school as in d) wants to compare salaries of support staff and teaching staff to see if there is a significant difference.</p></li>
<li><p>A researcher wants to find out how much time pupils spend looking at screens during lesson time, to see if there is a difference between year 7 and year 10 students. 10 pupils in year 7 and 10 pupils in year 10 are randomly selected across a school and observed throughout a school day in November. The times are recorded to the nearest minute.</p></li>
<li><p>A business manager wants to check if the financial expenditure on STEM teachers per year is similar to the national average (based on average numbers of pupils on role)</p></li>
</ol>
</div>
<div class="cell">
<details><summary>Answer</summary><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a><span class="co"># Answers</span></span>
<span id="cb38-2"><a href="#cb38-2"></a></span>
<span id="cb38-3"><a href="#cb38-3"></a><span class="co"># a)  An educational researcher wants to test a teaching approach with a group of 12 students to see if an intervention increases performance in their year 6 SATs results. Pupils are given a SATS paper before the intervention and again after. The results of these are normalised and then compared.</span></span>
<span id="cb38-4"><a href="#cb38-4"></a></span>
<span id="cb38-5"><a href="#cb38-5"></a><span class="co"># Paired (because we compare pairs of results (before and after) for the same student) and two-tailed (because we are interested in the means being higher or lower)</span></span>
<span id="cb38-6"><a href="#cb38-6"></a></span>
<span id="cb38-7"><a href="#cb38-7"></a><span class="co"># b)  A teacher wants to see if their pupils' GCSE computer science test scores are in line with the national average or not. The tests are out of 180 marks.</span></span>
<span id="cb38-8"><a href="#cb38-8"></a></span>
<span id="cb38-9"><a href="#cb38-9"></a><span class="co"># Unpaired (the teacher compares their students with another pool) and two-tailed (because we are interested in the means being higher or lower)</span></span>
<span id="cb38-10"><a href="#cb38-10"></a></span>
<span id="cb38-11"><a href="#cb38-11"></a><span class="co"># c)  The DfE want to compare uptake of STEM subjects pre and post pandemic to see if there has been any change in the percentage of students studying at least one STEM subject for A level.</span></span>
<span id="cb38-12"><a href="#cb38-12"></a></span>
<span id="cb38-13"><a href="#cb38-13"></a><span class="co"># Unpaired (the students taking STEM subjects before and after the pandemic will be different individuals from different cohorts) and two-tailed (because we are interested in the means being higher or lower)</span></span>
<span id="cb38-14"><a href="#cb38-14"></a></span>
<span id="cb38-15"><a href="#cb38-15"></a><span class="co"># d)  A school wants to compare salaries of staff between this academic year and last academic year to see whether there has been a significant increase.</span></span>
<span id="cb38-16"><a href="#cb38-16"></a></span>
<span id="cb38-17"><a href="#cb38-17"></a><span class="co"># Possibly paired (if the staff body has remained the same), and two-tailed (because we are interested in the means being higher or lower)</span></span>
<span id="cb38-18"><a href="#cb38-18"></a></span>
<span id="cb38-19"><a href="#cb38-19"></a><span class="co"># e)  The same school as in d) wants to compare salaries of support staff and teaching staff to see if there is a significant difference.</span></span>
<span id="cb38-20"><a href="#cb38-20"></a></span>
<span id="cb38-21"><a href="#cb38-21"></a><span class="co"># Unpaired (because there are two different groups, teachers and support staff), and two-tailed (because we are interested in the mean salaries being higher or lower)</span></span>
<span id="cb38-22"><a href="#cb38-22"></a></span>
<span id="cb38-23"><a href="#cb38-23"></a><span class="co"># f)  A researcher wants to find out how much time pupils spend looking at screens during lesson time, to see if there is a difference between year 7 and year 10 students. 10 pupils in year 7 and 10 pupils in year 10 are randomly selected across a school and observed  throughout a school day in November. The times are recorded to the nearest minute.</span></span>
<span id="cb38-24"><a href="#cb38-24"></a></span>
<span id="cb38-25"><a href="#cb38-25"></a><span class="co"># Unpaired (because there are two different groups, Y7 and Y10), and two-tailed (because we are interested in the means of times being higher or lower)</span></span>
<span id="cb38-26"><a href="#cb38-26"></a></span>
<span id="cb38-27"><a href="#cb38-27"></a><span class="co"># g)  A business manager wants to check if the financial expenditure on STEM teachers per year is similar to the national average (based on average numbers of pupils on role)</span></span>
<span id="cb38-28"><a href="#cb38-28"></a></span>
<span id="cb38-29"><a href="#cb38-29"></a><span class="co"># Unpaired (because there are two different groups, the school and the national cohort), and two-tailed (because we are interested in the expenditure means being higher or lower)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section><section id="task-2-normality-checking" class="level2" data-number="6.2"><h2 data-number="6.2" class="anchored" data-anchor-id="task-2-normality-checking">
<span class="header-section-number">6.2</span> Task 2 Normality Checking</h2>
<div class="question">
<p>Determine if the following subsets of PISA data are normal (you will need to use <code>select</code> and <code>filter</code>). Try to use all three methods of normality checking (a) qqplots, b) the Kolmogorov-Smirnov test, c) histogram plotting, to reach your conclusion</p>
<p>Are the following data normally distributed: a) PV1MATH scores in the UK; b) PV1MATH scores in Malta; c) Students in the UK who score more than 750 on their science test.</p>
<div class="cell">
<details><summary>Answer</summary><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="co"># a) PV1MATH scores in the UK</span></span>
<span id="cb39-2"><a href="#cb39-2"></a><span class="co"># Create UK Math subset</span></span>
<span id="cb39-3"><a href="#cb39-3"></a>UKMath<span class="ot">&lt;-</span>PISA_2018<span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4"></a>  <span class="fu">select</span>(CNT, PV1MATH)<span class="sc">%&gt;%</span></span>
<span id="cb39-5"><a href="#cb39-5"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span>)</span>
<span id="cb39-6"><a href="#cb39-6"></a>  <span class="co"># Perform a qqplot</span></span>
<span id="cb39-7"><a href="#cb39-7"></a><span class="fu">qqnorm</span>(UKMath<span class="sc">$</span>PV1MATH)</span>
<span id="cb39-8"><a href="#cb39-8"></a><span class="co"># If data are normally distributed, a qq plot should be a straight line.</span></span>
<span id="cb39-9"><a href="#cb39-9"></a><span class="co"># To assist judgement, you can add a straight line with:</span></span>
<span id="cb39-10"><a href="#cb39-10"></a><span class="fu">qqline</span>(UKMath<span class="sc">$</span>PV1MATH, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb39-11"><a href="#cb39-11"></a><span class="co"># The data in this case look normal.</span></span>
<span id="cb39-12"><a href="#cb39-12"></a></span>
<span id="cb39-13"><a href="#cb39-13"></a><span class="co"># Perform the KS test</span></span>
<span id="cb39-14"><a href="#cb39-14"></a><span class="fu">ks.test</span>(UKMath<span class="sc">$</span>PV1MATH, <span class="st">"pnorm"</span>, <span class="at">mean=</span><span class="fu">mean</span>(UKMath<span class="sc">$</span>PV1MATH), <span class="at">sd=</span><span class="fu">sd</span>(UKMath<span class="sc">$</span>PV1MATH))</span>
<span id="cb39-15"><a href="#cb39-15"></a><span class="co"># The p-value is 0.04783, less than 0.05, implying the data are not normal, but recall the over sensitivity of the test.</span></span>
<span id="cb39-16"><a href="#cb39-16"></a></span>
<span id="cb39-17"><a href="#cb39-17"></a><span class="co"># Plot a histogram</span></span>
<span id="cb39-18"><a href="#cb39-18"></a><span class="fu">ggplot</span>(<span class="at">data=</span>UKMath,</span>
<span id="cb39-19"><a href="#cb39-19"></a>       <span class="fu">aes</span>(<span class="at">x=</span>PV1MATH))<span class="sc">+</span></span>
<span id="cb39-20"><a href="#cb39-20"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill=</span><span class="st">"darkseagreen4"</span>)</span>
<span id="cb39-21"><a href="#cb39-21"></a><span class="co"># The data in this case look normal.</span></span>
<span id="cb39-22"><a href="#cb39-22"></a></span>
<span id="cb39-23"><a href="#cb39-23"></a><span class="co"># b) PV1MATH scores in Malta</span></span>
<span id="cb39-24"><a href="#cb39-24"></a></span>
<span id="cb39-25"><a href="#cb39-25"></a><span class="co"># Create Malta Math subset</span></span>
<span id="cb39-26"><a href="#cb39-26"></a>MalMath<span class="ot">&lt;-</span>PISA_2018<span class="sc">%&gt;%</span></span>
<span id="cb39-27"><a href="#cb39-27"></a>  <span class="fu">select</span>(CNT, PV1MATH)<span class="sc">%&gt;%</span></span>
<span id="cb39-28"><a href="#cb39-28"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"Malta"</span>)</span>
<span id="cb39-29"><a href="#cb39-29"></a>  <span class="co"># Perform a qqplot</span></span>
<span id="cb39-30"><a href="#cb39-30"></a><span class="fu">qqnorm</span>(MalMath<span class="sc">$</span>PV1MATH)</span>
<span id="cb39-31"><a href="#cb39-31"></a><span class="co"># If data are normally distributed, a qq plot should be a straight line.</span></span>
<span id="cb39-32"><a href="#cb39-32"></a><span class="co"># To assist judgement, you can add a straight line with:</span></span>
<span id="cb39-33"><a href="#cb39-33"></a><span class="fu">qqline</span>(MalMath<span class="sc">$</span>PV1MATH, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb39-34"><a href="#cb39-34"></a><span class="co"># The data in this case look normal.</span></span>
<span id="cb39-35"><a href="#cb39-35"></a></span>
<span id="cb39-36"><a href="#cb39-36"></a><span class="co"># Perform the KS test</span></span>
<span id="cb39-37"><a href="#cb39-37"></a><span class="fu">ks.test</span>(MalMath<span class="sc">$</span>PV1MATH, <span class="st">"pnorm"</span>, <span class="at">mean=</span><span class="fu">mean</span>(MalMath<span class="sc">$</span>PV1MATH), <span class="at">sd=</span><span class="fu">sd</span>(MalMath<span class="sc">$</span>PV1MATH))</span>
<span id="cb39-38"><a href="#cb39-38"></a><span class="co"># The p-value, 0.03173, less than 0.05, implying the data are not normally distributed, but recall the over sensitivity of the test.</span></span>
<span id="cb39-39"><a href="#cb39-39"></a></span>
<span id="cb39-40"><a href="#cb39-40"></a><span class="co"># Plot a histogram</span></span>
<span id="cb39-41"><a href="#cb39-41"></a><span class="fu">ggplot</span>(<span class="at">data=</span>MalMath,</span>
<span id="cb39-42"><a href="#cb39-42"></a>       <span class="fu">aes</span>(<span class="at">x=</span>PV1MATH))<span class="sc">+</span></span>
<span id="cb39-43"><a href="#cb39-43"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill=</span><span class="st">"darkseagreen4"</span>)</span>
<span id="cb39-44"><a href="#cb39-44"></a><span class="co"># The data in this case look normal.</span></span>
<span id="cb39-45"><a href="#cb39-45"></a></span>
<span id="cb39-46"><a href="#cb39-46"></a><span class="co"># c) UK science high achievers</span></span>
<span id="cb39-47"><a href="#cb39-47"></a></span>
<span id="cb39-48"><a href="#cb39-48"></a><span class="co"># Create a UK over 750 Science score subset</span></span>
<span id="cb39-49"><a href="#cb39-49"></a>UKHighSci<span class="ot">&lt;-</span>PISA_2018<span class="sc">%&gt;%</span></span>
<span id="cb39-50"><a href="#cb39-50"></a>  <span class="fu">select</span>(CNT, PV1SCIE)<span class="sc">%&gt;%</span></span>
<span id="cb39-51"><a href="#cb39-51"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span> <span class="sc">&amp;</span> PV1SCIE<span class="sc">&gt;</span><span class="dv">750</span>)</span>
<span id="cb39-52"><a href="#cb39-52"></a>  <span class="co"># Perform a qqplot</span></span>
<span id="cb39-53"><a href="#cb39-53"></a><span class="fu">qqnorm</span>(UKHighSci<span class="sc">$</span>PV1SCIE)</span>
<span id="cb39-54"><a href="#cb39-54"></a><span class="co"># If data are normally distributed, a qq plot should be a straight line.</span></span>
<span id="cb39-55"><a href="#cb39-55"></a><span class="co"># To assist judgement, you can add a straight line with:</span></span>
<span id="cb39-56"><a href="#cb39-56"></a><span class="fu">qqline</span>(UKHighSci<span class="sc">$</span>PV1SCIE, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb39-57"><a href="#cb39-57"></a><span class="co"># I am not entirely convinced from the line!</span></span>
<span id="cb39-58"><a href="#cb39-58"></a></span>
<span id="cb39-59"><a href="#cb39-59"></a><span class="co"># Perform the KS test</span></span>
<span id="cb39-60"><a href="#cb39-60"></a><span class="fu">ks.test</span>(UKHighSci<span class="sc">$</span>PV1SCIE, <span class="st">"pnorm"</span>, <span class="at">mean=</span><span class="fu">mean</span>(UKHighSci<span class="sc">$</span>PV1SCIE), <span class="at">sd=</span><span class="fu">sd</span>(UKHighSci<span class="sc">$</span>PV1SCIE))</span>
<span id="cb39-61"><a href="#cb39-61"></a><span class="co"># The p-value is 0.7683 more than 0.05, so we can assume the scores are not normal</span></span>
<span id="cb39-62"><a href="#cb39-62"></a></span>
<span id="cb39-63"><a href="#cb39-63"></a><span class="co"># Plot a histogram</span></span>
<span id="cb39-64"><a href="#cb39-64"></a><span class="fu">ggplot</span>(<span class="at">data=</span>UKHighSci,</span>
<span id="cb39-65"><a href="#cb39-65"></a>       <span class="fu">aes</span>(<span class="at">x=</span>PV1SCIE))<span class="sc">+</span></span>
<span id="cb39-66"><a href="#cb39-66"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill=</span><span class="st">"darkseagreen4"</span>)</span>
<span id="cb39-67"><a href="#cb39-67"></a><span class="co"># The data don't look normal here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div>
</section><section id="task-3-variance-checking" class="level2" data-number="6.3"><h2 data-number="6.3" class="anchored" data-anchor-id="task-3-variance-checking">
<span class="header-section-number">6.3</span> Task 3 Variance checking</h2>
<p>Determine if the variance of these samples meets the criteria to carry out a t-test: a) Boys and Girls maths scores in the UK b) Reading scores in the US and the UK c) Wealth scores of boys and girls in the US</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Recall, the rule of thumb researchers use is that if the ratio of variances of the larger sample to the smaller is less than four, then a t-test can be used <span class="citation" data-cites="boneau1960effects">(<a href="#ref-boneau1960effects" role="doc-biblioref">Boneau 1960</a>)</span></p>
</div>
</div>
<div class="question">
<div class="cell">
<details><summary>Answer</summary><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a><span class="co"># a)</span></span>
<span id="cb40-2"><a href="#cb40-2"></a><span class="co"># Create a UK maths subset for boys</span></span>
<span id="cb40-3"><a href="#cb40-3"></a>PISAUKMATHM<span class="ot">&lt;-</span>PISA_2018<span class="sc">%&gt;%</span></span>
<span id="cb40-4"><a href="#cb40-4"></a>  <span class="fu">select</span>(CNT, PV1MATH,ST004D01T)<span class="sc">%&gt;%</span></span>
<span id="cb40-5"><a href="#cb40-5"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span><span class="sc">|</span>ST004D01T<span class="sc">==</span><span class="st">"Male"</span>)</span>
<span id="cb40-6"><a href="#cb40-6"></a><span class="co"># Create a UK reading subset for girls</span></span>
<span id="cb40-7"><a href="#cb40-7"></a>PISAUKMATHF<span class="ot">&lt;-</span>PISA_2018<span class="sc">%&gt;%</span></span>
<span id="cb40-8"><a href="#cb40-8"></a>  <span class="fu">select</span>(CNT, PV1MATH,ST004D01T)<span class="sc">%&gt;%</span></span>
<span id="cb40-9"><a href="#cb40-9"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span><span class="sc">|</span>ST004D01T<span class="sc">==</span><span class="st">"Female"</span>)</span>
<span id="cb40-10"><a href="#cb40-10"></a><span class="co"># Find the variance</span></span>
<span id="cb40-11"><a href="#cb40-11"></a>MVar<span class="ot">&lt;-</span><span class="fu">var</span>(PISAUKMATHM<span class="sc">$</span>PV1MATH, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb40-12"><a href="#cb40-12"></a>FVar<span class="ot">&lt;-</span><span class="fu">var</span>(PISAUKMATHF<span class="sc">$</span>PV1MATH, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb40-13"><a href="#cb40-13"></a>MVar<span class="sc">/</span>FVar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 1.132708</code></pre>
</div>
<details><summary>Answer</summary><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a><span class="co"># The ratio of variance is 1.132708 so a t-test can be performed</span></span>
<span id="cb42-2"><a href="#cb42-2"></a></span>
<span id="cb42-3"><a href="#cb42-3"></a><span class="co"># b)</span></span>
<span id="cb42-4"><a href="#cb42-4"></a><span class="co"># Create a US reading score dataframe</span></span>
<span id="cb42-5"><a href="#cb42-5"></a>USREAD<span class="ot">&lt;-</span>PISA_2018<span class="sc">%&gt;%</span></span>
<span id="cb42-6"><a href="#cb42-6"></a>  <span class="fu">select</span>(CNT, PV1READ)<span class="sc">%&gt;%</span></span>
<span id="cb42-7"><a href="#cb42-7"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United States"</span>)</span>
<span id="cb42-8"><a href="#cb42-8"></a><span class="co"># Create a UK reading score dataframe</span></span>
<span id="cb42-9"><a href="#cb42-9"></a>UKREAD<span class="ot">&lt;-</span>PISA_2018<span class="sc">%&gt;%</span></span>
<span id="cb42-10"><a href="#cb42-10"></a>  <span class="fu">select</span>(CNT, PV1READ)<span class="sc">%&gt;%</span></span>
<span id="cb42-11"><a href="#cb42-11"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span>)</span>
<span id="cb42-12"><a href="#cb42-12"></a><span class="co"># Find the variance</span></span>
<span id="cb42-13"><a href="#cb42-13"></a>UKVar<span class="ot">&lt;-</span><span class="fu">var</span>(UKREAD<span class="sc">$</span>PV1READ, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb42-14"><a href="#cb42-14"></a>USVar<span class="ot">&lt;-</span><span class="fu">var</span>(USREAD<span class="sc">$</span>PV1READ, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb42-15"><a href="#cb42-15"></a>UKVar<span class="sc">/</span>USVar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8133229</code></pre>
</div>
<details><summary>Answer</summary><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a><span class="co"># The ratio of variance is 0.813 so a t-test can be performed</span></span>
<span id="cb44-2"><a href="#cb44-2"></a></span>
<span id="cb44-3"><a href="#cb44-3"></a><span class="co"># c)</span></span>
<span id="cb44-4"><a href="#cb44-4"></a><span class="co"># Create a US Male Wealth  dataframe</span></span>
<span id="cb44-5"><a href="#cb44-5"></a>USWEALTHM<span class="ot">&lt;-</span>PISA_2018<span class="sc">%&gt;%</span></span>
<span id="cb44-6"><a href="#cb44-6"></a>  <span class="fu">select</span>(CNT, WEALTH, ST004D01T)<span class="sc">%&gt;%</span></span>
<span id="cb44-7"><a href="#cb44-7"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United States"</span><span class="sc">|</span>ST004D01T<span class="sc">==</span><span class="st">"Male"</span>)</span>
<span id="cb44-8"><a href="#cb44-8"></a><span class="co"># Create a US Female Wealth  dataframe</span></span>
<span id="cb44-9"><a href="#cb44-9"></a>USWEALTHF<span class="ot">&lt;-</span>PISA_2018<span class="sc">%&gt;%</span></span>
<span id="cb44-10"><a href="#cb44-10"></a>  <span class="fu">select</span>(CNT, WEALTH, ST004D01T)<span class="sc">%&gt;%</span></span>
<span id="cb44-11"><a href="#cb44-11"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United States"</span><span class="sc">|</span>ST004D01T<span class="sc">==</span><span class="st">"Female"</span>)</span>
<span id="cb44-12"><a href="#cb44-12"></a><span class="co"># Find the variance</span></span>
<span id="cb44-13"><a href="#cb44-13"></a>MVar<span class="ot">&lt;-</span><span class="fu">var</span>(USWEALTHM<span class="sc">$</span>WEALTH, <span class="at">na.rm =</span><span class="cn">TRUE</span>)</span>
<span id="cb44-14"><a href="#cb44-14"></a>FVar<span class="ot">&lt;-</span><span class="fu">var</span>(USWEALTHF<span class="sc">$</span>WEALTH, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb44-15"><a href="#cb44-15"></a>MVar<span class="sc">/</span>FVar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 1.05469</code></pre>
</div>
<details><summary>Answer</summary><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a><span class="co"># The ratio of variance is 1.05469 so a t-test can be performed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div>
</section><section id="task-4-performing-t-tests" class="level2" data-number="6.4"><h2 data-number="6.4" class="anchored" data-anchor-id="task-4-performing-t-tests">
<span class="header-section-number">6.4</span> Task 4 Performing t-tests</h2>
<div class="question">
<ol type="1">
<li>Use the PISA dataset and the gender <code>ST004D01T</code> and <code>PV1MATH</code> (Math score) variables to perform a two-sided, unpaired t-test to determine if boys and girls perform differently on the test in the UK. Before performing the test, check for the normality of the data, and check for equal variance.</li>
</ol>
</div>
<div class="question">
<ol start="2" type="1">
<li>Choose a different country of interest to compare performance in males and females in that country</li>
</ol>
<div class="cell">
<details><summary>Answer</summary><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1"></a><span class="co"># Are there differences between the mean scores of boys and girls in China PISA mathematics?</span></span>
<span id="cb47-2"><a href="#cb47-2"></a><span class="co">#</span></span>
<span id="cb47-3"><a href="#cb47-3"></a><span class="co"># Select the gender (ST004D01T) and math score columns (PV1MATH)</span></span>
<span id="cb47-4"><a href="#cb47-4"></a><span class="co"># Filter the data to select UK responses</span></span>
<span id="cb47-5"><a href="#cb47-5"></a></span>
<span id="cb47-6"><a href="#cb47-6"></a>MaleChina <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb47-7"><a href="#cb47-7"></a>  <span class="fu">select</span>(CNT,ST004D01T, PV1MATH) <span class="sc">%&gt;%</span></span>
<span id="cb47-8"><a href="#cb47-8"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">'B-S-J-Z (China)'</span>, ST004D01T<span class="sc">==</span><span class="st">'Male'</span>)</span>
<span id="cb47-9"><a href="#cb47-9"></a></span>
<span id="cb47-10"><a href="#cb47-10"></a>FemaleChina<span class="ot">&lt;-</span>PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb47-11"><a href="#cb47-11"></a>  <span class="fu">select</span>(CNT,ST004D01T, PV1MATH) <span class="sc">%&gt;%</span></span>
<span id="cb47-12"><a href="#cb47-12"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">'B-S-J-Z (China)'</span>, ST004D01T<span class="sc">==</span><span class="st">'Female'</span>)</span>
<span id="cb47-13"><a href="#cb47-13"></a></span>
<span id="cb47-14"><a href="#cb47-14"></a><span class="co"># The conditions to do a t-test include that the data are normally distributed</span></span>
<span id="cb47-15"><a href="#cb47-15"></a><span class="fu">qqnorm</span>(MaleChina<span class="sc">$</span>PV1MATH)</span>
<span id="cb47-16"><a href="#cb47-16"></a><span class="fu">qqline</span>(MaleChina<span class="sc">$</span>PV1MATH, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb47-17"><a href="#cb47-17"></a><span class="fu">qqnorm</span>(FemaleChina<span class="sc">$</span>PV1MATH)</span>
<span id="cb47-18"><a href="#cb47-18"></a><span class="fu">qqline</span>(FemaleChina<span class="sc">$</span>PV1MATH, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb47-19"><a href="#cb47-19"></a></span>
<span id="cb47-20"><a href="#cb47-20"></a></span>
<span id="cb47-21"><a href="#cb47-21"></a><span class="co"># The plots produces relatively straight lines so the distributions can be # assumed to be normal</span></span>
<span id="cb47-22"><a href="#cb47-22"></a><span class="co">#</span></span>
<span id="cb47-23"><a href="#cb47-23"></a><span class="co"># We will then check the variances of the two data sets</span></span>
<span id="cb47-24"><a href="#cb47-24"></a></span>
<span id="cb47-25"><a href="#cb47-25"></a>VarM<span class="ot">&lt;-</span><span class="fu">var</span>(MaleChina<span class="sc">$</span>PV1MATH, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb47-26"><a href="#cb47-26"></a>VarF<span class="ot">&lt;-</span><span class="fu">var</span>(FemaleChina<span class="sc">$</span>PV1MATH, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb47-27"><a href="#cb47-27"></a>VarM<span class="sc">/</span>VarF</span>
<span id="cb47-28"><a href="#cb47-28"></a></span>
<span id="cb47-29"><a href="#cb47-29"></a><span class="co"># The variance ratio is close to 1 (1.17)</span></span>
<span id="cb47-30"><a href="#cb47-30"></a><span class="co"># So our two conditions are met and can we can perform the t-test</span></span>
<span id="cb47-31"><a href="#cb47-31"></a></span>
<span id="cb47-32"><a href="#cb47-32"></a><span class="co"># Create a UK Math subset</span></span>
<span id="cb47-33"><a href="#cb47-33"></a>CHIMATH<span class="ot">&lt;-</span>PISA_2018<span class="sc">%&gt;%</span></span>
<span id="cb47-34"><a href="#cb47-34"></a>  <span class="fu">select</span>(CNT, PV1MATH,ST004D01T)<span class="sc">%&gt;%</span></span>
<span id="cb47-35"><a href="#cb47-35"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"B-S-J-Z (China)"</span>)</span>
<span id="cb47-36"><a href="#cb47-36"></a><span class="co"># Plot a two-sided, unpaired t-test</span></span>
<span id="cb47-37"><a href="#cb47-37"></a><span class="fu">t.test</span>(PV1MATH <span class="sc">~</span> ST004D01T, <span class="at">data =</span> CHIMATH, </span>
<span id="cb47-38"><a href="#cb47-38"></a>       <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span>
<span id="cb47-39"><a href="#cb47-39"></a></span>
<span id="cb47-40"><a href="#cb47-40"></a><span class="co"># The p-value is &lt;0.05 (2.414e-07) suggesting there are statistically</span></span>
<span id="cb47-41"><a href="#cb47-41"></a><span class="co"># differences between boys and girls in mathematics in China</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div>
<div class="question">
<ol start="3" type="1">
<li>Now try to compare the performance of males and females in Maths in all the <code>OECD</code> countries in the PISA dataset. You may need to think about how to do this using R without repeating the test for each country.</li>
</ol>
<div class="cell">
<details><summary>Answer</summary><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a>MaleOECD <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="#cb48-2"></a>  <span class="fu">select</span>(OECD, ST004D01T, PV1MATH) <span class="sc">%&gt;%</span></span>
<span id="cb48-3"><a href="#cb48-3"></a>  <span class="fu">filter</span>(OECD<span class="sc">==</span><span class="st">'Yes'</span>, ST004D01T<span class="sc">==</span><span class="st">'Male'</span>)</span>
<span id="cb48-4"><a href="#cb48-4"></a></span>
<span id="cb48-5"><a href="#cb48-5"></a>FemaleOECD <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb48-6"><a href="#cb48-6"></a>  <span class="fu">select</span>(OECD, ST004D01T, PV1MATH) <span class="sc">%&gt;%</span></span>
<span id="cb48-7"><a href="#cb48-7"></a>  <span class="fu">filter</span>(OECD<span class="sc">==</span><span class="st">'Yes'</span>, ST004D01T<span class="sc">==</span><span class="st">'Female'</span>)</span>
<span id="cb48-8"><a href="#cb48-8"></a></span>
<span id="cb48-9"><a href="#cb48-9"></a><span class="fu">qqnorm</span>(MaleOECD<span class="sc">$</span>PV1MATH)</span>
<span id="cb48-10"><a href="#cb48-10"></a><span class="fu">qqline</span>(MaleOECD<span class="sc">$</span>PV1MATH, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb48-11"><a href="#cb48-11"></a><span class="fu">qqnorm</span>(FemaleOECD<span class="sc">$</span>PV1MATH)</span>
<span id="cb48-12"><a href="#cb48-12"></a><span class="fu">qqline</span>(FemaleOECD<span class="sc">$</span>PV1MATH, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb48-13"><a href="#cb48-13"></a></span>
<span id="cb48-14"><a href="#cb48-14"></a></span>
<span id="cb48-15"><a href="#cb48-15"></a><span class="co"># The plots produces relatively straight lines so the distributions can be assumed to be normal</span></span>
<span id="cb48-16"><a href="#cb48-16"></a></span>
<span id="cb48-17"><a href="#cb48-17"></a><span class="co"># We will then check the variances of the two data sets</span></span>
<span id="cb48-18"><a href="#cb48-18"></a></span>
<span id="cb48-19"><a href="#cb48-19"></a>VarM <span class="ot">&lt;-</span> <span class="fu">var</span>(MaleOECD<span class="sc">$</span>PV1MATH, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb48-20"><a href="#cb48-20"></a>VarF <span class="ot">&lt;-</span> <span class="fu">var</span>(FemaleOECD<span class="sc">$</span>PV1MATH, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb48-21"><a href="#cb48-21"></a>VarM <span class="sc">/</span> VarF</span>
<span id="cb48-22"><a href="#cb48-22"></a></span>
<span id="cb48-23"><a href="#cb48-23"></a><span class="co"># The variance ratio is close to 1 (1.1)</span></span>
<span id="cb48-24"><a href="#cb48-24"></a><span class="co"># So our two conditions are met and can we can perform the t-test</span></span>
<span id="cb48-25"><a href="#cb48-25"></a></span>
<span id="cb48-26"><a href="#cb48-26"></a><span class="co"># The p-value is &lt;0.05 (2.2e-16) suggesting there are statistically</span></span>
<span id="cb48-27"><a href="#cb48-27"></a><span class="co"># differences between boys and girls</span></span>
<span id="cb48-28"><a href="#cb48-28"></a></span>
<span id="cb48-29"><a href="#cb48-29"></a>OECD <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb48-30"><a href="#cb48-30"></a>  <span class="fu">select</span>(OECD, ST004D01T, PV1MATH) <span class="sc">%&gt;%</span></span>
<span id="cb48-31"><a href="#cb48-31"></a>  <span class="fu">filter</span>(OECD<span class="sc">==</span><span class="st">'Yes'</span>)</span>
<span id="cb48-32"><a href="#cb48-32"></a></span>
<span id="cb48-33"><a href="#cb48-33"></a><span class="fu">t.test</span>(PV1MATH <span class="sc">~</span> ST004D01T, <span class="at">data =</span> OECD, </span>
<span id="cb48-34"><a href="#cb48-34"></a>       <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div>
<div class="question">
<ol start="4" type="1">
<li>Are there statistically significant differences in mean wealth scores of boys and girls in the UK?</li>
</ol>
<div class="cell">
<details><summary>Answer</summary><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1"></a>MaleUK <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb49-2"><a href="#cb49-2"></a>  <span class="fu">select</span>(ST004D01T, WEALTH) <span class="sc">%&gt;%</span></span>
<span id="cb49-3"><a href="#cb49-3"></a>  <span class="fu">filter</span>(ST004D01T<span class="sc">==</span><span class="st">'Male'</span>)</span>
<span id="cb49-4"><a href="#cb49-4"></a></span>
<span id="cb49-5"><a href="#cb49-5"></a>FemaleUK <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb49-6"><a href="#cb49-6"></a>  <span class="fu">select</span>(ST004D01T, WEALTH) <span class="sc">%&gt;%</span></span>
<span id="cb49-7"><a href="#cb49-7"></a>  <span class="fu">filter</span>(ST004D01T<span class="sc">==</span><span class="st">'Female'</span>)</span>
<span id="cb49-8"><a href="#cb49-8"></a></span>
<span id="cb49-9"><a href="#cb49-9"></a><span class="fu">qqnorm</span>(MaleUK<span class="sc">$</span>WEALTH)</span>
<span id="cb49-10"><a href="#cb49-10"></a><span class="fu">qqline</span>(MaleUK<span class="sc">$</span>WEALTH, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb49-11"><a href="#cb49-11"></a><span class="fu">qqnorm</span>(FemaleUK<span class="sc">$</span>WEALTH)</span>
<span id="cb49-12"><a href="#cb49-12"></a><span class="fu">qqline</span>(FemaleUK<span class="sc">$</span>WEALTH, <span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb49-13"><a href="#cb49-13"></a></span>
<span id="cb49-14"><a href="#cb49-14"></a><span class="co"># The plots here are somewhat skewed which might suggest not performing the test</span></span>
<span id="cb49-15"><a href="#cb49-15"></a></span>
<span id="cb49-16"><a href="#cb49-16"></a><span class="co"># We will then check the variances of the two data sets</span></span>
<span id="cb49-17"><a href="#cb49-17"></a></span>
<span id="cb49-18"><a href="#cb49-18"></a>VarM <span class="ot">&lt;-</span> <span class="fu">var</span>(MaleUK<span class="sc">$</span>WEALTH, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb49-19"><a href="#cb49-19"></a>VarF <span class="ot">&lt;-</span> <span class="fu">var</span>(FemaleUK<span class="sc">$</span>WEALTH, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb49-20"><a href="#cb49-20"></a>VarM <span class="sc">/</span> VarF</span>
<span id="cb49-21"><a href="#cb49-21"></a></span>
<span id="cb49-22"><a href="#cb49-22"></a><span class="co"># The variance ratio is close to 1 (1.1)</span></span>
<span id="cb49-23"><a href="#cb49-23"></a><span class="co"># So our two conditions are met and can we can perform the t-test</span></span>
<span id="cb49-24"><a href="#cb49-24"></a></span>
<span id="cb49-25"><a href="#cb49-25"></a>WEALTH <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb49-26"><a href="#cb49-26"></a>  <span class="fu">select</span>(WEALTH, ST004D01T, CNT) <span class="sc">%&gt;%</span></span>
<span id="cb49-27"><a href="#cb49-27"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">'United Kingdom'</span>)</span>
<span id="cb49-28"><a href="#cb49-28"></a></span>
<span id="cb49-29"><a href="#cb49-29"></a><span class="fu">t.test</span>(PV1MATH <span class="sc">~</span> ST004D01T, <span class="at">data =</span> OECD, </span>
<span id="cb49-30"><a href="#cb49-30"></a>       <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span>
<span id="cb49-31"><a href="#cb49-31"></a></span>
<span id="cb49-32"><a href="#cb49-32"></a><span class="co"># p-value &lt; 2.2e-16 so there are statistically significant differences between boys' and girls' reported wealth in the UK</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div>
</section><section id="task-5-multiple-t-tests-with-anova" class="level2" data-number="6.5"><h2 data-number="6.5" class="anchored" data-anchor-id="task-5-multiple-t-tests-with-anova">
<span class="header-section-number">6.5</span> Task 5 Multiple t-tests with anova</h2>
<div class="question">
<p>For the UK, France, Thailand, and the US determine if there are statistically significant differences in variation in mathematics scores.</p>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a>PISAMULTI<span class="ot">&lt;-</span>PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="#cb50-2"></a>  <span class="fu">select</span>(CNT, PV1MATH)<span class="sc">%&gt;%</span></span>
<span id="cb50-3"><a href="#cb50-3"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span> <span class="sc">|</span> CNT<span class="sc">==</span><span class="st">"Thailand"</span> <span class="sc">|</span> CNT<span class="sc">==</span><span class="st">"United States"</span> <span class="sc">|</span> CNT<span class="sc">==</span><span class="st">"France"</span>)</span>
<span id="cb50-4"><a href="#cb50-4"></a></span>
<span id="cb50-5"><a href="#cb50-5"></a></span>
<span id="cb50-6"><a href="#cb50-6"></a>resaov<span class="ot">&lt;-</span><span class="fu">aov</span>(PV1MATH <span class="sc">~</span> CNT, <span class="at">data=</span>PISAMULTI)</span>
<span id="cb50-7"><a href="#cb50-7"></a>sumresaov<span class="ot">&lt;-</span><span class="fu">summary</span>(resaov)</span>
<span id="cb50-8"><a href="#cb50-8"></a>sumresaov</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>               Df    Sum Sq Mean Sq F value Pr(&gt;F)    
CNT             3  19708753 6569584   731.4 &lt;2e-16 ***
Residuals   33593 301722376    8982                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a>eta<span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(<span class="fu">etaSquared</span>(resaov))</span>
<span id="cb52-2"><a href="#cb52-2"></a>eta<span class="ot">&lt;-</span>eta<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb52-3"><a href="#cb52-3"></a>eta</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>      eta.sq eta.sq.part
CNT 6.131563    6.131563</code></pre>
</div>
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a><span class="fu">TukeyHSD</span>(resaov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = PV1MATH ~ CNT, data = PISAMULTI)

$CNT
                                   diff        lwr        upr p adj
United Kingdom-France          9.517876   5.818238  13.217513     0
Thailand-France              -49.928145 -53.960994 -45.895296     0
United States-France         -14.083379 -18.736341  -9.430416     0
 [ reached getOption("max.print") -- omitted 3 rows ]</code></pre>
</div>
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a><span class="co"># There are statistically significant differences in mathematics scores for all pairs of countries</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div>
<div class="question">
<p>For the UK, are there statistically significant differences in reading score by students who attend different types of school (<code>ISCEDO</code>), e.g. Vocational, General etc.</p>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1"></a>UKSchRead<span class="ot">&lt;-</span>PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb57-2"><a href="#cb57-2"></a>  <span class="fu">select</span>(CNT, PV1READ, ISCEDO)<span class="sc">%&gt;%</span></span>
<span id="cb57-3"><a href="#cb57-3"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span>)</span>
<span id="cb57-4"><a href="#cb57-4"></a></span>
<span id="cb57-5"><a href="#cb57-5"></a></span>
<span id="cb57-6"><a href="#cb57-6"></a>resaov<span class="ot">&lt;-</span><span class="fu">aov</span>(PV1READ <span class="sc">~</span> ISCEDO, <span class="at">data=</span>UKSchRead)</span>
<span id="cb57-7"><a href="#cb57-7"></a>sumresaov<span class="ot">&lt;-</span><span class="fu">summary</span>(resaov)</span>
<span id="cb57-8"><a href="#cb57-8"></a>sumresaov</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>               Df    Sum Sq Mean Sq F value  Pr(&gt;F)   
ISCEDO          2    126441   63221   6.614 0.00135 **
Residuals   13815 132056332    9559                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1"></a>eta<span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(<span class="fu">etaSquared</span>(resaov))</span>
<span id="cb59-2"><a href="#cb59-2"></a>eta<span class="ot">&lt;-</span>eta<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb59-3"><a href="#cb59-3"></a>eta</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>           eta.sq eta.sq.part
ISCEDO 0.09565645  0.09565645</code></pre>
</div>
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1"></a><span class="fu">TukeyHSD</span>(resaov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = PV1READ ~ ISCEDO, data = UKSchRead)

$ISCEDO
                                diff         lwr       upr     p adj
Pre-Vocational-General    -102.78896 -175.284439 -30.29348 0.0025668
Vocational-General         -21.40641  -55.251751  12.43893 0.2993528
Vocational-Pre-Vocational   81.38255    1.423372 161.34172 0.0449504</code></pre>
</div>
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1"></a><span class="co"># There are statistically significant differences between Pre-vocational and general, and vocational and pre-vocational, but not between vocational and general.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div>
<div class="question">
<p>For the UK, use <code>ifelse</code> on the WEALTH variable to create categories for four quartiles (divide the data into top; upper-mid; lower-mid; and bottom). Use anova to determine between which groups there are statistically significant differences in science scores</p>
<p>Hint: You can use <code>quantiles&lt;-quantile(UKSci$PV1SCIE, prob=c(.25,.5,.75), na.rm=TRUE)</code> to give the values of PV1SCIE that account for 25%, 50% and 75% of the responses.</p>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1"></a>UKSci<span class="ot">&lt;-</span>PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb64-2"><a href="#cb64-2"></a>  <span class="fu">select</span>(CNT, PV1SCIE, WEALTH)<span class="sc">%&gt;%</span></span>
<span id="cb64-3"><a href="#cb64-3"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb64-4"><a href="#cb64-4"></a>  <span class="fu">na.omit</span>()<span class="sc">%&gt;%</span></span>
<span id="cb64-5"><a href="#cb64-5"></a>  <span class="fu">droplevels</span>()<span class="sc">%&gt;%</span></span>
<span id="cb64-6"><a href="#cb64-6"></a>  <span class="fu">select</span>(PV1SCIE, WEALTH)</span>
<span id="cb64-7"><a href="#cb64-7"></a><span class="co"># Find the cut of points for 25%, 50% and 75% (quantiles) of WEALTH</span></span>
<span id="cb64-8"><a href="#cb64-8"></a>quantiles<span class="ot">&lt;-</span><span class="fu">quantile</span>(UKSci<span class="sc">$</span>WEALTH, <span class="at">prob=</span><span class="fu">c</span>(.<span class="dv">25</span>,.<span class="dv">5</span>,.<span class="dv">75</span>), <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb64-9"><a href="#cb64-9"></a></span>
<span id="cb64-10"><a href="#cb64-10"></a>UKSci<span class="ot">&lt;-</span>UKSci<span class="sc">%&gt;%</span></span>
<span id="cb64-11"><a href="#cb64-11"></a>  <span class="fu">mutate</span>(<span class="at">WEALTH=</span><span class="fu">ifelse</span>(WEALTH<span class="sc">&lt;</span>quantiles[<span class="dv">1</span>], <span class="st">"Bottom"</span>, </span>
<span id="cb64-12"><a href="#cb64-12"></a>                        <span class="fu">ifelse</span>(WEALTH<span class="sc">&lt;</span>quantiles[<span class="dv">2</span>], <span class="st">"Lower-mid"</span>,</span>
<span id="cb64-13"><a href="#cb64-13"></a>                               <span class="fu">ifelse</span>(WEALTH<span class="sc">&lt;</span>quantiles[<span class="dv">3</span>], <span class="st">"Upper-mid"</span>,<span class="st">"Top"</span>))))</span>
<span id="cb64-14"><a href="#cb64-14"></a></span>
<span id="cb64-15"><a href="#cb64-15"></a>resaov<span class="ot">&lt;-</span><span class="fu">aov</span>(PV1SCIE <span class="sc">~</span> WEALTH, <span class="at">data=</span>UKSci)</span>
<span id="cb64-16"><a href="#cb64-16"></a>sumresaov<span class="ot">&lt;-</span><span class="fu">summary</span>(resaov)</span>
<span id="cb64-17"><a href="#cb64-17"></a>sumresaov</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>               Df    Sum Sq Mean Sq F value Pr(&gt;F)    
WEALTH          3   1531216  510405   57.19 &lt;2e-16 ***
Residuals   13363 119258836    8925                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1"></a><span class="fu">TukeyHSD</span>(resaov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = PV1SCIE ~ WEALTH, data = UKSci)

$WEALTH
                          diff         lwr       upr     p adj
Lower-mid-Bottom     11.013562   5.0690229 16.958100 0.0000116
Top-Bottom           29.568912  23.6310625 35.506762 0.0000000
Upper-mid-Bottom     17.452150  11.5204961 23.383804 0.0000000
 [ reached getOption("max.print") -- omitted 3 rows ]</code></pre>
</div>
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1"></a><span class="co"># There are statistically significant differences between all groups by wealth</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div>
</section></section><section id="extension-and-additional-reading" class="level1" data-number="7"><h1 data-number="7">
<span class="header-section-number">7</span> Extension and additional reading</h1>
<section id="recreating-a-paper-in-r" class="level2" data-number="7.1"><h2 data-number="7.1" class="anchored" data-anchor-id="recreating-a-paper-in-r">
<span class="header-section-number">7.1</span> Recreating a paper in R</h2>
<div class="question">
<p>Looking at the reading <span class="citation" data-cites="cook2014visiphilia">Cook (<a href="#ref-cook2014visiphilia" role="doc-biblioref">2014</a>)</span>, consider the following</p>
<!-- -->
<ol type="1">
<li>Is it possible to replicate the results using the PISA 2018 data set? Make a graph showing the difference in male and female <code>PV1MATH</code> results for each country <code>CNT</code>. To do this we are going to have to:</li>
</ol>
<ul>
<li>work out the <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code> maths score <code>PV1MATH</code> for each country <code>CNT</code> and gender <code>ST004D01T</code> grouping, call this <code>meanmath</code> and create a new dataframe to store this</li>
<li>from this dataframe, create two new dataframes, one for males only and one for females only</li>
<li>
<code>rename()</code> (see <strong>?@sec-renaming</strong>) the <code>meanmath</code> score in each dataframe to <code>male_mean</code> and <code>female_mean</code>
</li>
<li>bind the dataframes together using using column bind function <code>cbind(&lt;male_df&gt;, &lt;female_df&gt;)</code> and store this in a new dataframe called <code>Mathgendergap</code>. <strong>NOTE:</strong> cbind only accepts tables with different names, so you’ll need to select <code>select(CNT, male_mean)</code> from the male dataframe and <code>select(female_mean)</code> from the female dataframe.</li>
<li>use <code>mutate</code> (see <strong>?@sec-mutate</strong>) to calculate the difference in male and female mean maths scores for each country</li>
<li>plot the results for each country</li>
</ul>
<div class="cell">
<details><summary>creating difference dataset</summary><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1"></a><span class="co"># A relatively simple recreation (without significance testing)</span></span>
<span id="cb69-2"><a href="#cb69-2"></a>Mathgendergap <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb69-3"><a href="#cb69-3"></a>  <span class="fu">select</span>(CNT,PV1MATH,ST004D01T) <span class="sc">%&gt;%</span></span>
<span id="cb69-4"><a href="#cb69-4"></a>  <span class="fu">group_by</span>(CNT,ST004D01T)<span class="sc">%&gt;%</span></span>
<span id="cb69-5"><a href="#cb69-5"></a>  <span class="fu">summarise</span>(<span class="at">meanmath=</span><span class="fu">mean</span>(PV1MATH)) <span class="sc">%&gt;%</span></span>
<span id="cb69-6"><a href="#cb69-6"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb69-7"><a href="#cb69-7"></a></span>
<span id="cb69-8"><a href="#cb69-8"></a><span class="co"># alternative, using column binding, cbind():</span></span>
<span id="cb69-9"><a href="#cb69-9"></a>Mathgendergap<span class="ot">&lt;-</span>  <span class="fu">cbind</span>(Mathgendergap <span class="sc">%&gt;%</span> </span>
<span id="cb69-10"><a href="#cb69-10"></a>                           <span class="fu">filter</span>(ST004D01T <span class="sc">==</span> <span class="st">"Male"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb69-11"><a href="#cb69-11"></a>                           <span class="fu">rename</span>(<span class="at">male_mean =</span> meanmath) <span class="sc">%&gt;%</span></span>
<span id="cb69-12"><a href="#cb69-12"></a>                             <span class="fu">select</span>(CNT, male_mean),</span>
<span id="cb69-13"><a href="#cb69-13"></a>                        Mathgendergap <span class="sc">%&gt;%</span></span>
<span id="cb69-14"><a href="#cb69-14"></a>                           <span class="fu">filter</span>(ST004D01T <span class="sc">==</span> <span class="st">"Female"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb69-15"><a href="#cb69-15"></a>                             <span class="fu">rename</span>(<span class="at">female_mean =</span> meanmath) <span class="sc">%&gt;%</span></span>
<span id="cb69-16"><a href="#cb69-16"></a>                             <span class="fu">select</span>(female_mean))</span>
<span id="cb69-17"><a href="#cb69-17"></a></span>
<span id="cb69-18"><a href="#cb69-18"></a><span class="co"># alternatively you can use pivot_wider</span></span>
<span id="cb69-19"><a href="#cb69-19"></a><span class="co"># Mathgendergap &lt;- pivot_wider(Mathgendergap, names_from = ST004D01T, values_from = meanmath)</span></span>
<span id="cb69-20"><a href="#cb69-20"></a></span>
<span id="cb69-21"><a href="#cb69-21"></a>Mathgendergap <span class="ot">&lt;-</span> Mathgendergap <span class="sc">%&gt;%</span></span>
<span id="cb69-22"><a href="#cb69-22"></a>  <span class="fu">mutate</span>(<span class="at">difference =</span> female_mean <span class="sc">-</span> male_mean) <span class="sc">%&gt;%</span></span>
<span id="cb69-23"><a href="#cb69-23"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(difference))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The above code doesn’t include the t-test results for each country, to do this we need to run some more complex code, you can see how it works below:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="07-T-testsPISA_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="2" type="1">
<li>What issues are there with using a t-test for the context given in the paper?</li>
<li>How do your findings from question 3 and the 2018 dataset compare with those in the paper? Are there any differences or disagreements with your findings?</li>
<li>How could the paper be improved?</li>
</ol>
</div>
</section></section><section id="doing-t-tests-in-r" class="level1" data-number="8"><h1 data-number="8">
<span class="header-section-number">8</span> Doing t-tests in R</h1>
<iframe width="560" height="315" src="https://www.youtube.com/embed/KdhAcLPq5B4?start=3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
<p>You can find the code from the video below:</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1"></a><span class="co"># Introduction to t-tests in R</span></span>
<span id="cb70-2"><a href="#cb70-2"></a><span class="co">#</span></span>
<span id="cb70-3"><a href="#cb70-3"></a><span class="co"># Download data from /Users/k1765032/Library/CloudStorage/GoogleDrive-richardandrewbrock@gmail.com/.shortcut-targets-by-id/1c3CkaEBOICzepArDfjQUP34W2BYhFjM4/PISR/Data/PISA/subset/Students_2018_RBDP_none_levels.rds</span></span>
<span id="cb70-4"><a href="#cb70-4"></a><span class="co"># You want the file: Students_2018_RBDP_none_levels.rds</span></span>
<span id="cb70-5"><a href="#cb70-5"></a><span class="co"># and place in your own file system</span></span>
<span id="cb70-6"><a href="#cb70-6"></a><span class="co"># change loc to load the data directly. Loading into R might take a few minutes</span></span>
<span id="cb70-7"><a href="#cb70-7"></a><span class="fu">install.packages</span>(<span class="st">"nortest"</span>)</span>
<span id="cb70-8"><a href="#cb70-8"></a></span>
<span id="cb70-9"><a href="#cb70-9"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb70-10"><a href="#cb70-10"></a><span class="fu">library</span>(nortest)</span>
<span id="cb70-11"><a href="#cb70-11"></a>loc <span class="ot">&lt;-</span> <span class="st">"/Users/k1765032/Library/CloudStorage/GoogleDrive-richardandrewbrock@gmail.com/.shortcut-targets-by-id/1c3CkaEBOICzepArDfjQUP34W2BYhFjM4/PISR/Data/PISA/subset/Students_2018_RBDP_none_levels.rds"</span></span>
<span id="cb70-12"><a href="#cb70-12"></a>PISA_2018 <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(loc)</span>
<span id="cb70-13"><a href="#cb70-13"></a></span>
<span id="cb70-14"><a href="#cb70-14"></a><span class="co"># Are there differences between the mean scores of UK boys and girls in PISA mathematics?</span></span>
<span id="cb70-15"><a href="#cb70-15"></a><span class="co">#</span></span>
<span id="cb70-16"><a href="#cb70-16"></a><span class="co"># Select the gender (ST004D01T) and math score columns (PV1MATH)</span></span>
<span id="cb70-17"><a href="#cb70-17"></a><span class="co"># Filter the data to select UK responses</span></span>
<span id="cb70-18"><a href="#cb70-18"></a></span>
<span id="cb70-19"><a href="#cb70-19"></a>MaleUK<span class="ot">&lt;-</span>PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb70-20"><a href="#cb70-20"></a>  <span class="fu">select</span>(CNT,ST004D01T, PV1MATH) <span class="sc">%&gt;%</span></span>
<span id="cb70-21"><a href="#cb70-21"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">'United Kingdom'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb70-22"><a href="#cb70-22"></a>  <span class="fu">filter</span>(ST004D01T<span class="sc">==</span><span class="st">'Male'</span>)</span>
<span id="cb70-23"><a href="#cb70-23"></a></span>
<span id="cb70-24"><a href="#cb70-24"></a>FemaleUK<span class="ot">&lt;-</span>PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb70-25"><a href="#cb70-25"></a>  <span class="fu">select</span>(CNT,ST004D01T, PV1MATH) <span class="sc">%&gt;%</span></span>
<span id="cb70-26"><a href="#cb70-26"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">'United Kingdom'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb70-27"><a href="#cb70-27"></a>  <span class="fu">filter</span>(ST004D01T<span class="sc">==</span><span class="st">'Female'</span>)</span>
<span id="cb70-28"><a href="#cb70-28"></a></span>
<span id="cb70-29"><a href="#cb70-29"></a><span class="co"># The conditions to do a t-test include that the data are normally distributed</span></span>
<span id="cb70-30"><a href="#cb70-30"></a><span class="co"># and there is homogeneity (similarity) of the variances (the squared standard deviations)</span></span>
<span id="cb70-31"><a href="#cb70-31"></a><span class="co"># Let us check the conditions are met by calculating first if the data sets are normally</span></span>
<span id="cb70-32"><a href="#cb70-32"></a><span class="co"># distributed using the Pearson test of normality from the nortest package</span></span>
<span id="cb70-33"><a href="#cb70-33"></a></span>
<span id="cb70-34"><a href="#cb70-34"></a><span class="fu">pearson.test</span>(<span class="fu">as.numeric</span>(MaleUK<span class="sc">$</span>PV1MATH))</span>
<span id="cb70-35"><a href="#cb70-35"></a><span class="fu">pearson.test</span>(<span class="fu">as.numeric</span>(FemaleUK<span class="sc">$</span>PV1MATH))</span>
<span id="cb70-36"><a href="#cb70-36"></a></span>
<span id="cb70-37"><a href="#cb70-37"></a><span class="co"># The p-values are over 0.05 so both distriburtions are normal</span></span>
<span id="cb70-38"><a href="#cb70-38"></a><span class="co"># Pearson chi-square normality test</span></span>
<span id="cb70-39"><a href="#cb70-39"></a><span class="co">#</span></span>
<span id="cb70-40"><a href="#cb70-40"></a><span class="co"># data:  as.numeric(MaleUK$PV1MATH)</span></span>
<span id="cb70-41"><a href="#cb70-41"></a><span class="co"># P = 75.714, p-value = 0.1936</span></span>
<span id="cb70-42"><a href="#cb70-42"></a><span class="co"># Pearson chi-square normality test</span></span>
<span id="cb70-43"><a href="#cb70-43"></a><span class="co">#</span></span>
<span id="cb70-44"><a href="#cb70-44"></a><span class="co"># data:  as.numeric(FemaleUK$PV1MATH)</span></span>
<span id="cb70-45"><a href="#cb70-45"></a><span class="co"># P = 74.06, p-value = 0.2589</span></span>
<span id="cb70-46"><a href="#cb70-46"></a><span class="co">#</span></span>
<span id="cb70-47"><a href="#cb70-47"></a><span class="co"># We will then check the variances of the two data sets</span></span>
<span id="cb70-48"><a href="#cb70-48"></a></span>
<span id="cb70-49"><a href="#cb70-49"></a>VarM<span class="ot">&lt;-</span><span class="fu">var</span>(MaleUK<span class="sc">$</span>PV1MATH)</span>
<span id="cb70-50"><a href="#cb70-50"></a>VarF<span class="ot">&lt;-</span><span class="fu">var</span>(FemaleUK<span class="sc">$</span>PV1MATH)</span>
<span id="cb70-51"><a href="#cb70-51"></a>VarM<span class="sc">/</span>VarF</span>
<span id="cb70-52"><a href="#cb70-52"></a></span>
<span id="cb70-53"><a href="#cb70-53"></a><span class="co"># The variance ratio is close to 1 (1.1)</span></span>
<span id="cb70-54"><a href="#cb70-54"></a><span class="co"># So our two conditions are met and can we can perform the t-test</span></span>
<span id="cb70-55"><a href="#cb70-55"></a></span>
<span id="cb70-56"><a href="#cb70-56"></a><span class="fu">t.test</span>(MaleUK<span class="sc">$</span>PV1MATH, FemaleUK<span class="sc">$</span>PV1MATH)</span>
<span id="cb70-57"><a href="#cb70-57"></a></span>
<span id="cb70-58"><a href="#cb70-58"></a><span class="co"># The p-value is &lt;0.05 (4.061e-08) suggesting there are statistically</span></span>
<span id="cb70-59"><a href="#cb70-59"></a><span class="co"># differences between boys and girls</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>



</section><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-baker2016statisticians" class="csl-entry" role="listitem">
Baker, M. 2016. <span>“Statisticians Issue Warning over Misuse of p Values.”</span> <em>Nature</em>.
</div>
<div id="ref-boneau1960effects" class="csl-entry" role="listitem">
Boneau, C Alan. 1960. <span>“The Effects of Violations of Assumptions Underlying the t Test.”</span> <em>Psychological Bulletin</em> 57 (1): 49.
</div>
<div id="ref-cohen1994earth" class="csl-entry" role="listitem">
Cohen, Jacob. 1994. <span>“The Earth Is Round (p&lt;. 05).”</span> <em>American Psychologist</em> 49 (12): 997.
</div>
<div id="ref-cook2014visiphilia" class="csl-entry" role="listitem">
Cook, Di. 2014. <span>“Visiphilia: The Gender Gap in Math Is Not Universal.”</span> <em>Chance</em> 27 (4): 48–52. <a href="https://www.tandfonline.com/doi/full/10.1080/09332480.2014.988961">https://www.tandfonline.com/doi/full/10.1080/09332480.2014.988961</a>.
</div>
<div id="ref-hanna2013psychology" class="csl-entry" role="listitem">
Hanna, Donncha, and Martin Dempster. 2013. <em>Psychology Statistics for Dummies</em>. John Wiley &amp; Sons.
</div>
<div id="ref-wilkinson2018assessing" class="csl-entry" role="listitem">
Wilkinson, David, Alex Bryson, and Lucy Stokes. 2018. <span>“Assessing the Variance in Pupil Attainment: How Important Is the School Attended?”</span> <em>National Institute Economic Review</em> 243 (1): R4–16. <a href="https://docs.iza.org/dp11372.pdf">https://docs.iza.org/dp11372.pdf</a>.
</div>
</div></section></div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>