<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>MASTEMR - 10 Correlation and regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><link rel="stylesheet" href="../css/mastemr.css">
</head>
<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="index.qmd" class="navbar-brand navbar-brand-logo">
    <img src="../images/KCL_logo.png" alt="" class="navbar-logo"></a>
    <a class="navbar-brand" href="index.qmd">
    <span class="navbar-title">MASTEMR</span>
    </a>
  </div>
        <div class="quarto-navbar-tools ms-auto">
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/01-Intro_to_quant_methods.html">Sessions</a></li><li class="breadcrumb-item"><a href="../chapters/10-Correlation_and_regression.html">10 Correlation and regression</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto"><div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Sessions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-Intro_to_quant_methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">01 Introduction</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">02 Introduction to R</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-1-Intro_to_analysis_software.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-2-Intro_to_analysis_software.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Loading packages and exploring data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-3-Intro_to_analysis_software.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Piping and dplyr</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02-4-Intro_to_graphs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Making graphs</span></a>
  </div>
</li>
      </ul>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-Descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">03 Descriptive Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-Presentations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">04 Presentations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-Introduction_to_PISA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">05 Introduction to PISA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-ChisqPISA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">07 Hypothesis testing and Chi-square tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-T-testsPISA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">06 T-tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-Writing_report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">08 Writing a quantitative report</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-Assignment_3_tutorials.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">09 Assignment 3 tutorials</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-Correlation_and_regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">10 Correlation and regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-selecting_statistical_tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">11 Selecting statistical tools</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-value_of_quant.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">12 The value of quantitative methods</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/QandA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Questions and Answers</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Additional tests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A6-Bayesian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bayesian Statistics</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Appendicies</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A1-PISA_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PISA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A2-DfE_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DfE England</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A3-TIMSS_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">TIMSS, PIRLS and ICILS</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A4-Other_datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Other datasets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A5-Self_Study_Tasks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix Self Study Tasks</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#pre-reading-and-pre-session-tasks" id="toc-pre-reading-and-pre-session-tasks" class="nav-link active" data-scroll-target="#pre-reading-and-pre-session-tasks"><span class="header-section-number">1</span> Pre-reading and pre-session tasks</a>
  <ul class="collapse">
<li><a href="#pre-reading" id="toc-pre-reading" class="nav-link" data-scroll-target="#pre-reading"><span class="header-section-number">1.1</span> Pre-reading</a></li>
  <li><a href="#pre-session-task" id="toc-pre-session-task" class="nav-link" data-scroll-target="#pre-session-task"><span class="header-section-number">1.2</span> Pre-session task</a></li>
  </ul>
</li>
  <li><a href="#correlation-and-linear-regression" id="toc-correlation-and-linear-regression" class="nav-link" data-scroll-target="#correlation-and-linear-regression"><span class="header-section-number">2</span> Correlation and linear regression</a></li>
  <li>
<a href="#correlation" id="toc-correlation" class="nav-link" data-scroll-target="#correlation"><span class="header-section-number">3</span> Correlation</a>
  <ul class="collapse">
<li><a href="#other-correlation-coefficients" id="toc-other-correlation-coefficients" class="nav-link" data-scroll-target="#other-correlation-coefficients"><span class="header-section-number">3.1</span> Other correlation-coefficients</a></li>
  <li><a href="#reporting-correlations" id="toc-reporting-correlations" class="nav-link" data-scroll-target="#reporting-correlations"><span class="header-section-number">3.2</span> Reporting correlations</a></li>
  </ul>
</li>
  <li>
<a href="#regression" id="toc-regression" class="nav-link" data-scroll-target="#regression"><span class="header-section-number">4</span> Regression</a>
  <ul class="collapse">
<li><a href="#linear-models-and-regression" id="toc-linear-models-and-regression" class="nav-link" data-scroll-target="#linear-models-and-regression"><span class="header-section-number">4.1</span> Linear models and regression</a></li>
  <li><a href="#r-squared" id="toc-r-squared" class="nav-link" data-scroll-target="#r-squared"><span class="header-section-number">4.2</span> R squared</a></li>
  </ul>
</li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression"><span class="header-section-number">5</span> Multiple linear regression</a></li>
  <li><a href="#reporting-regression" id="toc-reporting-regression" class="nav-link" data-scroll-target="#reporting-regression"><span class="header-section-number">6</span> Reporting regression</a></li>
  <li><a href="#sec-z-values" id="toc-sec-z-values" class="nav-link" data-scroll-target="#sec-z-values"><span class="header-section-number">7</span> Standardising results with z-values</a></li>
  <li>
<a href="#seminar-tasks" id="toc-seminar-tasks" class="nav-link" data-scroll-target="#seminar-tasks"><span class="header-section-number">8</span> Seminar Tasks</a>
  <ul class="collapse">
<li><a href="#task-1" id="toc-task-1" class="nav-link" data-scroll-target="#task-1"><span class="header-section-number">8.1</span> Task 1</a></li>
  <li><a href="#task-2-correlation-tasks" id="toc-task-2-correlation-tasks" class="nav-link" data-scroll-target="#task-2-correlation-tasks"><span class="header-section-number">8.2</span> Task 2 Correlation tasks</a></li>
  <li><a href="#task-3-regression-tasks" id="toc-task-3-regression-tasks" class="nav-link" data-scroll-target="#task-3-regression-tasks"><span class="header-section-number">8.3</span> Task 3 Regression Tasks</a></li>
  <li><a href="#task-4-linear-regression-tasks" id="toc-task-4-linear-regression-tasks" class="nav-link" data-scroll-target="#task-4-linear-regression-tasks"><span class="header-section-number">8.4</span> Task 4 Linear regression tasks</a></li>
  </ul>
</li>
  <li>
<a href="#extentsion-tasks" id="toc-extentsion-tasks" class="nav-link" data-scroll-target="#extentsion-tasks"><span class="header-section-number">9</span> Extentsion tasks</a>
  <ul class="collapse">
<li><a href="#sec-Stoet-Geary" id="toc-sec-Stoet-Geary" class="nav-link" data-scroll-target="#sec-Stoet-Geary"><span class="header-section-number">9.1</span> Recreating Stoet and Geary’s paper</a></li>
  <li><a href="#loading-data-sets" id="toc-loading-data-sets" class="nav-link" data-scroll-target="#loading-data-sets"><span class="header-section-number">9.2</span> Loading data sets</a></li>
  <li><a href="#sec-leftjoin" id="toc-sec-leftjoin" class="nav-link" data-scroll-target="#sec-leftjoin"><span class="header-section-number">9.3</span> Linking data using <code>left_join</code></a></li>
  <li><a href="#sec-standard-stoet-geary" id="toc-sec-standard-stoet-geary" class="nav-link" data-scroll-target="#sec-standard-stoet-geary"><span class="header-section-number">9.4</span> Standardising PISA results</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">10 Correlation and regression</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><!-- Correlation 
https://docs.google.com/presentation/d/1QlXhCOaFMRyg8IJ2JczKkpjx26eS9BRi/edit#slide=id.p1--><!-- Correlation 
https://docs.google.com/presentation/d/1QlXhCOaFMRyg8IJ2JczKkpjx26eS9BRi/edit#slide=id.p1
@mikk2016relationships
--><section id="pre-reading-and-pre-session-tasks" class="level1" data-number="1"><h1 data-number="1">
<span class="header-section-number">1</span> Pre-reading and pre-session tasks</h1>
<section id="pre-reading" class="level2" data-number="1.1"><h2 data-number="1.1" class="anchored" data-anchor-id="pre-reading">
<span class="header-section-number">1.1</span> Pre-reading</h2>
</section><section id="pre-session-task" class="level2" data-number="1.2"><h2 data-number="1.2" class="anchored" data-anchor-id="pre-session-task">
<span class="header-section-number">1.2</span> Pre-session task</h2>
</section></section><section id="correlation-and-linear-regression" class="level1" data-number="2"><h1 data-number="2">
<span class="header-section-number">2</span> Correlation and linear regression</h1>
<p>In this session we will be exploring the use of <strong>linear regression</strong> to describe data and predict results. We will be looking for patterns within the PISA data sets, as well we trying to recreate some of the controversial findings from <span class="citation" data-cites="stoet2018gender">Stoet and Geary (<a href="#ref-stoet2018gender" role="doc-biblioref">2018</a>)</span> by linking <code>PISA_2018</code> data to global gender equality indices using the <code>left_join</code> function.</p>
<p>There are two types of statistics that we can create:</p>
<p><strong>Descriptive statistics</strong> describe/summarise a data set. E.g. what’s the average height of a woman, how many people called George were born in Somerset each year since 1921?</p>
<p><strong>Inferential statistics</strong> estimate something from a set of data, make generalisations about larger populations. E.g. If I know the height of a woman, can I predict her shoe size? If I meet someone called George, what is the likelihood that they were born in Somerset?</p>
<p>The first few sessions of this course taught you how to use R to perform descriptive statistics, with you finding the <code>mean</code>, <code>max</code>, <code>min</code> etc of data. Following sessions have given you a range of inferential tools, for example chi-square, t-tests and ANOVA. This session will introduce you to <em>linear regression</em> a means by which you can predict the value of a variable based on the value of another variable. Before we can start using linear regression we will introduce you to <em>correlation</em>, another type of inferential statistics.</p>
</section><section id="correlation" class="level1" data-number="3"><h1 data-number="3">
<span class="header-section-number">3</span> Correlation</h1>
<p>Correlation gives the direction and strength of the relationship between two numeric variables. For example we might see a relationship between the reading level of a student and their maths results in the UK: the better a student is at reading, typically, the higher their maths grade. Correlation allows us to describe this relation statistically:</p>
<div class="cell">
<details><summary>code</summary><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>corr_data <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span> </span>
<span id="cb1-2"><a href="#cb1-2"></a>  <span class="fu">filter</span>(CNT <span class="sc">==</span> <span class="st">"United Kingdom"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb1-3"><a href="#cb1-3"></a>  <span class="fu">select</span>(PV1MATH, PV1READ, ST004D01T)</span>
<span id="cb1-4"><a href="#cb1-4"></a></span>
<span id="cb1-5"><a href="#cb1-5"></a>corr <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(corr_data<span class="sc">$</span>PV1MATH, corr_data<span class="sc">$</span>PV1READ, <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb1-6"><a href="#cb1-6"></a>corr_est <span class="ot">&lt;-</span> <span class="fu">signif</span>(corr[[<span class="st">"estimate"</span>]],<span class="dv">4</span>)</span>
<span id="cb1-7"><a href="#cb1-7"></a></span>
<span id="cb1-8"><a href="#cb1-8"></a></span>
<span id="cb1-9"><a href="#cb1-9"></a><span class="fu">ggplot</span>(<span class="at">data =</span> corr_data, <span class="fu">aes</span>(PV1MATH, PV1READ)) <span class="sc">+</span></span>
<span id="cb1-10"><a href="#cb1-10"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span><span class="fl">0.1</span>) <span class="sc">+</span> </span>
<span id="cb1-11"><a href="#cb1-11"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb1-12"><a href="#cb1-12"></a>  <span class="fu">geom_text</span>(<span class="at">label=</span><span class="fu">paste</span>(<span class="st">"r = "</span>, corr_est), <span class="fu">aes</span>(<span class="at">x=</span><span class="dv">700</span>,<span class="at">y=</span><span class="sc">-</span><span class="fl">4.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="10-Correlation_and_regression_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The graph above shows that there is a correlation between Maths score and Reading score. This relationship is a <em>positive</em> one, i.e.&nbsp;as the reading level of an individual increases the maths grade is also likely to increase. The strength, <em>correlation coefficient</em> (<code>Pearson's r</code>) of the relationship between these two numeric fields is 0.7812. The correlation coefficient runs from -1 to +1.</p>
<ul>
<li>If the correlation coefficient (r) is negative, i.e.&nbsp;as one factor increase the other declines, the slope of the line of best-fit will be negative. E.g “The more time you spend running on a treadmill, the more calories you will burn”</li>
<li>If the correlation coefficient (r) is positive, i.e.&nbsp;as one factor increase the other increases, the slope of the line of best-fit will be positive. E.g. “As the temperature decreases, more heaters are purchased.”</li>
<li>If the correlation coefficient (r) is 0, i.e one factor increasing doesn’t impact the other factor, the slope of the line of best-fit will be flat. E.g. “the number of trees in a city has no relation to the number of chocolate bars purchased by children”</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="10-Correlation_and_regression_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>To run the correlation test in R we use the <code>cor.test</code> function:</p>
<p><code>cor.test(&lt;vector1&gt;, &lt;vector2&gt;, method = "pearson")</code></p>
<p>For our data we will be using the <code>PV1MATH</code> and <code>PV1READ</code> columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="fu">cor.test</span>(corr_data<span class="sc">$</span>PV1MATH, corr_data<span class="sc">$</span>PV1READ, <span class="at">method =</span> <span class="st">"pearson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  corr_data$PV1MATH and corr_data$PV1READ
t = 147.09, df = 13816, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.7746249 0.7876230
sample estimates:
      cor 
0.7812086 </code></pre>
</div>
</div>
<ul>
<li>
<code>df</code> the number of ways that the data can vary, the larger this number the more ways the data could have been different</li>
<li>
<code>p-value</code> significance of the result, can we dismiss the null-hypothesis that there isn’t a relationship between maths score and wealth as the p-value is less than <code>0.05</code>
</li>
<li>
<code>sample estimates</code> the strength of the relationship between the factors</li>
<li>
<code>confidence intervals</code> the upper and lower limit of where the correlation coefficient is likely to lie, with 95% confidence.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Degrees of freedom (<code>df</code>)</p>
<p>Two individuals from different countries might have a weight difference of 5 KG. So what?! But if <em>average</em> weights between <em>whole</em> populations of countries vary by 5 KG then this becomes much more interesting.</p>
<p>Roughly: Number of independent values that can vary without questioning the significance of the model. So the more <code>df</code> you have, the safer your model. Degrees of freedom can be calculated by looking at the number of values that can vary, often this is the number of observations that you have minus one – if you had just one element it wouldn’t be able to vary against anything else:</p>
<p><code>df = n - 1</code></p>
</div>
</div>
<section id="other-correlation-coefficients" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="other-correlation-coefficients">
<span class="header-section-number">3.1</span> Other correlation-coefficients</h2>
<p>When looking for correlations in data that is <em>non-parametric</em>, i.e.&nbsp;not normally distributed you could use <em>Spearman’s rank order correlation-coefficient (rho ρ)</em> rather than <em>Pearson’s r</em>. <code>cor.test(... method = "...")</code> allows you to specify the <code>method</code> used for correlation, you can set this to Spearman’s rho by writing <code>method = "spearman"</code></p>
<p>Data will need to contain continuous or ordinal variables. The Spearman correlation coefficient is based on the <em>ranked</em> values for each variable rather than the raw data. The Spearman correlation between two variables is equal to the Pearson correlation between the rank values of those two variables.</p>
<p>We want to look at the correlation between attitudes towards the learning activities in schools (<code>ATTLNACT</code>) and wealth (<code>WEALTH</code>) for females from the UK with fathers who are Cooks.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="co"># all the females who have fathers that are Cooks(!)</span></span>
<span id="cb4-2"><a href="#cb4-2"></a>sub_data <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span> </span>
<span id="cb4-3"><a href="#cb4-3"></a>                <span class="fu">filter</span>(CNT <span class="sc">==</span> <span class="st">"United Kingdom"</span>,</span>
<span id="cb4-4"><a href="#cb4-4"></a>                       ST004D01T <span class="sc">==</span> <span class="st">"Female"</span>,</span>
<span id="cb4-5"><a href="#cb4-5"></a>                       OCOD2 <span class="sc">==</span> <span class="st">"Cooks"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Graphing this data, it is unclear if it is normalised:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="fu">ggplot</span>(sub_data) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x=</span>ATTLNACT))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="10-Correlation_and_regression_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can run the <em>Shapiro-Wilk Test</em> to check for the the normality of the data, any alpha value greater than <code>0.05</code> means we can assume that the data is normally distributed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="fu">shapiro.test</span>(sub_data<span class="sc">$</span>ATTLNACT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  sub_data$ATTLNACT
W = 0.84971, p-value = 0.003354</code></pre>
</div>
</div>
<p>In this case the data <em>isn’t</em> normally distributed as <code>p &lt; 0.05</code> and we need to use a non-parametric correlation test. We need to run <em>Spearman</em> rather than <em>Pearson</em>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a><span class="fu">cor.test</span>(sub_data<span class="sc">$</span>WEALTH, sub_data<span class="sc">$</span>ATTLNACT, <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  sub_data$WEALTH and sub_data$ATTLNACT
S = 1369, p-value = 0.3097
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
0.2269763 </code></pre>
</div>
</div>
<p>The result shows no significant correlation (<code>p=0.31</code>) between wealth and attitude to school for this group of students</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>the <em>central limit theorem</em> means that when you have a sufficiently large sample you can presume that the data is normally distributed. As a rule of thumb <em>“30 is the magic number”</em>, and any samples you are studying with 30 or more data items can be treated as parametric, e.g.&nbsp;you would always use pearson when running correlation analysis on 30 or more items.</p>
</div>
</div>
<p>When dealing with non-parametric and small data sets you can also use <strong>Kendall’s Tau</strong> i.e.&nbsp;<code>cor.test(... method = "kendall")</code></p>
</section><section id="reporting-correlations" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="reporting-correlations">
<span class="header-section-number">3.2</span> Reporting correlations</h2>
<p>To interpret the correlation co-efficient of a model we can use the following table:</p>
<table class="table">
<thead><tr class="header">
<th>Correlation co-efficient</th>
<th>Relationship</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>.70 or higher</td>
<td>very strong positive</td>
</tr>
<tr class="even">
<td>.40 to .69</td>
<td>strong positive</td>
</tr>
<tr class="odd">
<td>.30 to .39</td>
<td>moderate positive</td>
</tr>
<tr class="even">
<td>.20 to .29</td>
<td>weak positive</td>
</tr>
<tr class="odd">
<td>.01 to .19</td>
<td>negligible or none</td>
</tr>
<tr class="even">
<td>0</td>
<td>no relationship</td>
</tr>
<tr class="odd">
<td>-.01 to -.19</td>
<td>negligible or none</td>
</tr>
<tr class="even">
<td>-.20 to -.29</td>
<td>weak negative</td>
</tr>
<tr class="odd">
<td>-.30 to -.39</td>
<td>moderate negative</td>
</tr>
<tr class="even">
<td>-.40 to -.69</td>
<td>strong negative</td>
</tr>
<tr class="odd">
<td>-.70 or higher</td>
<td>very strong negative</td>
</tr>
</tbody>
</table>
<p>When writing a report we might present our findings like this:</p>
<blockquote class="blockquote">
<p>There was no significant relationship between the perceived quality of sleep and its impact on Mood, <em>r</em> = -.12, <em>p</em> = .17</p>
</blockquote>
<p>or</p>
<blockquote class="blockquote">
<p>There is a significant very strong correlation between overall well-being and life satisfaction, <em>r</em> = .86, <em>p</em> = .00</p>
</blockquote>
</section></section><section id="regression" class="level1" data-number="4"><h1 data-number="4">
<span class="header-section-number">4</span> Regression</h1>
<p>Correlation allows us to see the strength of the relationship but it doesn’t allow us to <em>predict</em> what would happen if a variable changed. “When the wind blows, the trees move. When the trees move, the wind blows.” Which is it? Correlation suggests there is a link but tells us nothing about causation. To do this we need <em>regression</em>.</p>
<table class="table">
<caption>differences and similarities between correlation and regression</caption>
<colgroup>
<col style="width: 50%">
<col style="width: 49%">
</colgroup>
<thead><tr class="header">
<th>Correlation</th>
<th>Regression</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>an example of inferential statistics</td>
<td>an example of inferential statistics</td>
</tr>
<tr class="even">
<td>give direction and strength of the relationship between two (or more) numeric variables</td>
<td>give direction and strength of the relationship between two (or more) variables</td>
</tr>
<tr class="odd">
<td>Relationship between variables</td>
<td>The extent to which one variable <u>predicts</u> another</td>
</tr>
<tr class="even">
<td>Effect only (no cause)</td>
<td>Cause and effect</td>
</tr>
<tr class="odd">
<td>p(x,y) == p(y,x)</td>
<td>One way (e.g.&nbsp;education affects income differently from how income affects education)</td>
</tr>
<tr class="even">
<td>Single point/value</td>
<td>An equation that creates a best fitting line</td>
</tr>
</tbody>
</table>
<p>Regression is a way of <em>predicting</em> the value of one <em>dependent</em> variable from one or more <em>independent</em> variables by creating a hypothetical model of the relationship between them.</p>
<ul>
<li>
<strong>independent variable</strong> - the cause of the change that is independent of other variables</li>
<li>
<strong>dependent variable</strong> - the effect of the cause</li>
</ul>
<section id="linear-models-and-regression" class="level2" data-number="4.1"><h2 data-number="4.1" class="anchored" data-anchor-id="linear-models-and-regression">
<span class="header-section-number">4.1</span> Linear models and regression</h2>
<p>The model used is a <strong>linear</strong> one, therefore, we describe the relationship using the equation of a straight line. In linear regression, with one dependent and one independent variable, we use the <em>Method of Least Squares</em> to find the line of best fit. The means finding a straight line that passes as close as possible to all the points. The distance between a point and this line is called a residual. The line of best fit is the line where the sum of the residuals squared is the smallest number possible.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/method_of_least_squares.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Method of Least Squares</figcaption></figure>
</div>
<p>The line that is created can be described by the equation:</p>
<p><code>Output = Intercept + Coefficient * Input</code> <!--F-statistic = a measure of the ratio of the variation explained by the model and the variation attributable to unsystematic factors (the error of the model).--></p>
<p>Let’s use linear regression to explore the relationship between the score in maths(<code>PV1MATH</code>) and the score in reading (<code>PV1READ</code>). To build this model we use the <code>lm</code> command:</p>
<p><code>lm(&lt;dependent_var&gt; ~ &lt;independent_var&gt; , data=&lt;dataframe&gt;)</code></p>
<p>The first part defines the model we are going to explore, listing the dependent variable and separating it from the independent variable[s] with a tilde <code>~</code>. You can specify multiple independent variables by adding more plusses, but for the example here we are only going to use one. Once the model has been built we can feed it into the <code>summary(&lt;mdl&gt;)</code> command to output the results:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PV1MATH ~ PV1READ, data = PISA_2018)

Residuals:
    Min      1Q  Median      3Q     Max 
-289.48  -39.35   -0.79   38.68  341.71 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 9.617e+01  3.254e-01   295.5   &lt;2e-16 ***
PV1READ     8.003e-01  6.942e-04  1152.9   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 58.42 on 606625 degrees of freedom
  (5377 observations deleted due to missingness)
Multiple R-squared:  0.6866,    Adjusted R-squared:  0.6866 
F-statistic: 1.329e+06 on 1 and 606625 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>If you look at the <code>Coefficents:</code> table we can see that <code>PV1READ</code> is significant in explaining the outcome of the model as the p-value <code>Pr(&gt;|t|)</code> is less than 0.001 <code>&lt;2e-16 ***</code>. The null hypothesis is that one variable does not predict another, we can dismiss this. By looking at the <code>Estimate</code> we can also see by how much a <code>PV1MATH</code> grade would increase if the <code>PV1READ</code> increased by one: <code>0.8003</code>. Additionally, we have <em>R<sup>2</sup></em> value of <code>0.6866</code>, this suggests that the model is very good at explaining the value of the dependent variable, 68.7% of the variance in the <code>PV1MATH</code> grade is explained by the <code>PV1READ</code> grade.</p>
</section><section id="r-squared" class="level2" data-number="4.2"><h2 data-number="4.2" class="anchored" data-anchor-id="r-squared">
<span class="header-section-number">4.2</span> R squared</h2>
<p>With large data sets you will often find a statistically significant difference, but <em>p-values</em> should be read with caution as the larger the data set you use the more likely you are to get a low <em>p-value</em>. The actual magnitude of a significant difference might be very small. <strong>r-squared</strong> and <strong>adjusted r-squared</strong> are ways for you to report on the magnitude of a significant difference and when you report the findings from a linear model you should be looking at the <code>p</code> and the <code>R^2^</code> values. You have already met <em>R</em>, this is the correlation coefficient from earlier, <em>R<sup>2</sup></em> is this value squared:</p>
<ul>
<li>
<strong>R</strong> - The correlation between the observed values of the outcome, and the values predicted by the model.</li>
<li>
<strong>R<sup>2</sup></strong> - The proportion of variance in the dependent variable accounted for by the model.</li>
<li>
<strong>Adj. R<sup>2</sup></strong> - An estimate of R<sup>2</sup> in the population (shrinkage), often very similar to plain R<sup>2</sup>.</li>
</ul>
<!--Effect size measurements include Cohen's d, Glass' g and Pearson's r--><p>Imagine we take two experiments a) and b)</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="images/effectsize.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">(a) larger effect-size; (b) smaller effect-size from <span class="citation" data-cites="coe2002s">Coe (<a href="#ref-coe2002s" role="doc-biblioref">2002</a>)</span></figcaption></figure>
</div>
<p>Both have statistically significant results, but it’s clear that the impact of the intervention in graph a) is larger as there is less overlap between the curves, i.e.&nbsp;there is more difference between the the outcomes.</p>
<blockquote class="blockquote">
<p>if the difference were as in graph (a) it would be very significant; in graph (b), on the other hand, the difference might hardly be noticeable <span class="citation" data-cites="coe2002s">(<a href="#ref-coe2002s" role="doc-biblioref">Coe 2002, p2</a>)</span></p>
</blockquote>
<p>Different effect sizes have different meanings and there is some debate on how to interpret them, with different interpretations for different fields of research <span class="citation" data-cites="schafer2019meaningfulness">(<a href="#ref-schafer2019meaningfulness" role="doc-biblioref">Schäfer and Schwarz 2019</a>)</span></p>
<table class="table">
<caption>How to interpret effect sizes <span class="citation" data-cites="cohen1962statistical">(<a href="#ref-cohen1962statistical" role="doc-biblioref">Cohen 1962</a>)</span>
</caption>
<thead><tr class="header">
<th>Effect size value</th>
<th>Effect size</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>0.0 to 0.19</td>
<td>negligible</td>
</tr>
<tr class="even">
<td>0.2 to 0.49</td>
<td>small</td>
</tr>
<tr class="odd">
<td>0.5 to 0.79</td>
<td>medium</td>
</tr>
<tr class="even">
<td>0.8+</td>
<td>large</td>
</tr>
</tbody>
</table>
<p>You might be familiar with the Education Endowment Foundation’s <em>Teaching and Learning Toolkit</em> which outlines the <em>Impact</em> of different interventions on student learning. For example, repeating a year is seen to decrease student progress by 3 months and providing students with feedback is seen to increase student progress by 6 months. Behind the scenes they are using effect-sizes to predict the impact of educational interventions. In their model an effect-size of 0.1 is considered to have “Low impact”, but also an effect size of this magnitude is translated to 2 months progress in the Toolkit <span class="citation" data-cites="higgins2016sutton">(<a href="#ref-higgins2016sutton" role="doc-biblioref">Higgins et al. 2016, 5</a>)</span>.</p>
</section></section><section id="multiple-linear-regression" class="level1" data-number="5"><h1 data-number="5">
<span class="header-section-number">5</span> Multiple linear regression</h1>
<p>So far we have looked at the impact of a single independent variable on a single dependent variable. We are now going to look at building models that contain multiple independent variables, of both continuous and discrete values. For example, we might want to see how Gender (<code>ST004D01T</code>) and Reading score (<code>PV1READ</code>) help predict a maths score. To add extra independent variables, use the plus symbol <code>+</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a>mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(PV1MATH <span class="sc">~</span> PV1READ <span class="sc">+</span> gender, </span>
<span id="cb11-2"><a href="#cb11-2"></a>          <span class="at">data=</span>PISA_2018 <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">gender =</span> ST004D01T))</span>
<span id="cb11-3"><a href="#cb11-3"></a><span class="fu">summary</span>(mdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PV1MATH ~ PV1READ + gender, data = PISA_2018 %&gt;% 
    rename(gender = ST004D01T))

Residuals:
    Min      1Q  Median      3Q     Max 
-289.42  -38.14   -0.68   37.51  356.24 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 7.405e+01  3.368e-01   219.8   &lt;2e-16 ***
PV1READ     8.180e-01  6.808e-04  1201.6   &lt;2e-16 ***
genderMale  2.798e+01  1.471e-01   190.2   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 56.75 on 606622 degrees of freedom
  (5379 observations deleted due to missingness)
Multiple R-squared:  0.7043,    Adjusted R-squared:  0.7043 
F-statistic: 7.223e+05 on 2 and 606622 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Both independent variables are significant (<code>p&lt;0.001</code>), and the <em>R<sup>2</sup></em> of the model is high at <code>0.7043</code>, this model explains 70% of the variance in Maths grade. Looking at the Estimates, we see both independent variables presented, this means we can read them as if the other factor has been <em>controlled</em> for; e.g.&nbsp;what is the impact of reading score if the impact of gender has been taken into consideration. <code>PV1READ</code> is <code>0.818</code>, meaning for an increase of 1 in this score, the <code>PV1MATH</code> grade would increase by <code>0.818</code>. Gender is different, this is a <em>nominal</em> field, being either Male or Female, and <code>genderMale</code> is shown in the coefficients table. This means that the model has taken <code>gender == Female</code> as the base state, and modeled what happens if the gender were to change to Male. Interestingly, it suggests that when controlling for the reading grade, e.g.&nbsp;comparing females and males of the same reading score, males would do <code>27.98</code> points better in their <code>PV1MATH</code> grade than females(!). We’ll be exploring these gender differences a little further in section <a href="#sec-Stoet-Geary">Section&nbsp;9.1</a>.</p>
</section><section id="reporting-regression" class="level1" data-number="6"><h1 data-number="6">
<span class="header-section-number">6</span> Reporting regression</h1>
<p>When reporting linear regression we should make note of the <em>estimate</em> (also known as beta <em>β-value</em>) of each factor along with their <em>p-values</em>. We need to know the <em>R<sup>2</sup></em> and <em>p-value</em> for the model as well as the <em>F-statistic</em> and the <em>degrees of freedom</em>. We can then construct a few sentences to explain our findings <span class="citation" data-cites="statology2021">(<a href="#ref-statology2021" role="doc-biblioref">Zach 2021</a>)</span>:</p>
<blockquote class="blockquote">
<p>Simple linear regression was used to test if [predictor variable] significantly predicted [response variable]. The overall regression was statistically significant (R2 = [R2 value], F(df regression, df residual) = [F-value], p = [p-value]). It was found that [predictor variable] significantly predicted [response variable] (β = [β-value], p = [p-value]).</p>
</blockquote>
<p>For the example above, this would be:</p>
<blockquote class="blockquote">
<p>Simple linear regression was used to test if a student reading grade significantly predicted student maths grade. The overall regression was statistically significant (R<sup>2</sup> = 0.6866, F(1,606625) = 1329000, p = &lt;0.001). It was found that reading grade significantly predicted maths grade (β = 0.8003, p = &lt;0.001).</p>
</blockquote>
<p>Alternatively, you could make use of the <code>easystats</code> package which will do most of the heavy lifting for you:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a><span class="fu">library</span>(easystats)</span>
<span id="cb13-2"><a href="#cb13-2"></a>mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(PV1MATH <span class="sc">~</span> PV1READ, <span class="at">data=</span>PISA_2018)</span>
<span id="cb13-3"><a href="#cb13-3"></a><span class="fu">summary</span>(mdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = PV1MATH ~ PV1READ, data = PISA_2018)

Residuals:
    Min      1Q  Median      3Q     Max 
-289.48  -39.35   -0.79   38.68  341.71 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 9.617e+01  3.254e-01   295.5   &lt;2e-16 ***
PV1READ     8.003e-01  6.942e-04  1152.9   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 58.42 on 606625 degrees of freedom
  (5377 observations deleted due to missingness)
Multiple R-squared:  0.6866,    Adjusted R-squared:  0.6866 
F-statistic: 1.329e+06 on 1 and 606625 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="fu">report</span>(mdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>We fitted a linear model (estimated using OLS) to predict PV1MATH with PV1READ
(formula: PV1MATH ~ PV1READ). The model explains a statistically significant
and substantial proportion of variance (R2 = 0.69, F(1, 606625) = 1.33e+06, p &lt;
.001, adj. R2 = 0.69). The model's intercept, corresponding to PV1READ = 0, is
at 96.17 (95% CI [95.53, 96.80], t(606625) = 295.53, p &lt; .001). Within this
model:

  - The effect of PV1READ is statistically significant and positive (beta = 0.80,
95% CI [0.80, 0.80], t(606625) = 1152.88, p &lt; .001; Std. beta = 0.83, 95% CI
[0.83, 0.83])

Standardized parameters were obtained by fitting the model on a standardized
version of the dataset. 95% Confidence Intervals (CIs) and p-values were
computed using a Wald t-distribution approximation.</code></pre>
</div>
</div>
</section><section id="sec-z-values" class="level1" data-number="7"><h1 data-number="7">
<span class="header-section-number">7</span> Standardising results with z-values</h1>
<p>When we are trying to compare data between countries, our results can be heavily skewed by the overall performance of a country. For example, imagine we have country <em>A</em> and country <em>U</em>. Students in country <em>A</em> generally get high grades with a very high standard deviation, whilst students in country <em>U</em> generally get very low grades with a very low standard deviation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">sex=</span><span class="fu">c</span>(<span class="st">"M"</span>,<span class="st">"M"</span>,<span class="st">"M"</span>,<span class="st">"F"</span>,<span class="st">"F"</span>,<span class="st">"F"</span>,<span class="st">"M"</span>,<span class="st">"M"</span>,<span class="st">"M"</span>,<span class="st">"F"</span>,<span class="st">"F"</span>,<span class="st">"F"</span>),</span>
<span id="cb17-2"><a href="#cb17-2"></a>           <span class="at">country=</span><span class="fu">c</span>(<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"U"</span>,<span class="st">"U"</span>,<span class="st">"U"</span>,<span class="st">"U"</span>,<span class="st">"U"</span>,<span class="st">"U"</span>),</span>
<span id="cb17-3"><a href="#cb17-3"></a>           <span class="at">grade=</span><span class="fu">c</span>(<span class="dv">100</span>,<span class="dv">87</span>,<span class="dv">98</span>,<span class="dv">95</span>,<span class="dv">82</span>,<span class="dv">90</span>,<span class="dv">10</span>,<span class="dv">8</span>,<span class="dv">9</span>,<span class="dv">12</span>,<span class="dv">10</span>,<span class="dv">11</span>))</span>
<span id="cb17-4"><a href="#cb17-4"></a></span>
<span id="cb17-5"><a href="#cb17-5"></a>df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(country, sex) <span class="sc">%&gt;%</span> </span>
<span id="cb17-6"><a href="#cb17-6"></a>  <span class="fu">mutate</span>(<span class="at">mgrade =</span> <span class="fu">mean</span>(grade)) <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="#cb17-7"></a>  <span class="fu">group_by</span>(country) <span class="sc">%&gt;%</span></span>
<span id="cb17-8"><a href="#cb17-8"></a>  <span class="fu">mutate</span>(<span class="at">meancountry =</span> <span class="fu">mean</span>(grade),</span>
<span id="cb17-9"><a href="#cb17-9"></a>         <span class="at">sdgrade =</span> <span class="fu">sd</span>(grade)) <span class="sc">%&gt;%</span></span>
<span id="cb17-10"><a href="#cb17-10"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> sex, <span class="at">values_from =</span> mgrade) <span class="sc">%&gt;%</span></span>
<span id="cb17-11"><a href="#cb17-11"></a>  <span class="fu">summarise</span>(<span class="at">M_max =</span> <span class="fu">max</span>(M, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb17-12"><a href="#cb17-12"></a>            <span class="st">`</span><span class="at">F_max</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">max</span>(<span class="st">`</span><span class="at">F</span><span class="st">`</span>, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb17-13"><a href="#cb17-13"></a>            <span class="at">difference =</span> M_max<span class="sc">-</span><span class="st">`</span><span class="at">F_max</span><span class="st">`</span>,</span>
<span id="cb17-14"><a href="#cb17-14"></a>            <span class="at">sd =</span> <span class="fu">max</span>(sdgrade),</span>
<span id="cb17-15"><a href="#cb17-15"></a>            <span class="at">mean =</span> <span class="fu">max</span>(meancountry))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  country M_max F_max difference    sd  mean
  &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 A          95    89          6  6.90    92
2 U           9    11         -2  1.41    10</code></pre>
</div>
</div>
<p>If we look for the difference in grades between females and males in country <em>A</em> we might see a massive difference, whilst female and male students in country <em>U</em> have a much smaller difference. We might then conclude that country <em>U</em> is more equitable. But in reality, because the standard deviation in country <em>U</em> is so small, the relative difference between females and males is actually larger than that seen in country <em>A</em>! To get around this problem, when dealing with situations like this, we can use <em>standardised</em>, or <em>z</em>, values. These z-values would be a student’s grade in relation to the standard deviation of all of that country’s grades.</p>
<p>To calculate the standardised <em>z-value</em> for each entry, we use:</p>
<p><code>(entry - mean of grouping) / sd of grouping</code></p>
<p>For example, for the first Male student in country A who scored 100 points, we would calculate</p>
<p><code>(100 - 92) / 6.899 = 1.16</code></p>
<p>This shows that this student got 1.16 standard deviations more than the mean of the population. For the first female in country U, we would calculate:</p>
<p><code>(12 - 10) / 1.141 = 1.75</code></p>
<p>These two values are then directly comparable, the first males in country A is relatively closer to the mean grade of country A, than the first female in country U. How does this work out for the whole country? Going back to whether sex had a greater impact on results in country A or country U we can calculate the z-values for each student by using the <code><a href="https://rdrr.io/r/base/scale.html">scale()</a></code> command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a>dfz <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(country) <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2"></a>  <span class="fu">mutate</span>(<span class="at">zgrade =</span> <span class="fu">scale</span>(grade))</span>
<span id="cb19-3"><a href="#cb19-3"></a>dfz</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 4
# Groups:   country [2]
   sex   country grade zgrade[,1]
   &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt;      &lt;dbl&gt;
 1 M     A         100      1.16 
 2 M     A          87     -0.725
 3 M     A          98      0.870
 4 F     A          95      0.435
 5 F     A          82     -1.45 
 6 F     A          90     -0.290
 7 M     U          10      0    
 8 M     U           8     -1.41 
 9 M     U           9     -0.707
10 F     U          12      1.41 
11 F     U          10      0    
12 F     U          11      0.707</code></pre>
</div>
</div>
<p>We can then group by country and by sex and see how the <code>mean</code> z-value varies</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a>dfz <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2"></a>  <span class="fu">group_by</span>(country, sex) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3"></a>  <span class="fu">summarise</span>(<span class="at">mean_zgrade =</span> <span class="fu">mean</span>(zgrade))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
# Groups:   country [2]
  country sex   mean_zgrade
  &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt;
1 A       F          -0.435
2 A       M           0.435
3 U       F           0.707
4 U       M          -0.707</code></pre>
</div>
</div>
<p>We can clearly see that the grades in country <em>A</em> are relatively closer to the mean of country <em>A</em>, than the grades in country <em>U</em>, meaning that there is less variation in country <em>A</em>.</p>
<!--
### Science self efficacy

We can also try and recreate fig. 4 from @stoet2018gender, looking at how self-efficacy in science `SCIEEFF` varies given the GGGI `Overall.Score`:


::: {.cell}

:::

::: {.cell}

:::


> We used the UNESCO graduation data (available via http://data.uis.unesco.org) labelled "Distribution of tertiary graduates"

::: question
1.  


::: {.cell}

:::


2.  


::: {.cell}

:::


3.  calculate a new field, then conduct a


::: {.cell}

:::

:::

## Logistic regression

Sometimes the dependent variable will be *boolean*, that is a field that can only have two values, e.g. `True/False`, `Yes/No`, `High/Low`, etc. Unfortunately we can't use the linear model to do th


::: {.cell}

:::

::: {.cell}

:::


-->
</section><section id="seminar-tasks" class="level1" data-number="8"><h1 data-number="8">
<span class="header-section-number">8</span> Seminar Tasks</h1>
<section id="task-1" class="level2" data-number="8.1"><h2 data-number="8.1" class="anchored" data-anchor-id="task-1">
<span class="header-section-number">8.1</span> Task 1</h2>
<div class="question">
<p>Group discussion:</p>
<ul>
<li>What were the most important findings from Stoet and Geary’s paper?</li>
<li>How trustworthy are the results?</li>
<li>What do these results mean for gender equality in STEM?</li>
</ul>
<ol type="1">
<li>What are <em>Spearman’s Rho</em> and <em>Pearson’s r</em>? When might you use one rather than the other?</li>
</ol>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="co">#&gt; When the data you use has outliers or is not </span></span>
<span id="cb23-2"><a href="#cb23-2"></a><span class="co">#&gt; normally distributed (non-parametric) you should use Spearman's Rho</span></span>
<span id="cb23-3"><a href="#cb23-3"></a><span class="co">#&gt; you can test this by checking that shapiro.test p &gt;0.05</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="2" type="1">
<li>Identify dependent and independent variables in the following scenarios and select the most appropriate statistical test (from all that you have learnt) for the analysis.</li>
</ol>
<ul>
<li>The government is trying to understand which groups of people have been affected by a pandemic. They have data on healthcare professionals, education professionals and train drivers and the number of days taken off ill in the last 6 months.</li>
<li>A cigarette company, working in a country that still allows cigarette advertising(!), wants to work out which groups in society are not currently smoking that many cigarettes. They want to find out if city dwellers are more likely to smoke than people living in the countryside.</li>
<li>A netball team is trying to work out how likely their players are to get injured in a season. They have data on the number of injuries per player and the number of minutes each player has been playing netball.</li>
<li>A country is trying to find out whether girls or boys are better behaved in schools. They have access to school databases that record the number of bad behaviour slips for each student.</li>
</ul>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="co"># The government is trying to understand which groups of people have been affected by a pandemic. They have data on healthcare professionals, education professionals and train drivers and the number of days taken off ill in the last 6 months.</span></span>
<span id="cb24-2"><a href="#cb24-2"></a><span class="co">#&gt; Dependendent: days off ill</span></span>
<span id="cb24-3"><a href="#cb24-3"></a><span class="co">#&gt; Independent: job role</span></span>
<span id="cb24-4"><a href="#cb24-4"></a><span class="co">#&gt; Suggested model: ANOVA to check if there are differences between jobs</span></span>
<span id="cb24-5"><a href="#cb24-5"></a></span>
<span id="cb24-6"><a href="#cb24-6"></a><span class="co"># A cigarette company, working in a country that still allows cigarette advertising(!), wants to work out which groups in society are not currently smoking that many cigarettes. They want to find out if city dwellers are more likely to smoke than people living in the countryside.</span></span>
<span id="cb24-7"><a href="#cb24-7"></a><span class="co">#&gt; Dependent: Smoker / Non Smoker</span></span>
<span id="cb24-8"><a href="#cb24-8"></a><span class="co">#&gt; Independent: City / Countryside residence</span></span>
<span id="cb24-9"><a href="#cb24-9"></a><span class="co">#&gt; Suggested model: Chi-square</span></span>
<span id="cb24-10"><a href="#cb24-10"></a></span>
<span id="cb24-11"><a href="#cb24-11"></a><span class="co"># A netball team is trying to work out how likely their players are to get injured in a season. They have data on the number of injuries per player and the number of minutes each player has been playing netball.</span></span>
<span id="cb24-12"><a href="#cb24-12"></a><span class="co">#&gt; Dependent: injuries</span></span>
<span id="cb24-13"><a href="#cb24-13"></a><span class="co">#&gt; Independent: time on court</span></span>
<span id="cb24-14"><a href="#cb24-14"></a><span class="co">#&gt; Suggested model: Linear model/regression</span></span>
<span id="cb24-15"><a href="#cb24-15"></a></span>
<span id="cb24-16"><a href="#cb24-16"></a><span class="co"># A country is trying to find out whether girls or boys are better behaved in schools. They have access to school databases that record the number of bad behaviour slips for each student.</span></span>
<span id="cb24-17"><a href="#cb24-17"></a><span class="co">#&gt; Dependent: behaviour slips</span></span>
<span id="cb24-18"><a href="#cb24-18"></a><span class="co">#&gt; Independent: Gender (Girls/Boys)</span></span>
<span id="cb24-19"><a href="#cb24-19"></a><span class="co">#&gt; Suggested model: t-test</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="3" type="1">
<li>Interpret this correlation coefficient between the Index of economic, social and cultural status <code>ESCS</code> and Family wealth <code>WEALTH</code>
</li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  PISA_2018$ESCS and PISA_2018$WEALTH
t = 751.83, df = 595193, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.6966207 0.6992267
sample estimates:
     cor 
0.697926 </code></pre>
</div>
</div>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="co">#&gt; The Index of economic, social and cultural status `ESCS` is strongly</span></span>
<span id="cb26-2"><a href="#cb26-2"></a><span class="co">#&gt; correlated with Family wealth `WEALTH`, with a correlation coefficient</span></span>
<span id="cb26-3"><a href="#cb26-3"></a><span class="co">#&gt; of 0.697926. This model is signficant with a p-value of &lt; 0.001</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="4" type="1">
<li>Interpret this linear model based on the FBI’s 2006 crime statistics. It explores the relationship between size of population (1,000s) and the number of murders (units)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>:</li>
</ol>
<table class="table">
<thead><tr class="header">
<th></th>
<th>Estimate</th>
<th>Std. Error</th>
<th>t value</th>
<th>Pr(&gt;|t|)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>-0.726</td>
<td>0.089</td>
<td>-8.191</td>
<td>&lt;2e-16 ***</td>
</tr>
<tr class="even">
<td>Pop_thou</td>
<td>0.103</td>
<td>0.001</td>
<td>145.932</td>
<td>&lt;2e-16 ***</td>
</tr>
</tbody>
</table>
<p><em>Adj R<sup>2</sup></em> 0.721</p>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="co">#&gt; The model is pretty good at explaining the variance, The Adj. R2</span></span>
<span id="cb27-2"><a href="#cb27-2"></a><span class="co">#&gt; shows that population explains 72% of the variance in murders.</span></span>
<span id="cb27-3"><a href="#cb27-3"></a><span class="co">#&gt; The model is significant as p &lt; 0.001. For every increase in </span></span>
<span id="cb27-4"><a href="#cb27-4"></a><span class="co">#&gt; population of 1000 people, the model predicts another 0.1 deaths.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="5" type="1">
<li>Work out the correlation between a country’s mean female science grade and mean male science grade. Should you use <em>Spearman’s Rho</em> or <em>Pearson’s r</em> in your model? Why?</li>
</ol>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a>df <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(CNT, ST004D01T) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">maths =</span> <span class="fu">mean</span>(PV1MATH))</span>
<span id="cb28-2"><a href="#cb28-2"></a></span>
<span id="cb28-3"><a href="#cb28-3"></a>maths_male   <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ST004D01T <span class="sc">==</span> <span class="st">"Male"</span>)</span>
<span id="cb28-4"><a href="#cb28-4"></a>maths_female <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ST004D01T <span class="sc">==</span> <span class="st">"Female"</span>)</span>
<span id="cb28-5"><a href="#cb28-5"></a></span>
<span id="cb28-6"><a href="#cb28-6"></a><span class="fu">cor.test</span>(maths_male<span class="sc">$</span>maths, maths_female<span class="sc">$</span>maths)</span>
<span id="cb28-7"><a href="#cb28-7"></a></span>
<span id="cb28-8"><a href="#cb28-8"></a><span class="co">#&gt; you should use Pearson as the shapiro wilkes test has a p-vale &gt; 0.05</span></span>
<span id="cb28-9"><a href="#cb28-9"></a></span>
<span id="cb28-10"><a href="#cb28-10"></a><span class="fu">shapiro.test</span>(maths_female<span class="sc">$</span>maths)</span>
<span id="cb28-11"><a href="#cb28-11"></a><span class="co">#&gt; p-value = 0.1727</span></span>
<span id="cb28-12"><a href="#cb28-12"></a></span>
<span id="cb28-13"><a href="#cb28-13"></a><span class="fu">shapiro.test</span>(maths_male<span class="sc">$</span>maths)</span>
<span id="cb28-14"><a href="#cb28-14"></a><span class="co">#&gt; p-value = 0.1414</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="6" type="1">
<li>Create a linear model to explore the relationship between the time spent in science lessons (<code>SMINS</code>) and the grade in science (<code>PV1SCIE</code>)</li>
</ol>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a>mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(PV1SCIE <span class="sc">~</span> SMINS, <span class="at">data =</span> PISA_2018)</span>
<span id="cb29-2"><a href="#cb29-2"></a><span class="fu">summary</span>(mdl)</span>
<span id="cb29-3"><a href="#cb29-3"></a></span>
<span id="cb29-4"><a href="#cb29-4"></a><span class="co">#&gt; For every extra minute spent learning science, </span></span>
<span id="cb29-5"><a href="#cb29-5"></a><span class="co">#&gt; there is a grade increase of 0.07, </span></span>
<span id="cb29-6"><a href="#cb29-6"></a><span class="co">#&gt; SMINS is a significant predictor p &lt;2e-16 ***, </span></span>
<span id="cb29-7"><a href="#cb29-7"></a><span class="co">#&gt; but the overall model has a very low R squared value of 0.01625</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Add the student maths score <code>PV1MATH</code> this model, how does this change the outcome?</p>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a>mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(PV1SCIE <span class="sc">~</span> SMINS <span class="sc">+</span> PV1MATH, <span class="at">data =</span> PISA_2018)</span>
<span id="cb30-2"><a href="#cb30-2"></a><span class="fu">summary</span>(mdl)</span>
<span id="cb30-3"><a href="#cb30-3"></a></span>
<span id="cb30-4"><a href="#cb30-4"></a><span class="co">#&gt; For every extra minute spent learning science each week, </span></span>
<span id="cb30-5"><a href="#cb30-5"></a><span class="co">#&gt; there is now a grade increase of only 0.015, </span></span>
<span id="cb30-6"><a href="#cb30-6"></a><span class="co">#&gt; i.e. when controlling for maths outcomes, time in science </span></span>
<span id="cb30-7"><a href="#cb30-7"></a><span class="co">#&gt; lessons explains less of the overall science grade. </span></span>
<span id="cb30-8"><a href="#cb30-8"></a><span class="co">#&gt; Both factors remain significant and the overall model </span></span>
<span id="cb30-9"><a href="#cb30-9"></a><span class="co">#&gt; now has a very high R squared value of 0.6974</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="7" type="1">
<li>Load the school level data set for 2018 (file <a href="https://drive.google.com/file/d/1ZJkiIGkVfBdRupTVxbaRQ1fwOZr_RV8O/view?usp=share_link">here</a>) and explore the fields.</li>
</ol>
<p>Using a linear model, how do “Shortage of educational staff” <code>STAFFSHORT</code> and “Shortage of educational material” <code>EDUSHORT</code> relate to “Student behaviour hindering learning” <code>STUBEHA</code></p>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a>mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(STUBEHA <span class="sc">~</span> STAFFSHORT <span class="sc">+</span> EDUSHORT, <span class="at">data=</span>PISA_2018_school)</span>
<span id="cb31-2"><a href="#cb31-2"></a><span class="fu">summary</span>(mdl)</span>
<span id="cb31-3"><a href="#cb31-3"></a></span>
<span id="cb31-4"><a href="#cb31-4"></a><span class="co">#&gt; STAFFSHORT has a slightly larger estimate, 0.214186, than EDUSHORT, 0.17148.</span></span>
<span id="cb31-5"><a href="#cb31-5"></a><span class="co">#&gt; This means as staff and educational resource shortages increase, so does</span></span>
<span id="cb31-6"><a href="#cb31-6"></a><span class="co">#&gt; student behaviour hindering learning.</span></span>
<span id="cb31-7"><a href="#cb31-7"></a><span class="co">#&gt; Both factors are significant p &lt;2e-16 ***</span></span>
<span id="cb31-8"><a href="#cb31-8"></a><span class="co">#&gt; The effect size of the overall model is low, at 0.08346</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Adjust the model to incorporate the percentage of boys in a school (see <code>SC002Q01TA</code> and <code>SCHSIZE</code>), what difference does this make?</p>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a>tbl_beh_predict <span class="ot">&lt;-</span> PISA_2018_school <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="#cb32-2"></a>  <span class="fu">mutate</span>(<span class="at">boy_per =</span> <span class="dv">100</span> <span class="sc">*</span> SC002Q01TA <span class="sc">/</span> SCHSIZE)</span>
<span id="cb32-3"><a href="#cb32-3"></a></span>
<span id="cb32-4"><a href="#cb32-4"></a>mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(STUBEHA <span class="sc">~</span> STAFFSHORT <span class="sc">+</span> EDUSHORT <span class="sc">+</span> boy_per, <span class="at">data=</span>tbl_beh_predict)</span>
<span id="cb32-5"><a href="#cb32-5"></a><span class="fu">summary</span>(mdl)</span>
<span id="cb32-6"><a href="#cb32-6"></a></span>
<span id="cb32-7"><a href="#cb32-7"></a><span class="co">#&gt; adding percentage of boys to the model increases the effect size 0.09553,</span></span>
<span id="cb32-8"><a href="#cb32-8"></a><span class="co">#&gt; albeit, still a small one.</span></span>
<span id="cb32-9"><a href="#cb32-9"></a><span class="co">#&gt; when controlling for boy_per the estimate of staff shortages</span></span>
<span id="cb32-10"><a href="#cb32-10"></a><span class="co">#&gt; decreases slightly, and the estimate of educational shortages</span></span>
<span id="cb32-11"><a href="#cb32-11"></a><span class="co">#&gt; increases. The estimate of boy_per is significant, for every </span></span>
<span id="cb32-12"><a href="#cb32-12"></a><span class="co">#&gt; one percent increase in boys in a school, student behaviour</span></span>
<span id="cb32-13"><a href="#cb32-13"></a><span class="co">#&gt; hindering learning increases by 0.005, this model shows an all </span></span>
<span id="cb32-14"><a href="#cb32-14"></a><span class="co">#&gt; girls school would likely have a student behaviour hindering</span></span>
<span id="cb32-15"><a href="#cb32-15"></a><span class="co">#&gt; learning value 0.5 lower than an all boys school!</span></span>
<span id="cb32-16"><a href="#cb32-16"></a><span class="co">#&gt; it'd be worth double checking to see if boy_per is parametric</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>How does the explanatory value of this model change if you only look at schools in the UK?</p>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a>mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(STUBEHA <span class="sc">~</span> STAFFSHORT <span class="sc">+</span> EDUSHORT <span class="sc">+</span> boy_per, </span>
<span id="cb33-2"><a href="#cb33-2"></a>          <span class="at">data=</span>tbl_beh_predict <span class="sc">%&gt;%</span> <span class="fu">filter</span>(CNT <span class="sc">==</span> <span class="st">"United Kingdom"</span>))</span>
<span id="cb33-3"><a href="#cb33-3"></a><span class="fu">summary</span>(mdl)</span>
<span id="cb33-4"><a href="#cb33-4"></a></span>
<span id="cb33-5"><a href="#cb33-5"></a><span class="co">#&gt; for the UK the effect size is larger at 0.1686, more of the variance of</span></span>
<span id="cb33-6"><a href="#cb33-6"></a><span class="co">#&gt; STUBEHA is explained by this model than for other countries</span></span>
<span id="cb33-7"><a href="#cb33-7"></a><span class="co">#&gt; educational resource shortages have a negative impact on STUBEHA, </span></span>
<span id="cb33-8"><a href="#cb33-8"></a><span class="co">#&gt; albeit with a very small estimate -0.003519</span></span>
<span id="cb33-9"><a href="#cb33-9"></a><span class="co">#&gt; staff shortages have a bigger impact that other countries, with an</span></span>
<span id="cb33-10"><a href="#cb33-10"></a><span class="co">#&gt; estimate of 0.396835</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="8" type="1">
<li>Using <code>left_join</code> (see <a href="#sec-leftjoin">Section&nbsp;9.3</a>), link each student record in <code>PISA_2018</code> to their school details (file <a href="https://drive.google.com/file/d/1ZJkiIGkVfBdRupTVxbaRQ1fwOZr_RV8O/view?usp=share_link">here</a>). You will need need to <code>select</code> a subset of the school table to cover: <code>CNT, CNTSCHID, SC016Q02TA, SC156Q03HA, SC156Q04HA, SC154Q01HA,</code> <code>SC154Q02WA, SC154Q05WA, SC154Q08WA, SC154Q09HA, STRATIO, CLSIZE,</code> <code>EDUSHORT, STAFFSHORT, STUBEHA</code>
</li>
</ol>
<div class="cell">
<details><summary>left_join code</summary><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a><span class="co">#&gt; SC016Q02TA   Percentage of total funding for school year from: Student fees or school charges paid by parents</span></span>
<span id="cb34-2"><a href="#cb34-2"></a><span class="co">#&gt; SC156Q03HA   At school: A programme to use digital devices for teaching and learning in specific subjects</span></span>
<span id="cb34-3"><a href="#cb34-3"></a><span class="co">#&gt; SC156Q04HA   At school: Regular discussions with teaching staff about the use of digital devices for pedagogical purposes</span></span>
<span id="cb34-4"><a href="#cb34-4"></a><span class="co">#&gt; SC154Q01HA   School's use of assessments of students: To guide students' learning</span></span>
<span id="cb34-5"><a href="#cb34-5"></a><span class="co">#&gt; SC154Q02WA   School's use of assessments of students: To inform parents about their child's progress</span></span>
<span id="cb34-6"><a href="#cb34-6"></a><span class="co">#&gt; SC154Q05WA   School's use of assessments of students: To compare the school to &lt;district or national&gt; performance</span></span>
<span id="cb34-7"><a href="#cb34-7"></a><span class="co">#&gt; SC154Q08WA   School's use of assessments of students: To identify aspects of instruction or the curriculum that could be improved</span></span>
<span id="cb34-8"><a href="#cb34-8"></a><span class="co">#&gt; SC154Q09HA   School's use of assessments of students: To adapt teaching to the students' needs</span></span>
<span id="cb34-9"><a href="#cb34-9"></a><span class="co">#&gt; STRATIO  Student-Teacher ratio</span></span>
<span id="cb34-10"><a href="#cb34-10"></a><span class="co">#&gt; CLSIZE   Class Size (cheating here slightly as this is a nominal field which roughly maps to the continuous)</span></span>
<span id="cb34-11"><a href="#cb34-11"></a><span class="co">#&gt; EDUSHORT Shortage of educational material (WLE)</span></span>
<span id="cb34-12"><a href="#cb34-12"></a><span class="co">#&gt; STAFFSHORT   Shortage of educational staff (WLE)</span></span>
<span id="cb34-13"><a href="#cb34-13"></a><span class="co">#&gt; STUBEHA  Student behaviour hindering learning (WLE)</span></span>
<span id="cb34-14"><a href="#cb34-14"></a></span>
<span id="cb34-15"><a href="#cb34-15"></a>PISA_2018_stusch <span class="ot">&lt;-</span> </span>
<span id="cb34-16"><a href="#cb34-16"></a>  <span class="fu">left_join</span>(PISA_2018 <span class="sc">%&gt;%</span> <span class="fu">select</span>(CNT, CNTSCHID, ST004D01T, WEALTH, </span>
<span id="cb34-17"><a href="#cb34-17"></a>                                 ESCS, PV1SCIE, PV1MATH, PV1READ), </span>
<span id="cb34-18"><a href="#cb34-18"></a>             PISA_2018_school <span class="sc">%&gt;%</span> </span>
<span id="cb34-19"><a href="#cb34-19"></a>              <span class="fu">select</span>(CNT, CNTSCHID, SC016Q02TA, SC156Q03HA, SC156Q04HA,</span>
<span id="cb34-20"><a href="#cb34-20"></a>                     SC154Q01HA, SC154Q02WA, SC154Q05WA, SC154Q08WA,</span>
<span id="cb34-21"><a href="#cb34-21"></a>                     SC154Q09HA, STRATIO, CLSIZE, EDUSHORT, STAFFSHORT, STUBEHA))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Using a linear model, find out how well the student teacher ratio <code>STRATIO</code> in a school predicts the <code>mean</code> maths achievement <code>PV1MATH</code> in that school. <strong>HINT</strong>: you need one row for each school, so use summarise with unique on <code>STRATIO</code> and mean on <code>PV1MATH</code>:</p>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a>stu_tch_mat <span class="ot">&lt;-</span> PISA_2018_stusch <span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a href="#cb35-2"></a>  <span class="fu">group_by</span>(CNTSCHID) <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3"></a>  <span class="fu">summarise</span>(<span class="at">stu_tch_rat =</span> <span class="fu">unique</span>(STRATIO),</span>
<span id="cb35-4"><a href="#cb35-4"></a>            <span class="at">maths =</span> <span class="fu">mean</span>(PV1MATH))</span>
<span id="cb35-5"><a href="#cb35-5"></a></span>
<span id="cb35-6"><a href="#cb35-6"></a>mdl_stu_tch_mat <span class="ot">&lt;-</span> <span class="fu">lm</span>(maths <span class="sc">~</span> stu_tch_rat, <span class="at">data=</span>stu_tch_mat)</span>
<span id="cb35-7"><a href="#cb35-7"></a><span class="fu">summary</span>(mdl_stu_tch_mat)</span>
<span id="cb35-8"><a href="#cb35-8"></a></span>
<span id="cb35-9"><a href="#cb35-9"></a><span class="co">#&gt; it's significant p &lt;2e-16 ***, but with a very low </span></span>
<span id="cb35-10"><a href="#cb35-10"></a><span class="co">#&gt; estimates/betas, i.e. one extra student per teacher </span></span>
<span id="cb35-11"><a href="#cb35-11"></a><span class="co">#&gt; decreases the maths score by just 1.3 points, </span></span>
<span id="cb35-12"><a href="#cb35-12"></a><span class="co">#&gt; additionally the R squared value is low 0.02499 </span></span>
<span id="cb35-13"><a href="#cb35-13"></a><span class="co">#&gt; this is "low impact" in the EEF toolkit</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Adjust the linear model used above to incorporate <code>STUBEHA</code> “Student behaviour hindering learning” in addition to the student teacher ratio:</p>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a>stu_tch_mat_bev <span class="ot">&lt;-</span> PISA_2018_stusch <span class="sc">%&gt;%</span> </span>
<span id="cb36-2"><a href="#cb36-2"></a>  <span class="fu">group_by</span>(CNTSCHID) <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3"></a>  <span class="fu">summarise</span>(<span class="at">stu_tch_rat =</span> <span class="fu">unique</span>(STRATIO),</span>
<span id="cb36-4"><a href="#cb36-4"></a>            <span class="at">behaviour =</span> <span class="fu">unique</span>(STUBEHA),</span>
<span id="cb36-5"><a href="#cb36-5"></a>            <span class="at">maths =</span> <span class="fu">mean</span>(PV1MATH))</span>
<span id="cb36-6"><a href="#cb36-6"></a></span>
<span id="cb36-7"><a href="#cb36-7"></a><span class="co">#&gt; max(stu_tch_mat_bev$behaviour, na.rm = TRUE)</span></span>
<span id="cb36-8"><a href="#cb36-8"></a><span class="co">#&gt; min(stu_tch_mat_bev$behaviour, na.rm = TRUE)</span></span>
<span id="cb36-9"><a href="#cb36-9"></a></span>
<span id="cb36-10"><a href="#cb36-10"></a>mdl_stu_tch_mat_bev <span class="ot">&lt;-</span> <span class="fu">lm</span>(maths <span class="sc">~</span> stu_tch_rat <span class="sc">+</span> behaviour, <span class="at">data=</span>stu_tch_mat_bev)</span>
<span id="cb36-11"><a href="#cb36-11"></a><span class="fu">summary</span>(mdl_stu_tch_mat_bev)</span>
<span id="cb36-12"><a href="#cb36-12"></a></span>
<span id="cb36-13"><a href="#cb36-13"></a><span class="co">#&gt; both factors are significant p&lt;2e-16 ***, but with low estimates/betas, </span></span>
<span id="cb36-14"><a href="#cb36-14"></a><span class="co">#&gt; i.e. one extra student per teacher decreases </span></span>
<span id="cb36-15"><a href="#cb36-15"></a><span class="co">#&gt; the maths score by 1.2 points and the aggregated student behaviour hinder </span></span>
<span id="cb36-16"><a href="#cb36-16"></a><span class="co">#&gt; learning decreases maths by 11.1 points </span></span>
<span id="cb36-17"><a href="#cb36-17"></a><span class="co">#&gt; (max behaviour = 3.6274, min = -4.3542), additionally the R squared value </span></span>
<span id="cb36-18"><a href="#cb36-18"></a><span class="co">#&gt; is better, but still low 0.05619</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="9" type="1">
<li>Explore the schools data set to look at other interesting models. The school data set has a lot more numeric/continuous fields than the student table! To find these fields use this code:</li>
</ol>
<div class="cell">
<details><summary>find numeric fields</summary><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a><span class="co"># to get the names of numeric fields along with their labels</span></span>
<span id="cb37-2"><a href="#cb37-2"></a>nms <span class="ot">&lt;-</span> PISA_2018_school <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span> <span class="fu">names</span>()</span>
<span id="cb37-3"><a href="#cb37-3"></a>lbls <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(nms,<span class="sc">~</span>{</span>
<span id="cb37-4"><a href="#cb37-4"></a>  lbl <span class="ot">&lt;-</span> <span class="fu">attr</span>(PISA_2018_school[[.x]], <span class="st">"label"</span>)</span>
<span id="cb37-5"><a href="#cb37-5"></a>  nme <span class="ot">&lt;-</span> .x</span>
<span id="cb37-6"><a href="#cb37-6"></a>  row <span class="ot">&lt;-</span> <span class="fu">c</span>(nme, lbl)</span>
<span id="cb37-7"><a href="#cb37-7"></a>  <span class="fu">names</span>(row) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"name"</span>, <span class="st">"label"</span>)</span>
<span id="cb37-8"><a href="#cb37-8"></a>  <span class="fu">return</span>(row)</span>
<span id="cb37-9"><a href="#cb37-9"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="10" type="1">
<li><p>In pairs discuss how you could use correlation and regression in your own research. Start building some models to explore the data sets.</p></li>
<li><p>Recreate the Stoet &amp; Geary analysis (see <a href="#sec-standard-stoet-geary">Section&nbsp;9.4</a>) to see if there is a “gender gap in intraindividual <strong>mathematics</strong> scores” that is “larger in more gender-equal countries”. You might expect this to be the case as it exists for science. Is this a STEM wide finding? How does the science model look for 2018 data? Was it a one off finding?</p></li>
</ol>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a><span class="co"># standardise the results for each student in line with pg7</span></span>
<span id="cb38-2"><a href="#cb38-2"></a><span class="co"># https://eprints.leedsbeckett.ac.uk/id/eprint/4753/6/symplectic-version.pdf</span></span>
<span id="cb38-3"><a href="#cb38-3"></a></span>
<span id="cb38-4"><a href="#cb38-4"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb38-5"><a href="#cb38-5"></a><span class="fu">library</span>(arrow)</span>
<span id="cb38-6"><a href="#cb38-6"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb38-7"><a href="#cb38-7"></a></span>
<span id="cb38-8"><a href="#cb38-8"></a>PISA_2015_GGGI <span class="ot">&lt;-</span> <span class="fu">left_join</span>(</span>
<span id="cb38-9"><a href="#cb38-9"></a>  PISA_2015 <span class="sc">%&gt;%</span> <span class="fu">select</span>(CNT, ST004D01T, PV1MATH, PV1SCIE, PV1READ, SCIEEFF),</span>
<span id="cb38-10"><a href="#cb38-10"></a>  GGGI <span class="sc">%&gt;%</span> <span class="fu">select</span>(Country, Overall.Score),</span>
<span id="cb38-11"><a href="#cb38-11"></a>  <span class="at">by=</span><span class="fu">c</span>(<span class="st">"CNT"</span><span class="ot">=</span><span class="st">"Country"</span>))</span>
<span id="cb38-12"><a href="#cb38-12"></a></span>
<span id="cb38-13"><a href="#cb38-13"></a><span class="co"># step 1</span></span>
<span id="cb38-14"><a href="#cb38-14"></a>PISA_2015z <span class="ot">&lt;-</span> PISA_2015_GGGI <span class="sc">%&gt;%</span> </span>
<span id="cb38-15"><a href="#cb38-15"></a>  <span class="fu">rename</span>(<span class="at">gender =</span> ST004D01T) <span class="sc">%&gt;%</span></span>
<span id="cb38-16"><a href="#cb38-16"></a>  <span class="fu">group_by</span>(CNT) <span class="sc">%&gt;%</span></span>
<span id="cb38-17"><a href="#cb38-17"></a>  <span class="fu">mutate</span>(<span class="at">zMaths   =</span> <span class="fu">scale</span>(PV1MATH),</span>
<span id="cb38-18"><a href="#cb38-18"></a>         <span class="at">zScience =</span> <span class="fu">scale</span>(PV1SCIE), </span>
<span id="cb38-19"><a href="#cb38-19"></a>         <span class="at">zReading =</span> <span class="fu">scale</span>(PV1READ))</span>
<span id="cb38-20"><a href="#cb38-20"></a></span>
<span id="cb38-21"><a href="#cb38-21"></a><span class="co"># step 2</span></span>
<span id="cb38-22"><a href="#cb38-22"></a>PISA_2015z <span class="ot">&lt;-</span> PISA_2015z <span class="sc">%&gt;%</span> </span>
<span id="cb38-23"><a href="#cb38-23"></a>  <span class="fu">mutate</span>(<span class="at">zGeneral =</span> (zMaths <span class="sc">+</span> zScience <span class="sc">+</span> zReading) <span class="sc">/</span> <span class="dv">3</span>)</span>
<span id="cb38-24"><a href="#cb38-24"></a></span>
<span id="cb38-25"><a href="#cb38-25"></a><span class="co"># step 3</span></span>
<span id="cb38-26"><a href="#cb38-26"></a>PISA_2015z <span class="ot">&lt;-</span> PISA_2015z <span class="sc">%&gt;%</span> </span>
<span id="cb38-27"><a href="#cb38-27"></a>  <span class="fu">mutate</span>(<span class="at">rel_MATH =</span> zMaths   <span class="sc">-</span> zGeneral,</span>
<span id="cb38-28"><a href="#cb38-28"></a>         <span class="at">rel_SCIE =</span> zScience <span class="sc">-</span> zGeneral,</span>
<span id="cb38-29"><a href="#cb38-29"></a>         <span class="at">rel_READ =</span> zReading <span class="sc">-</span> zGeneral)</span>
<span id="cb38-30"><a href="#cb38-30"></a></span>
<span id="cb38-31"><a href="#cb38-31"></a><span class="co"># step 4 part 1</span></span>
<span id="cb38-32"><a href="#cb38-32"></a>PISA_2015z <span class="ot">&lt;-</span> PISA_2015z <span class="sc">%&gt;%</span> </span>
<span id="cb38-33"><a href="#cb38-33"></a>  <span class="fu">group_by</span>(CNT, gender) <span class="sc">%&gt;%</span></span>
<span id="cb38-34"><a href="#cb38-34"></a>  <span class="fu">summarise</span>(<span class="at">zMaths =</span> <span class="fu">mean</span>(zMaths, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb38-35"><a href="#cb38-35"></a>            <span class="at">zScience =</span> <span class="fu">mean</span>(zScience, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb38-36"><a href="#cb38-36"></a>            <span class="at">zReading =</span> <span class="fu">mean</span>(zReading, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb38-37"><a href="#cb38-37"></a>            <span class="at">zGeneral =</span> <span class="fu">mean</span>(zGeneral, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb38-38"><a href="#cb38-38"></a>            <span class="at">rel_MATH =</span> zMaths <span class="sc">-</span> zGeneral,</span>
<span id="cb38-39"><a href="#cb38-39"></a>            <span class="at">rel_SCIE =</span> zScience <span class="sc">-</span> zGeneral,</span>
<span id="cb38-40"><a href="#cb38-40"></a>            <span class="at">rel_READ =</span> zReading <span class="sc">-</span> zGeneral,</span>
<span id="cb38-41"><a href="#cb38-41"></a>            <span class="at">gggi =</span> <span class="fu">unique</span>(Overall.Score))</span>
<span id="cb38-42"><a href="#cb38-42"></a></span>
<span id="cb38-43"><a href="#cb38-43"></a><span class="co"># step 4 part 2</span></span>
<span id="cb38-44"><a href="#cb38-44"></a>pisa_gggi_diff <span class="ot">&lt;-</span> PISA_2015z <span class="sc">%&gt;%</span></span>
<span id="cb38-45"><a href="#cb38-45"></a>  <span class="fu">select</span>(CNT, gender, gggi, rel_MATH) <span class="sc">%&gt;%</span></span>
<span id="cb38-46"><a href="#cb38-46"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> gender,</span>
<span id="cb38-47"><a href="#cb38-47"></a>              <span class="at">values_from =</span> rel_MATH) <span class="sc">%&gt;%</span></span>
<span id="cb38-48"><a href="#cb38-48"></a>  <span class="fu">mutate</span>(<span class="at">difference =</span>  Male <span class="sc">-</span> Female)</span>
<span id="cb38-49"><a href="#cb38-49"></a></span>
<span id="cb38-50"><a href="#cb38-50"></a><span class="fu">ggplot</span>(pisa_gggi_diff,</span>
<span id="cb38-51"><a href="#cb38-51"></a>       <span class="fu">aes</span>(<span class="at">x=</span>difference, <span class="at">y=</span>gggi)) <span class="sc">+</span> </span>
<span id="cb38-52"><a href="#cb38-52"></a>  <span class="fu">geom_point</span>(<span class="at">colour=</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb38-53"><a href="#cb38-53"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb38-54"><a href="#cb38-54"></a>  <span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label=</span>CNT),</span>
<span id="cb38-55"><a href="#cb38-55"></a>            <span class="at">box.padding =</span> <span class="fl">0.2</span>,</span>
<span id="cb38-56"><a href="#cb38-56"></a>            <span class="at">max.overlaps =</span> <span class="cn">Inf</span>,</span>
<span id="cb38-57"><a href="#cb38-57"></a>            <span class="at">colour=</span><span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb38-58"><a href="#cb38-58"></a>  <span class="fu">xlab</span>(<span class="fu">paste0</span>(<span class="st">"relative difference in PV1MATH scores (male-female)"</span>))</span>
<span id="cb38-59"><a href="#cb38-59"></a></span>
<span id="cb38-60"><a href="#cb38-60"></a><span class="co"># perform correlation analysis</span></span>
<span id="cb38-61"><a href="#cb38-61"></a>result <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(pisa_gggi_diff<span class="sc">$</span>gggi, </span>
<span id="cb38-62"><a href="#cb38-62"></a>                    pisa_gggi_diff<span class="sc">$</span>difference, </span>
<span id="cb38-63"><a href="#cb38-63"></a>                    <span class="at">method=</span><span class="st">"spearman"</span>)</span>
<span id="cb38-64"><a href="#cb38-64"></a>result</span>
<span id="cb38-65"><a href="#cb38-65"></a><span class="co">#&gt; this result isn't significant as p-value &gt; 0.05</span></span>
<span id="cb38-66"><a href="#cb38-66"></a><span class="co">#&gt; additionally the correlation coefficient is negative</span></span>
<span id="cb38-67"><a href="#cb38-67"></a><span class="co">#&gt; this suggests that the STEM gender paradox doesn't apply to maths.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div>
</section><section id="task-2-correlation-tasks" class="level2" data-number="8.2"><h2 data-number="8.2" class="anchored" data-anchor-id="task-2-correlation-tasks">
<span class="header-section-number">8.2</span> Task 2 Correlation tasks</h2>
<div class="question">
<p>Use <code>cor.test</code> to explore the following relationships:</p>
<ol type="1">
<li>
<code>PV1MATH</code> to <code>PV1SCIE</code>, is this a stronger relationship than that between Maths and Reading?</li>
</ol>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="fu">cor.test</span>(PISA_2018<span class="sc">$</span>PV1MATH, PISA_2018<span class="sc">$</span>PV1SCIE, <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb39-2"><a href="#cb39-2"></a><span class="co">#&gt; cor 0.8451287</span></span>
<span id="cb39-3"><a href="#cb39-3"></a></span>
<span id="cb39-4"><a href="#cb39-4"></a><span class="fu">cor.test</span>(PISA_2018<span class="sc">$</span>PV1MATH, PISA_2018<span class="sc">$</span>PV1READ, <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb39-5"><a href="#cb39-5"></a><span class="co">#&gt; cor 0.828626</span></span>
<span id="cb39-6"><a href="#cb39-6"></a></span>
<span id="cb39-7"><a href="#cb39-7"></a><span class="co">#&gt; very slightly, yes!</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="2" type="1">
<li>The wealth <code>WEALTH</code> of females <code>ST004D01T</code> and their Reading <code>PV1READ</code> score, how does this compare to males? Why might they be different?</li>
</ol>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a>data <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ST004D01T <span class="sc">==</span> <span class="st">"Female"</span>)</span>
<span id="cb40-2"><a href="#cb40-2"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>WEALTH, data<span class="sc">$</span>PV1READ, <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb40-3"><a href="#cb40-3"></a></span>
<span id="cb40-4"><a href="#cb40-4"></a></span>
<span id="cb40-5"><a href="#cb40-5"></a>data <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ST004D01T <span class="sc">==</span> <span class="st">"Male"</span>)</span>
<span id="cb40-6"><a href="#cb40-6"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>WEALTH, data<span class="sc">$</span>PV1READ, <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb40-7"><a href="#cb40-7"></a><span class="co">#&gt; cor 0.2553069</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="3" type="1">
<li>For the <code>United Kingdom</code> How does the sense of belonging to school <code>BELONG</code> correlate with the attitude to learning activities <code>ATTLNACT</code>? How does the UK compare against other countries?</li>
</ol>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>data <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(CNT <span class="sc">==</span> <span class="st">"United Kingdom"</span>)</span>
<span id="cb41-2"><a href="#cb41-2"></a><span class="fu">cor.test</span>(data<span class="sc">$</span>BELONG, data<span class="sc">$</span>ATTLNACT, <span class="at">method =</span> <span class="st">"pearson"</span>)</span>
<span id="cb41-3"><a href="#cb41-3"></a><span class="co">#&gt; cor 0.1314652</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you want to find all the <code>numeric</code> fields, i.e.&nbsp;the fields that you can easily run correlation calculations on, use the following code to list them:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a>PISA_2018 <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span> <span class="fu">names</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "WVARSTRR"   "ESCS"       "LMINS"      "CNTSCHID"   "CNTSTUID"  
 [6] "ST060Q01NA" "MMINS"      "SMINS"      "TMINS"      "CULTPOSS"  
[11] "WEALTH"     "PV1MATH"    "PV1READ"    "PV1SCIE"    "ATTLNACT"  
 [ reached getOption("max.print") -- omitted 2 entries ]</code></pre>
</div>
</div>
</div>
</div>
</section><section id="task-3-regression-tasks" class="level2" data-number="8.3"><h2 data-number="8.3" class="anchored" data-anchor-id="task-3-regression-tasks">
<span class="header-section-number">8.3</span> Task 3 Regression Tasks</h2>
<div class="question">
<ol type="1">
<li><p>Is it reasonable to presume that using 5 interventions from the education endowment foundation toolkit, each with effect-sizes of 0.1, i.e.&nbsp;2 months improvement, will increase the progress for the average student in your class by 10 months (5 * 2)?</p></li>
<li><p>Run a regression model to look at how science grades predict Maths outcomes in UK students. How does this compare to students in France?</p></li>
</ol>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a>mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(PV1MATH <span class="sc">~</span> PV1SCIE, </span>
<span id="cb44-2"><a href="#cb44-2"></a>          <span class="at">data=</span>PISA_2018 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span>))</span>
<span id="cb44-3"><a href="#cb44-3"></a><span class="fu">summary</span>(mdl)</span>
<span id="cb44-4"><a href="#cb44-4"></a><span class="co">#&gt; Estimate = 0.757</span></span>
<span id="cb44-5"><a href="#cb44-5"></a><span class="co">#&gt; p&lt;0.001</span></span>
<span id="cb44-6"><a href="#cb44-6"></a><span class="co">#&gt; R2 = 0.6378</span></span>
<span id="cb44-7"><a href="#cb44-7"></a></span>
<span id="cb44-8"><a href="#cb44-8"></a>mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(PV1MATH <span class="sc">~</span> PV1SCIE, </span>
<span id="cb44-9"><a href="#cb44-9"></a>          <span class="at">data=</span>PISA_2018 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"France"</span>))</span>
<span id="cb44-10"><a href="#cb44-10"></a><span class="fu">summary</span>(mdl)</span>
<span id="cb44-11"><a href="#cb44-11"></a><span class="co">#&gt; Estimate = 0.834</span></span>
<span id="cb44-12"><a href="#cb44-12"></a><span class="co">#&gt; p&lt;0.001</span></span>
<span id="cb44-13"><a href="#cb44-13"></a><span class="co">#&gt; R2 = 0.7326</span></span>
<span id="cb44-14"><a href="#cb44-14"></a></span>
<span id="cb44-15"><a href="#cb44-15"></a><span class="co">#&gt; both models are significant, but the model in France has a higher R squared value, i.e. Science is a better predictor of maths outcomes in France than it is in the UK.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="3" type="1">
<li>Create a linear model to look at how wealth <code>WEALTH</code> influences Maths grades in the United Kingdom and Belarus. If we use the Education Endowment Foundation’s interpretation of effect sizes <span class="citation" data-cites="higgins2016sutton">(<a href="#ref-higgins2016sutton" role="doc-biblioref">Higgins et al. 2016, 5</a>)</span> what is the impact of increasing the wealth of students in each country?</li>
</ol>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a>mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(PV1MATH <span class="sc">~</span> WEALTH, </span>
<span id="cb45-2"><a href="#cb45-2"></a>          <span class="at">data=</span>PISA_2018 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span>))</span>
<span id="cb45-3"><a href="#cb45-3"></a><span class="fu">summary</span>(mdl)</span>
<span id="cb45-4"><a href="#cb45-4"></a><span class="co">#&gt; Estimate = 14.3</span></span>
<span id="cb45-5"><a href="#cb45-5"></a><span class="co">#&gt; p&lt;0.001</span></span>
<span id="cb45-6"><a href="#cb45-6"></a><span class="co">#&gt; R2 = 0.01999</span></span>
<span id="cb45-7"><a href="#cb45-7"></a><span class="co">#&gt; this is just below 0.02, meaning the model has "Very low or no impact"</span></span>
<span id="cb45-8"><a href="#cb45-8"></a></span>
<span id="cb45-9"><a href="#cb45-9"></a>mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(PV1MATH <span class="sc">~</span> WEALTH, </span>
<span id="cb45-10"><a href="#cb45-10"></a>          <span class="at">data=</span>PISA_2018 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"Belarus"</span>))</span>
<span id="cb45-11"><a href="#cb45-11"></a><span class="fu">summary</span>(mdl)</span>
<span id="cb45-12"><a href="#cb45-12"></a><span class="co">#&gt; Estimate = 31.4</span></span>
<span id="cb45-13"><a href="#cb45-13"></a><span class="co">#&gt; p&lt;0.001</span></span>
<span id="cb45-14"><a href="#cb45-14"></a><span class="co">#&gt; R2 = 0.05476</span></span>
<span id="cb45-15"><a href="#cb45-15"></a><span class="co">#&gt; Wealth has a greater impact on Maths results in Belarus than in the UK, with an effect size of "Low"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div>
</section><section id="task-4-linear-regression-tasks" class="level2" data-number="8.4"><h2 data-number="8.4" class="anchored" data-anchor-id="task-4-linear-regression-tasks">
<span class="header-section-number">8.4</span> Task 4 Linear regression tasks</h2>
<div class="question">
<ol type="1">
<li>What errors can you see in this code:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a><span class="fu">ml</span>(ST113Q01TA <span class="sc">~</span> ST004D01T, WEALTH, <span class="at">data =</span> PISA_2015)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<details><summary>answer</summary><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1"></a><span class="co"># 1. lm rather than ml</span></span>
<span id="cb47-2"><a href="#cb47-2"></a><span class="co"># 2. + between ST004D01T + WEALTH, rather than an ,</span></span>
<span id="cb47-3"><a href="#cb47-3"></a><span class="fu">lm</span>(ST113Q01TA <span class="sc">~</span> ST004D01T <span class="sc">+</span> WEALTH, <span class="at">data =</span> PISA_2015)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<ol start="2" type="1">
<li>PV1MATH given PV1READ and PV1SCIE</li>
</ol>
<ol start="3" type="1">
<li>
</li></ol>
</div>
</section></section><section id="extentsion-tasks" class="level1" data-number="9"><h1 data-number="9">
<span class="header-section-number">9</span> Extentsion tasks</h1>
<section id="sec-Stoet-Geary" class="level2" data-number="9.1"><h2 data-number="9.1" class="anchored" data-anchor-id="sec-Stoet-Geary">
<span class="header-section-number">9.1</span> Recreating Stoet and Geary’s paper</h2>
<p>Stoet and Geary’s 2018 paper: <em>“The Gender-Equality Paradox in Science, Technology, Engineering, and Mathematics Education”</em> presented controversial findings, including how the increased female uptake of STEM degrees in country could be partially explained (using regression) by the decreased gender equality in that country. We are going to explore part of this paper by looking at another finding (figure 3a) that looked at girls’ achievement in the <code>PISA_2015</code> science test compared to their maths and reading grades. Comparing this relative grade to boys in the same country, it showed that as gender equality of their country increased, the gap got bigger, i.e.&nbsp;the more gender equal a country, the worse the female relative performance in science.</p>
<blockquote class="blockquote">
<p>The gender gap in intraindividual science scores (a) was larger in more gender-equal countries (<em>r<sub>s</sub></em> = .42)</p>
</blockquote>
<!-- fields used by stoet geary and 2012 equivalents

MATHEFF 2012 MATINTFC 2012 SCIEEFF 2015-->
</section><section id="loading-data-sets" class="level2" data-number="9.2"><h2 data-number="9.2" class="anchored" data-anchor-id="loading-data-sets">
<span class="header-section-number">9.2</span> Loading data sets</h2>
<p>To perform more complex analysis you will often want to join different data sets together. <span class="citation" data-cites="stoet2018gender">Stoet and Geary (<a href="#ref-stoet2018gender" role="doc-biblioref">2018</a>)</span> explore gender differences in outcomes with gender equality in countries (see their figures 3 and 4), by using the <code>PISA_2015</code> data set with the science efficacy <code>SCIEEFF</code>, and science performance (maybe <code>PV1SCIE</code>, or a aggregation of <code>PV1</code>, <code>PV2</code> etc ) fields; mapping this data set to the 2015 Global Gender Gap Index (GGGI). Let’s try and recreate what they did.</p>
<p>First we are going to download the GGGI, unfortunately, it’s difficult to find the 2015 data set, so we’ll use 2013 instead, which can be found <a href="https://data.humdata.org/dataset/29f2f52f-a9c2-4ff9-a99e-42b894dc18e9/resource/a8fe8c72-1359-4ce3-b8cc-03d9e5e85875/download/table-3b-detailed-rankings-2013.csv">here</a></p>
<p>The data is in a <code>.csv</code> format so we need to use <code>read.csv</code> to get it into R (make sure that you use <code>read.csv</code> rather than <code>read_csv</code> as the names will come out slightly differently)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a><span class="co"># load the GGGI</span></span>
<span id="cb48-2"><a href="#cb48-2"></a>GGGI <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"&lt;folder&gt;table-3b-detailed-rankings-2013.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If we look at the names of the GGGI fields we find that there is a <code>Country</code> column and the <code>Overall.Score</code> column, these are the columns that we are interested in. We can also see that many of the top scoring countries, i.e.&nbsp;those with better gender equality are Nordic countries.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1"></a>GGGI <span class="sc">%&gt;%</span> <span class="fu">head</span>(<span class="dv">5</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Country, Overall.Score)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Country Overall.Score
1     Iceland        0.8731
2     Finland        0.8421
3      Norway        0.8417
4      Sweden        0.8129
5 Philippines        0.7832</code></pre>
</div>
</div>
<p>Now we will load the 2015 PISA data set, we have a <code>.parquet</code> copy for you <a href="https://drive.google.com/file/d/18NpQO1DGY5dnjnlR2b3IF9Zv8xtpc1Fk/view?usp=share_link">here</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1"></a><span class="co"># load PISA_2015 student data set</span></span>
<span id="cb51-2"><a href="#cb51-2"></a>PISA_2015 <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">"&lt;folder&gt;PISA_2015_student_subset.parquet"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="sec-leftjoin" class="level2" data-number="9.3"><h2 data-number="9.3" class="anchored" data-anchor-id="sec-leftjoin">
<span class="header-section-number">9.3</span> Linking data using <code>left_join</code>
</h2>
<p>To link the <code>GGGI</code> to the <code>PISA_2015</code> data set we will use the <code>left_join</code> function from the tidyverse. This takes a few parameters</p>
<pre><code>left_join(&lt;table_1&gt;, &lt;table_2&gt;, by=&lt;matching_field[s]&gt;)</code></pre>
<p>We will now join a subset of the <code>PISA_2015</code> data set to a subset of the <code>GGGI</code> scores:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1"></a>PISA_2015_GGGI <span class="ot">&lt;-</span> <span class="fu">left_join</span>(</span>
<span id="cb53-2"><a href="#cb53-2"></a>  PISA_2015 <span class="sc">%&gt;%</span> <span class="fu">select</span>(CNT, ST004D01T, PV1MATH, PV1SCIE, PV1READ, SCIEEFF),</span>
<span id="cb53-3"><a href="#cb53-3"></a>  GGGI <span class="sc">%&gt;%</span> <span class="fu">select</span>(Country, Overall.Score),</span>
<span id="cb53-4"><a href="#cb53-4"></a>  <span class="at">by=</span><span class="fu">c</span>(<span class="st">"CNT"</span><span class="ot">=</span><span class="st">"Country"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>line 1, assigns <code>&lt;-</code> the result of the <code>left_join</code> to a new object, <code>PISA_2015_GGGI</code>,</li>
<li>line 2, specifies <code>&lt;table_1&gt;</code> to be <code>PISA_2015</code> with the selected fields, note we have chosen to use <code>PV1</code> grades here, it’s unclear what the original paper uses (See <strong>?@sec-PV</strong> for a discussion on the use of <code>PV</code> grades)</li>
<li>line 3, specifies <code>&lt;table_2&gt;</code> to be <code>GGGI</code> with just the country and <code>Overall.Score</code> fields</li>
<li>line 4, specifies the <code>&lt;matching_field&gt;</code> to be <code>CNT</code>from <code>PISA_2015</code> and <code>Country</code> from <code>GGGI</code>, this means that the data in <code>&lt;table_2&gt;</code> will be added to <code>&lt;table_1&gt;</code> where <code>CNT</code> and <code>Country</code> are the same. For example for every entry of <code>Finland</code> in <code>PISA_2015</code>, the <code>Overall.Score</code> of <code>0.8421</code> will be added. Where it can’t find a matching country, e.g.&nbsp;Albania doesn’t have a GGGI entry, <code>NA</code> will be added.</li>
</ul>
<p>You can see the new data set has attached the <code>Overall.Score</code> field from <code>GGGI</code> to the selected fields from <code>PISA_2015</code>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  CNT     ST004D01T PV1MATH PV1SCIE PV1READ SCIEEFF Overall.Score
  &lt;chr&gt;   &lt;fct&gt;       &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;         &lt;dbl&gt;
1 Albania Female       463.    517.    430.      NA         0.641
2 Albania Female       430.    480.    463.      NA         0.641
3 Albania Female       303.    447.    503.      NA         0.641</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>There are multiple types of join in the tidyverse, you can find out more about them <a href="https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf">here</a></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><img src="..\images/joins.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">The available joins in the tidyverse, CC 4.0, by rstudio.com</figcaption></figure>
</div>
</div>
</div>
</section><section id="sec-standard-stoet-geary" class="level2" data-number="9.4"><h2 data-number="9.4" class="anchored" data-anchor-id="sec-standard-stoet-geary">
<span class="header-section-number">9.4</span> Standardising PISA results</h2>
<p>Next, we will try to wrangle the data into shape to recreate figure 3 from <span class="citation" data-cites="stoet2018gender">Stoet and Geary (<a href="#ref-stoet2018gender" role="doc-biblioref">2018</a>)</span>. To do this we first need to standardise the grades for maths, science and reading so we can compare the results of students between countries without low performing or high performing countries skewing the results (see <a href="#sec-z-values">Chapter&nbsp;7</a> for details on how to standardise data). Following the steps outlined on page 7:</p>
<blockquote class="blockquote">
<ol type="1">
<li>We standardized the mathematics, science, and reading scores on a nation-by-nation basis. We call these new standardized scores <em>zMath</em>, <em>zRead</em>, and <em>zScience</em>.</li>
<li>We calculated for each student the standardized average score of the new z-scores and we call this <em>zGeneral</em>.</li>
<li>Then, we calculated for each student their intra-individual strengths by subtracting <em>zGeneral</em> as follows: <em>relativeSciencestrength = zScience - zGeneral</em>, <em>relativeMathstrength = zMath - zGeneral</em>, <em>relativeReadingstrength = zReading - zGeneral</em>.</li>
<li>Finally, using these new intra-individual (relative) scores, we calculated for each country the averages for boys and girls and subtracted those to calculate the gender gaps in relative academic strengths</li>
</ol>
</blockquote>
<p>produces the following code:</p>
<div class="cell">
<details><summary>code</summary><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1"></a><span class="co"># standardise the results for each student in line with pg7</span></span>
<span id="cb55-2"><a href="#cb55-2"></a><span class="co"># https://eprints.leedsbeckett.ac.uk/id/eprint/4753/6/symplectic-version.pdf</span></span>
<span id="cb55-3"><a href="#cb55-3"></a></span>
<span id="cb55-4"><a href="#cb55-4"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb55-5"><a href="#cb55-5"></a><span class="fu">library</span>(arrow)</span>
<span id="cb55-6"><a href="#cb55-6"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb55-7"><a href="#cb55-7"></a></span>
<span id="cb55-8"><a href="#cb55-8"></a><span class="co"># step 1</span></span>
<span id="cb55-9"><a href="#cb55-9"></a>PISA_2015z <span class="ot">&lt;-</span> PISA_2015_GGGI <span class="sc">%&gt;%</span> </span>
<span id="cb55-10"><a href="#cb55-10"></a>  <span class="fu">rename</span>(<span class="at">gender =</span> ST004D01T) <span class="sc">%&gt;%</span></span>
<span id="cb55-11"><a href="#cb55-11"></a>  <span class="fu">group_by</span>(CNT) <span class="sc">%&gt;%</span></span>
<span id="cb55-12"><a href="#cb55-12"></a>  <span class="fu">mutate</span>(<span class="at">zMaths   =</span> <span class="fu">scale</span>(PV1MATH),</span>
<span id="cb55-13"><a href="#cb55-13"></a>         <span class="at">zScience =</span> <span class="fu">scale</span>(PV1SCIE), </span>
<span id="cb55-14"><a href="#cb55-14"></a>         <span class="at">zReading =</span> <span class="fu">scale</span>(PV1READ))</span>
<span id="cb55-15"><a href="#cb55-15"></a></span>
<span id="cb55-16"><a href="#cb55-16"></a><span class="co"># step 2</span></span>
<span id="cb55-17"><a href="#cb55-17"></a>PISA_2015z <span class="ot">&lt;-</span> PISA_2015z <span class="sc">%&gt;%</span> </span>
<span id="cb55-18"><a href="#cb55-18"></a>  <span class="fu">mutate</span>(<span class="at">zGeneral =</span> (zMaths <span class="sc">+</span> zScience <span class="sc">+</span> zReading) <span class="sc">/</span> <span class="dv">3</span>)</span>
<span id="cb55-19"><a href="#cb55-19"></a></span>
<span id="cb55-20"><a href="#cb55-20"></a><span class="co"># step 3</span></span>
<span id="cb55-21"><a href="#cb55-21"></a>PISA_2015z <span class="ot">&lt;-</span> PISA_2015z <span class="sc">%&gt;%</span> </span>
<span id="cb55-22"><a href="#cb55-22"></a>  <span class="fu">mutate</span>(<span class="at">rel_MATH =</span> zMaths   <span class="sc">-</span> zGeneral,</span>
<span id="cb55-23"><a href="#cb55-23"></a>         <span class="at">rel_SCIE =</span> zScience <span class="sc">-</span> zGeneral,</span>
<span id="cb55-24"><a href="#cb55-24"></a>         <span class="at">rel_READ =</span> zReading <span class="sc">-</span> zGeneral)</span>
<span id="cb55-25"><a href="#cb55-25"></a></span>
<span id="cb55-26"><a href="#cb55-26"></a><span class="co"># step 4 part 1</span></span>
<span id="cb55-27"><a href="#cb55-27"></a>PISA_2015z <span class="ot">&lt;-</span> PISA_2015z <span class="sc">%&gt;%</span> </span>
<span id="cb55-28"><a href="#cb55-28"></a>  <span class="fu">group_by</span>(CNT, gender) <span class="sc">%&gt;%</span></span>
<span id="cb55-29"><a href="#cb55-29"></a>  <span class="fu">summarise</span>(<span class="at">zMaths =</span> <span class="fu">mean</span>(zMaths, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb55-30"><a href="#cb55-30"></a>            <span class="at">zScience =</span> <span class="fu">mean</span>(zScience, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb55-31"><a href="#cb55-31"></a>            <span class="at">zReading =</span> <span class="fu">mean</span>(zReading, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb55-32"><a href="#cb55-32"></a>            <span class="at">zGeneral =</span> <span class="fu">mean</span>(zGeneral, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb55-33"><a href="#cb55-33"></a>            <span class="at">rel_MATH =</span> zMaths <span class="sc">-</span> zGeneral,</span>
<span id="cb55-34"><a href="#cb55-34"></a>            <span class="at">rel_SCIE =</span> zScience <span class="sc">-</span> zGeneral,</span>
<span id="cb55-35"><a href="#cb55-35"></a>            <span class="at">rel_READ =</span> zReading <span class="sc">-</span> zGeneral,</span>
<span id="cb55-36"><a href="#cb55-36"></a>            <span class="at">gggi =</span> <span class="fu">unique</span>(Overall.Score))</span>
<span id="cb55-37"><a href="#cb55-37"></a></span>
<span id="cb55-38"><a href="#cb55-38"></a><span class="co"># step 4 part 2</span></span>
<span id="cb55-39"><a href="#cb55-39"></a>pisa_gggi_diff <span class="ot">&lt;-</span> PISA_2015z <span class="sc">%&gt;%</span></span>
<span id="cb55-40"><a href="#cb55-40"></a>  <span class="fu">select</span>(CNT, gender, gggi, rel_SCIE) <span class="sc">%&gt;%</span></span>
<span id="cb55-41"><a href="#cb55-41"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> gender,</span>
<span id="cb55-42"><a href="#cb55-42"></a>              <span class="at">values_from =</span> rel_SCIE) <span class="sc">%&gt;%</span></span>
<span id="cb55-43"><a href="#cb55-43"></a>  <span class="fu">mutate</span>(<span class="at">difference =</span>  Male <span class="sc">-</span> Female)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Finally we will plot the results:</p>
<div class="cell">
<details><summary>graph code</summary><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb56-2"><a href="#cb56-2"></a></span>
<span id="cb56-3"><a href="#cb56-3"></a><span class="fu">ggplot</span>(pisa_gggi_diff,</span>
<span id="cb56-4"><a href="#cb56-4"></a>       <span class="fu">aes</span>(<span class="at">x=</span>difference, <span class="at">y=</span>gggi)) <span class="sc">+</span> </span>
<span id="cb56-5"><a href="#cb56-5"></a>  <span class="fu">geom_point</span>(<span class="at">colour=</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb56-6"><a href="#cb56-6"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb56-7"><a href="#cb56-7"></a>  <span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label=</span>CNT),</span>
<span id="cb56-8"><a href="#cb56-8"></a>            <span class="at">box.padding =</span> <span class="fl">0.2</span>,</span>
<span id="cb56-9"><a href="#cb56-9"></a>            <span class="at">max.overlaps =</span> <span class="cn">Inf</span>,</span>
<span id="cb56-10"><a href="#cb56-10"></a>            <span class="at">colour=</span><span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb56-11"><a href="#cb56-11"></a>  <span class="fu">xlab</span>(<span class="fu">paste0</span>(<span class="st">"relative difference in PV1SCIE scores (male-female)"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="10-Correlation_and_regression_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The graph is pretty good recreation of what the paper presented, with the general shape the same; differences in grades for each country might be explained by the original paper using 5 plausible values rather than just <code>PV1SCIE</code>, as we have used <span class="citation" data-cites="stoet2020gender">(<a href="#ref-stoet2020gender" role="doc-biblioref">Stoet and Geary 2020</a>)</span>. Does the statistical model stand up to scrutiny? To find out we will use <em>correlation</em>. Stoet and Geary used <em>Spearman’s rho</em>, signified by the <sub><em>s</em></sub> in <em>r<sub>s</sub></em>:</p>
<blockquote class="blockquote">
<p>The most important and novel finding here is that the sex difference in intraindividual strength in science was higher and more favorable to boys in more gender-equal countries, <em>r<sub>s</sub></em> = .42, 95% CI = [.19,.61], <em>p</em> &lt; .001, <em>n</em> = 62 (Fig. 3a)</p>
</blockquote>
<p>We can run our version of this model using the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1"></a>result <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(pisa_gggi_diff<span class="sc">$</span>gggi, </span>
<span id="cb57-2"><a href="#cb57-2"></a>                    pisa_gggi_diff<span class="sc">$</span>difference, </span>
<span id="cb57-3"><a href="#cb57-3"></a>                    <span class="at">method=</span><span class="st">"spearman"</span>)</span>
<span id="cb57-4"><a href="#cb57-4"></a>result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  pisa_gggi_diff$gggi and pisa_gggi_diff$difference
S = 24384, p-value = 0.02763
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
0.2874342 </code></pre>
</div>
</div>
<p>Our model doesn’t show such a strong correlation. In fact, our model shows a “weak positive” relationship of just <code>0.287</code>, albeit a significant one (<code>p&lt;0.05</code>).</p>
<p>For our version of this model it seems unnecessary to use Spearman’s rho, the number of countries we are comparing with valid data is 59 (<code>pisa_gggi_diff %&gt;% na.omit() %&gt;% nrow()</code>), which is greater than 30 and using the <em>central limit theorem</em> we should be able to use <em>Pearson’s r</em>. Additionally,<code>shapiro.test</code>on both difference and<code>gggi</code> give non-significant results, suggesting Pearson is the better test to use here:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1"></a><span class="fu">shapiro.test</span>(pisa_gggi_diff<span class="sc">$</span>gggi) </span>
<span id="cb59-2"><a href="#cb59-2"></a><span class="co">#&gt; p-value = 0.1226</span></span>
<span id="cb59-3"><a href="#cb59-3"></a><span class="fu">shapiro.test</span>(pisa_gggi_diff<span class="sc">$</span>difference)</span>
<span id="cb59-4"><a href="#cb59-4"></a><span class="co">#&gt; p-value = 0.4078</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If we run the model again using Pearson’s r, we get:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1"></a>result <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(pisa_gggi_diff<span class="sc">$</span>gggi, </span>
<span id="cb60-2"><a href="#cb60-2"></a>                    pisa_gggi_diff<span class="sc">$</span>difference, </span>
<span id="cb60-3"><a href="#cb60-3"></a>                    <span class="at">method=</span><span class="st">"pearson"</span>)</span>
<span id="cb60-4"><a href="#cb60-4"></a>result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  pisa_gggi_diff$gggi and pisa_gggi_diff$difference
t = 3.9972, df = 57, p-value = 0.0001863
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.2406661 0.6465242
sample estimates:
      cor 
0.4679109 </code></pre>
</div>
</div>
<p>A result much closer to the one published. The differences here might be the result of the different GGGI data set we used or a difference in the way we calculated <code>difference</code>, or something to do with the correlation model used. It would be good to know!</p>
<p>We can also explore this data using regression and a linear model looking at the relationship between <code>difference</code> in grades and the <code>gggi</code> value for each country:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1"></a>mdl <span class="ot">&lt;-</span> <span class="fu">lm</span>(difference <span class="sc">~</span> gggi, <span class="at">data =</span> pisa_gggi_diff)</span>
<span id="cb62-2"><a href="#cb62-2"></a><span class="fu">summary</span>(mdl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = difference ~ gggi, data = pisa_gggi_diff)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.067343 -0.018964 -0.003605  0.023548  0.083991 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.12926    0.05317  -2.431 0.018228 *  
gggi         0.29826    0.07462   3.997 0.000186 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.03247 on 57 degrees of freedom
  (14 observations deleted due to missingness)
Multiple R-squared:  0.2189,    Adjusted R-squared:  0.2052 
F-statistic: 15.98 on 1 and 57 DF,  p-value: 0.0001863</code></pre>
</div>
</div>
<p>This model also finds a significant difference (<code>p&lt;0.001</code>) and an estimate for gggi of <code>0.298</code>, i.e.&nbsp;for each increase of 1 in gggi, males will do <code>0.298</code> of a standard deviation better than females. The R<sup>2</sup> is pretty decent too at <code>0.219</code> suggesting the finding that Stoet and Geary reported is a sound one.</p>



</section></section><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-coe2002s" class="csl-entry" role="listitem">
Coe, Robert. 2002. <span>“It’s the Effect Size, Stupid.”</span> In <em>British Educational Research Association Annual Conference</em>, 12:14.
</div>
<div id="ref-cohen1962statistical" class="csl-entry" role="listitem">
Cohen, Jacob. 1962. <span>“The Statistical Power of Abnormal-Social Psychological Research: A Review.”</span> <em>The Journal of Abnormal and Social Psychology</em> 65 (3): 145.
</div>
<div id="ref-higgins2016sutton" class="csl-entry" role="listitem">
Higgins, Steve, Maria Katsipataki, AB Villanueva-Aguilera, Robbie Coleman, P Henderson, LE Major, R Coe, and Danielle Mason. 2016. <span>“The Sutton Trust-Education Endowment Foundation Teaching and Learning Toolkit.”</span> <a href="https://dro.dur.ac.uk/20987/1/20987.pdf">https://dro.dur.ac.uk/20987/1/20987.pdf</a>.
</div>
<div id="ref-schafer2019meaningfulness" class="csl-entry" role="listitem">
Schäfer, Thomas, and Marcus A Schwarz. 2019. <span>“The Meaningfulness of Effect Sizes in Psychological Research: Differences Between Sub-Disciplines and the Impact of Potential Biases.”</span> <em>Frontiers in Psychology</em> 10: 813. <a href="https://www.frontiersin.org/articles/10.3389/fpsyg.2019.00813/full">https://www.frontiersin.org/articles/10.3389/fpsyg.2019.00813/full</a>.
</div>
<div id="ref-stoet2018gender" class="csl-entry" role="listitem">
Stoet, Gijsbert, and David C Geary. 2018. <span>“The Gender-Equality Paradox in Science, Technology, Engineering, and Mathematics Education.”</span> <em>Psychological Science</em> 29 (4): 581–93. <a href="https://eprints.leedsbeckett.ac.uk/id/eprint/4753/6/symplectic-version.pdf">https://eprints.leedsbeckett.ac.uk/id/eprint/4753/6/symplectic-version.pdf</a>.
</div>
<div id="ref-stoet2020gender" class="csl-entry" role="listitem">
———. 2020. <span>“Corrigendum: The Gender-Equality Paradox in Science, Technology, Engineering, and Mathematics Education.”</span> <a href="https://journals.sagepub.com/doi/10.1177/0956797619892892">https://journals.sagepub.com/doi/10.1177/0956797619892892</a>.
</div>
<div id="ref-statology2021" class="csl-entry" role="listitem">
Zach. 2021. <span>“The Complete Guide: How to Report Regression Results.”</span> <a href="https://www.statology.org/how-to-report-regression-results/">https://www.statology.org/how-to-report-regression-results/</a>.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>
<ol>
<li id="fn1"><p>https://www.statisticssolutions.com/the-linear-regression-analysis-in-spss/:<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>